Entities/Industry/CTFShops/Quarters/Quarters.as
Really just wanted to get comfortable with pull requests.
Shouldn't be a controversial fix.
=> fixed amount spelling from ammount to amount

Entities/Industry/CTFShops/BoatShop/BoatShop.as
=> Boatshop menu fix

Entities/Characters/Builder/BuilderCommon.as, Entities/Characters/Builder/BuilderInventory.as, Entities/Characters/Builder/BuilderLogic.as, Entities/Common/Building/BlobPlacement.as, Entities/Common/Building/BlockPlacement.as, Entities/Common/Includes/Requirements.as
Not sure if I want to describe this too much.
It fixes the duplication issue as we discussed.
=> Duplication fix

Entities/Characters/Archer/ArcherAnim.as, Entities/Industry/CTFShops/Quarters/Quarters.as
Completes #8. Additionally fixes this issue:
=> Quarters include fix

README.md
Just a minimalistic readme. 
Needs a bit more work.
=> Repository readme

Locales/Russian_ru.json
Unfinished as all translations
=> Added a new russian translation

Rules/CommonScripts/KickAFK.as
Fixes that the AFK kick timer resets on any chat input.
=> AFK kick fix

Rules/CommonScripts/ScoreboardRender.as, Rules/CommonScripts/Timers.as, Rules/CommonScripts/UI/Controls/Specific/UIServerButton.as, Rules/CommonScripts/UI/UI.as, Rules/Main/Scripts/MainMenu.as, Rules/Main/Scripts/MainMenuCommon.as
The planned Angelscript update breaks a few minor things that can be easily fixed.
One of the fixes is a useless copy constructor usage that causes a compile error.  
The other fixes are related to callback handles. Add the assign operator when assigning a function pointer.
These changes should be compatible with the older Angelscript version.
=> [dev][modified] fixed scripts for angelscript update

Entities/Characters/Archer/ArcherLogic.as, Entities/Characters/Builder/BuilderLogic.as, Entities/Characters/Knight/KnightLogic.as, Entities/Common/Factory/Shop.as, Entities/Common/Respawning/OneClassAvailable.as, Entities/Common/Respawning/StandardRespawnCommand.as, Entities/Industry/Factory/Factory.as, Entities/Industry/OldBuildings/Research/ResearchGUI.as, Entities/Industry/OldBuildings/Research/Researching.as, Entities/Industry/Saw/Saw.as, Entities/Industry/Trading/TradingCommon.as, Entities/Industry/Trading/TradingMenu.as, Entities/Industry/Tunnel/TunnelTravel.as, Entities/Industry/Workbench/Workbench.as, Entities/Items/Crate/Crate.as, Entities/Items/Scroll/Scroll.as, Entities/Items/Scroll/Special/ScrollDrought.as, Entities/Natural/Trees/TreeSync.as, Entities/Special/TDM/TDM_Ruins/TDM_Ruins.as, Entities/Special/Tent/TentLogic.as, Entities/Special/WAR/WAR_base/WAR_base.as, Entities/Vehicles/Ballista/Ballista.as, Entities/Vehicles/Boats/WarBoat/WarBoat.as, Rules/CTF/Scripts/CTF_GiveSpawnItems.as
Next I'm going to organize descriptions and costs for easier translation
=> More translatable strings

Rules/CommonScripts/MechanismsCommon.as
This seems to improve the `MechanismServer.as` performance, especially at idle.
Tested in solo Sandbox, at idle:  
`0.00372s` average -> `0.00069s`
=> [modified] improved mechanisms performance at idle

Entities/Common/Respawning/ClassSelectMenu.as, Rules/CTF/Scripts/CTF_GiveSpawnItems.as
=> Translatable classes in class select menu, fixed CTF_GiveSpawnItems.as

Entities/Characters/Archer/ArcherLogic.as, Entities/Characters/Builder/BuilderInventory.as, Entities/Characters/Knight/KnightLogic.as, Entities/Common/Factory/Shop.as, Entities/Industry/CTFShops/Quarters/Quarters.as, Entities/Industry/CTFShops/Storage/Storage.as, Entities/Items/Containers/Chest/Chest.as, Entities/Items/Scroll/Special/ScrollMidas.as, Entities/Items/Scroll/Special/ScrollSuddenGib.as, Entities/Structures/Components/Passive/Magazine/Magazine.as, Entities/Structures/Components/Source/CoinSlot/CoinSlot.as, Entities/Structures/Components/Source/PushButton/PushButton.as, Entities/Vehicles/Common/PopWheelsOff.as, Entities/Vehicles/Common/VehicleAttachment.as, Entities/Vehicles/Common/VehicleCommon.as, Rules/CommonScripts/ShowGamemode.as, Rules/CommonScripts/TeamMenu.as, Rules/CommonScripts/TeamMenuJustSpectator.as
=> Translatable class grid menus, generic buttons and shop description

Locales/French_fr.json
I didn't proof read this a lot but this:
- Has the new engine side translations for menus, etc
- Has some strings put in "in advance", in particular ones that are not working engine side yet (tooltips in settings for example)
- Makes the french translation synced with diprog's translation changes
Since the whole file was remade there might be some things gone and changed
=> [updated] french translation

Entities/Materials/Ammunition/MaterialArrow.cfg, Entities/Materials/Ammunition/MaterialBallistaBolt.cfg, Entities/Materials/Ammunition/MaterialBombArrow.as, Entities/Materials/Ammunition/MaterialBombArrow.cfg, Entities/Materials/Ammunition/MaterialFireArrow.cfg, Entities/Materials/Ammunition/MaterialWaterArrow.cfg, Entities/Materials/Construction/MaterialGold.cfg, Entities/Materials/Construction/MaterialStone.cfg, Entities/Materials/Construction/MaterialWood.cfg, Entities/Materials/Explosive/MaterialBomb.as, Entities/Materials/Explosive/MaterialBomb.cfg, Entities/Materials/Explosive/MaterialWaterBomb.as, Entities/Materials/Explosive/MaterialWaterBomb.cfg, Entities/Materials/MaterialCommon.as, Entities/Materials/MaterialMerge.as, Entities/Materials/MaterialStandard.as
More / improved comments.
Semi-colons removed from preprocessor directives.
Underscores removed between type and name in conf's.
=> Material refactor

Rules/CommonScripts/NoSwears.as
Should prevent crashes and replace uppercase swears with uppercase replacements.
=> Chat filter fixes

Entities/Common/Emotes/EmoteBubble.as, Entities/Common/HoverMessage/HoverMessage.as, Entities/Industry/OldBuildings/Research/ResearchGUI.as, Rules/CommonScripts/MarkPlayers.as, Rules/CommonScripts/PlayerCamera.as, Rules/CommonScripts/Spectator.as
Script-side 60fps support.
`ResearchGUI` could be further improved, but it's a bit of a mess with a bit of input logic incorrectly merged with render logic.
=> 60fps final

Entities/Characters/Scripts/EatFoodButton.as
Change for this request https://github.com/transhumandesign/kag-base/issues/98, unused button "v" is for food, spacebar is still for throwing things.
=> different button for healing with food

Entities/Industry/CTFShops/Quarry/Quarry.as
Quarry button is now translatable ("Add fuel")
=> Quarry updates

Entities/Common/Includes/Costs.as, Entities/Industry/CTFShops/Quarry/Quarry.cfg
Everything else costs 50 and drops 50 gold-wise so this should be no exception
=> [modified] Quarry costs 50 gold and drops 50 gold on destruction

Entities/Characters/Builder/BuilderInventory.as
=> [added] Tapping inventory key as builder swaps to last block

Entities/Items/Crate/Crate.as
Crates were going to be kind of OP with/against kegs so these changes should help
- Now you should be able to mill people in crates with saws somewhat more consistently
- Also, half of the explosion damage taken by crates will also be taken by player inside
- Kegs kill crates and the players inside them
- Female player pitch for crate-related voice clips
- Kegs can't be launched as far as other items out of crates by dumping them
- Crates with lit kegs in them are even heavier
=> [modified] Crate/keg/saw interactions + fixes, no full explosion shield

Rules/CommonScripts/ScoreboardRender.as
Shows username if it's different to charactername, otherwise only shows charactername. Will be useful in the future for the reporting system.
=> [added] list of spectators now shows usernames

Entities/Characters/Archer/ArcherAutoPickup.as, Entities/Characters/Builder/BuilderAutoPickup.as, Entities/Characters/Knight/KnightAutoPickup.as
So that builders get the mats they walk over and they don't all get stolen by the crate etc. etc.
=> [modified] Autopickup to player before crate if possible

Rules/CommonScripts/Report.as
All done for now, everything should work as intended seeing as it isn't that big. I will start working on the Discord bot and looking into seclevs to make a nice KAG-Discord interface for admins.
=> [added] finished admin interface

Entities/Characters/Scripts/RunnerDeath.as
fixes issue #159 
tested with current public build and with current test build
=> held items now have momentum when dropped as you die

Rules/CommonScripts/Holiday/Holiday.as
seems to be working, but needs more testing
fixes issue #191
=> fixed holiday.as not removing the scripts properly

Rules/CommonScripts/Report.as, Rules/CommonScripts/ReportRender.as
Should be alright, thanks to @makmoud98 for the help.
=> [fixed] multiple issues including syncing issues

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md
added templates for bug reports and feature pitches, hopefully people will use them
=> [added] issues templates

PULL_REQUEST_TEMPLATE.md
A simple pull request template hopefully people will use it
=> [added] Pull request template

CODE_OF_CONDUCT.md
added boilerplate code of conduct
=> [added] code of conduct

Entities/Industry/CTFShops/BoatShop/BoatShop.as, Entities/Industry/CTFShops/CTFCosts.cfg
Dinghies now cost either 100 wood or 25 coins, but not both.
=> change dinghy cost

Rules/CommonScripts/accolade_data.cfg
Added all current OKSA/Forum/Discord staff, and as many ex-staff members as I could find, including ex-OKSA who resigned, leaving out OKSA who were removed for other reasons. I added Strathos as a prominent modder; there are definitely more to add, but I'm not familiar with the modding scene.
Additionally, I fixed Zanzibar (Guitarman)'s name, and put non-alphabetic names in a consistent sorted order (before alphabetic names).
(pick one)
- **HOLD**: you are aware of some serious issues with your PR. It should not be merged and you will follow up when they are fixed.
A few sentences describing the …
=> Update accolades_data.cfg with OKSA/Forum/Discord staff

Entities/Characters/Scripts/RunnerCollision.as
**READY**
This changes the condition of being 'still' from having a low velocity to not pressing left and right. It makes it much more consistent to crouch dodge.
This resolves #249 
Test 1: Throw a boulder in the air and crouch to dodge it
Test 2: Place a boulder on the ground and crouch grapple through it
=> More consistent crouch dodge

Rules/CommonScripts/ChatCommands.as
_Idea(s) originally suggested by on the official KAG Discord server by dask#5682. Special thanks for Vamist and Biurza for reviewing it._
This PR adds mainly adds new commands that both work in sv_test and Sandbox. I also made more comments to the code (for my new commands and for the preexisting ones) for beginner modders.
Commands that work in Sandbox and/or sv_test (requires one of them to be true before the commands can be done):
- !allmats (spawns 500 wood, 500 stone, 100 gold)
- !woodstone (spawns 250 wood, 500 stone)
- !stonewood (spawns 500 wood, 250 stone)
- !wood (spawns 250 wood)
- !gold (spawns 200 gold)
- !stones (you can now just type !stone instead - moved it here so this command also work in SBX)
The reason why I included !woodstone/!stonewood is if one wants to build in …
=> !allmats - Sandbox Commands!

Entities/Characters/Knight/Knight.cfg
**READY**
A small change that is a temporary fix for missing knight animations, until someone find right way how solve this problem.
uh, umm, fighting as knight?
_was tested on eu captains._
=> Temporary fix for missing knight animations

Entities/Industry/Fireplace/Fireplace.as, Entities/Industry/Fireplace/Fireplace.cfg, Entities/Items/Food/MakeFood.as
**READY**
- More cooked food options (improved #304 code)
- Steak → Cooked Steak
- Grain → Bread
- Egg → Cake
- Fixed issue where fireplaces were destroyed upon spawning in TDM (thanks @Coroz)
- Caused by them falling slightly and destroying on impact
- Removed fall damage to fix this
- Becomes static when it lands on solid ground
- Increased health
!fireplace
/rcon /loadmap Niiiiii_Watery.png
=> More fireplace improvements

Rules/TDM/Scripts/TDM_Trading.as
(READY)
Fixed description of water bombs in trader shop TDM
Open TDM Trader Shop
=> Fixed description of Water Bombs in TDM. 

Locales/Italian_it.json, Locales/Steam/steam_content_it.txt
Italian translations of Italian_it.json and steam_content_it.txt files.
Italian translations for all the game modes, systems and dlcs. Go to settings -> Misc -> Language to test it out.
=> Italian translation

Rules/CommonScripts/EmoteBinderMenu.as
**READY**
I realised that I overlooked things with my initial implementation of this. Now it doesn't display your menu to others when you're binding your emotes.
Test with another player on a server
I thoroughly tested this on a server with Waxtor and it seems to work perfectly
=> Fixed emote binder menu displaying to everyone

Rules/CTF/mapcycle.cfg
- **READY**
#mapcycle pitch result
Re-add 2 maps from returning maps pool. Moved Radioactive_Dahill and Oodle_Stonethrow to returning maps pool.
=> [modified] #mapcycle results

Rules/CommonScripts/accolade_data.cfg
=> Fixed tern

Rules/CommonScripts/accolade_data.cfg
=> mrpineapple map accolade alain github accolade

Entities/Common/Emotes/EmoteHotkeys.as, Entities/Common/Emotes/EmotesCommon.as, Rules/CommonScripts/EmoteBinderMenu.as
Fixed emote bindings not being read
=> [fixed] emote bindings not being read.

Rules/CommonScripts/ChatCommands.as
**READY**
This goes with my internal PR
- Removed !suicide/!killme commands since they can't use the same cooldown as the menu button
Closes #364
=> Suicide cooldown

Entities/Structures/Door/SwingDoor.as
* **READY**
A tiny fix for correlation between doors and drill. Drilling through doors will be much faster.
Still it need to be discussed before merging.
Sandbox, build doors, use drill on them
=> door-drill correlation

Entities/Characters/Archer/ArcherAnim.as, Entities/Characters/Builder/BuilderAnim.as, Entities/Characters/Knight/KnightAnim.as, Rules/CommonScripts/Accolades.as
- **READY**
Allows for capes to be rewarded in accolades
Add an accolade for yourself with unix date and its duration in months
`Mazey =
cape 1550418701 3;`
=> [added] Cape reward to accolades

Entities/Natural/Trees/BushyTreeLogic.as, Entities/Natural/Trees/PineTreeLogic.as, Entities/Natural/Trees/TreeCommon.as, Entities/Natural/Trees/TreeSync.as
This is a fix to trees not syncing between players #101 . It was caused by misuse of the XORRandom function and some bad code in the onInit hook.
=> [fixed] trees desyncing

Entities/Common/Factory/Shop.as, Entities/Industry/Trading/TradingMenu.as, Rules/CommonScripts/Report.as
**READY**
- Added more restrictions for who you can report
- You can't report yourself
- You can't report bots
- Added client chat messages with the reason for not being able to report a player
- Added '0' key as tenth keybind
- Added keybinds to trading posts
=> Added some suggestions from testing session

Locales/German_de.json
**READY**
This is the German translation of the game. Nothing more to say about it, I guess.
=> German translation

Rules/CommonScripts/accolade_data.cfg
READY
added accolades for OCE mixed 2v2 tournament no. 1 + other misc.
=> updated accolade data for march 17th

Locales/German_de.json
Fixed some minor spelling mistake as well as some translation errors.
Will continue asap.
=> German Translation Update

Rules/CommonScripts/DefaultVotes.as, Rules/CommonScripts/VoteCommon.as, Rules/CommonScripts/VoteCore.as
**READY**
- Prevent player from voting on a vote they started (admins can still force pass/cancel the vote)
- Prevent player from voting on a vote to kick them
- Prevent player from starting a vote against themselves
- Changed pass percentage back to 50% since the vote starter can't vote
- Changed what's visible in the vote box to reflect these changes
Vote/be voted against using players with different roles (normal, admin, THD team)
=> Voting changes

Rules/CommonScripts/AdminLogic.as
(pick one)
- **READY**
Just fixed the issue with the camera resetting to the center.
=> fixed camera issue

Locales/Portuguese_br.json
Missed a single "o" in a word :sweat_smile:
EDIT: Added translation for the new things that appeared with the F2P update.
EDIT2: New translations for the new emote/assist update and fixed a typo on f2p translation
**READY**: this PR is (to the best of your knowledge) ready to be incorporated into the game.
=> Add new translation on Portuguese_br.json

Entities/Characters/Scripts/RunnerHoverHUD.as, Entities/Common/HoverMessage/DrawHoverMessages.as, Rules/CTF/Scripts/CTF_GiveSpawnItems.as, Rules/CTF/Scripts/CTF_Interface.as, Rules/CommonScripts/KillMessages.as, Rules/CommonScripts/MarkPlayers.as, Rules/CommonScripts/ShowTipOnDeath.as, Rules/CommonScripts/TimeToEnd.as, Rules/CommonScripts/TimersHooks.as, Rules/CommonScripts/VoteCore.as, Rules/Sandbox/Scripts/Sandbox_Interface.as, Rules/TDM/Scripts/TDM_Interface.as, Scripts/Solo/Sandbox.as
**READY**
I went through every HUD element and decided whether they should be visible when HUD is hidden using F6
Resolves #411
Goes with engine-side pull request #​103
Press F6 (requires engine-side changes to properly test)
=> Fixed problems with video recording (F6) mode

Rules/WAR/Scripts/WAR.as, Scripts/Solo/TutorialTTH.as
- **READY**: Working/Ready
Prevents the game from ending if you use the tutorial TTH mode. 
Asu explained here
https://github.com/transhumandesign/kag-base/issues/443
=> Tutorial TTH fix

Entities/Common/Factory/Shop.as, Entities/Industry/Trading/TradingMenu.as, Rules/TDM/Scripts/TDM.as, Rules/TDM/tdm_vars.cfg
**READY**
When a TDM round ends, you are given back half the value of the items you have in your inventory or hand (except regular arrows). This allows people to get a bit of money back on any items they purchased but didn't end up using.
Thanks to @Pine2 for the idea
Finish a TDM round with items in your inventory or hand
=> Held/inventory items give back half their value when TDM round ends

Entities/Common/Scripts/DetectLadder.as
**READY**
As requested by @MrPotatobird and @1bardesign 
https://github.com/transhumandesign/kag-base/pull/542#issuecomment-502415861
Collide and climb ladders like normal
=> Reverted ability to pass through ladders

Rules/CommonScripts/DefaultVotes.as
**READY**
Adds a vote option to scramble the teams if they are unbalanced. Anyone that isn't in spectator can participate in the vote. If the vote passes, the map is restarted with new teams. Currently, the pass percentage is 50% which can be adjusted if needed.
Closes #174
Vote to scramble teams
=> Team scramble vote

Rules/CommonScripts/accolade_data.cfg
(pick one)
i accidentally gave bronze people from https://challonge.com/mxcoucff silver medals
sorry furai ;-;
=> Accolade fix 

Rules/CommonScripts/AdminGUI.as
Somehow most servers and clients dont have issues with this, but TC wont accepted this (on a linux host). 
It shouldn't compile none the less, the changes above fixes it.
=> Compile error fixes

Entities/Industry/Drill/Drill.as
Fixes a drill null error that does happen every so often when playing.
=> Drill null fix

Entities/Vehicles/Common/VehicleConvert.as
- **READY**
This pull request completely reworks how vehicle capture visually looks by making the window semi-transparent, smaller and even smaller on highest zoom level.
Issues:
- Uses hand alignment on line 205.
1. Start capturing any enemy vehicle.
=> Reworked vehicle converting GUI

Rules/CommonScripts/ScoreboardCommon.as, Rules/CommonScripts/ScoreboardRender.as
This displays the map name on the scoreboard
onInit and onRestart is used because sometimes the map names would show up with the file location + map name (e.g. map/ctf/mapnamehere.png)
=> Show's map name in scoreboard

Rules/CommonScripts/KAG.as
**IN DEVELOPMENT**
The join, swap team, map, and change name messages have been moved to script-side to allow for more customization. only difference is the map message is posted earlier than usual.
**Includes engine-side pull request 116**
Unable to test without engine pull request
=> Moved chat event messages from engine

Entities/Items/Log/Log.as, Entities/Items/Log/Log.cfg
(pick one)
fix for this issue https://github.com/transhumandesign/kag-base/issues/616
=> Ferrezinhre logchange 1

Entities/Industry/Drill/Drill.as
Reverted the interp change, will look into the engine side issue soon.
=> Drill interp revert

Rules/CommonScripts/accolade_data.cfg
=> Updated acc

Entities/Industry/CTFShops/Quarters/WakeOnHit.as, Entities/Items/Crate/Crate.as, Entities/Structures/Trampoline/TrampolineLogic.as, Entities/Vehicles/Common/PopWheelsOff.as, Entities/Vehicles/Common/VehicleCommon.as, Rules/CTF/Scripts/CTF.as
Fixes Attachment Points for next update
=> Attachment point changes

Entities/Vehicles/Common/VehicleCommon.as
Part 1
Fixes the mystery null error with vehicles
=> Null error hotfix

Rules/CommonScripts/accolade_data.cfg
=> FG community contributor accolade

Entities/Industry/Tunnel/TunnelTravel.as
Temp work around until engine code is fixed by somebody
Somebody already figured out how to do it in game anyway
=> Tunnel tile glitch work around

Entities/Characters/Knight/KnightLogic.as
Only for knight (as archer/builder doesnt have this issue afaik (let me know if they do))
Knights no longer jab while buying items
Knights no longer jab if the player just switched to it (happens when you change class at an enemy shop)
=> Shop jab prevention

Entities/Characters/Scripts/RunnerKnock.as
Item's that get healed require a player before we play their particle effect
This prevents drill's and what not from having the particles.
=> [Change] OnHeal changes

Entities/Natural/Trees/TreeSync.as
Ever had this happen and complained about it?
This pr fixes it!
Big thanks to Greendino for showing me how to reproduce this, and GoldenGuy for giving me an idea on how to fix the issue.
=> [fix] Tree no longer extends hitboxes of objects

Entities/Common/Building/BlobPlacement.as
**READY**
Resolves #617 
Place ladders on top of other players
=> Ladders can be placed on top of players

Entities/Items/Explosives/Explosion.as
**READY**
They also stun the area around you as water bombs do
Let a water bomb explode in your inventory
=> Water bombs stun instead of kill when they explode in your inventory

Entities/Vehicles/Common/VehicleCommon.as
fixes: https://github.com/transhumandesign/kag-base/issues/582
=> fixed catapult charging anim not getting synced.

Entities/Characters/Scripts/RunnerDeath.as
fixes: https://github.com/transhumandesign/kag-base/issues/209
=> you can no longer put corpses in player inventory.

Rules/CommonScripts/accolade_data.cfg
Should target release date far pessimistically enough
=> Updated accolades timestamp (targets 25-05-2020)

Entities/Characters/Builder/BuilderCommon.as, Entities/Characters/Scripts/RunnerKnock.as, Entities/Common/Building/BlobPlacement.as, Rules/CommonScripts/ChatCommands.as, Rules/CommonScripts/EmoteBinderMenu.as
Max particle cap (25 hearts)
No more flying with hotkey spam
!bot no longer complaining
Emote binder randomly changing
=> [Fix] Test build fixes

Entities/Characters/Builder/CommonBuilderBlocks.as
=> [fix] Small CTF fix

Rules/CommonScripts/MapVotesCommon.as, Rules/CommonScripts/PostGameMapVotes.as
See commits. It now still allows players to have fun blowing up towers post-game, has syncing bugs fixed, and it now shows the map ceilings (requested by bunnie).
=> Map voting fixes and rework

Rules/CommonScripts/MapVotesCommon.as, Rules/CommonScripts/PostGameMapVotes.as
=> Minor fix and cleanup for map votes

Entities/Characters/Builder/BuilderCommon.as, Entities/Common/Building/BlobPlacement.as
Hopefully should prevent it, blob gets made in a different location, disabled, then teleported back to client
=> [fix] Flying bug fix 2.0

Rules/CommonScripts/MapVotesCommon.as, Rules/CommonScripts/PostGameMapVotes.as
Hopefully final patches. Looks like this in small CTF: ![smallctf](https://cdn.discordapp.com/attachments/337265406001807360/712652786256445450/unknown.png)
=> Map vote refactors, fixes and frame appearance change

Entities/Characters/Builder/BuilderCommon.as
Hopefully the last time its needed :dagger:
=> [fix] Beta shop fix

Entities/Characters/Builder/BuilderInventory.as
=> [fix] Infinite blob building

Entities/Structures/Common/FallOnNoSupport.as
Title, removed hacky work around that was left in by accident, engine update fixes the bug that this tried to work around on. #blamevamist
=> [fix] Removed accidental work around

Rules/CommonScripts/accolade_data.cfg
**READY**: this PR is (to the best of your knowledge) ready to be incorporated into the game.
Adds new admins' accolades in scoreboard.
=> add new admins' accolades

Rules/CommonScripts/ScoreboardRender.as
Idea suggested by dino in development chat
Right clicking a user on scoreboard will copy their name, along with a small 'Username copied: username' animation as shown here:
https://cdn.discordapp.com/attachments/601801785623052301/714836880633364561/Sjso9bcCgy.mp4
=> [Added] Copy username upon right clicking a name

Entities/Characters/Scripts/RunnerDrowning.as
=> [Fix] Only plays gasping once 

Entities/Common/GUI/WheelMenuCommon.as
Entry rendering of pickup wheel seem to have wrong offset. 
Also reduced radius of wheel. The original radius felt too big. Please review.
=> Minor fixes to pickup-wheel rendering

Entities/Items/Explosives/Bomb.as
Title. Bombs only collide with enemy shields now
=> Bombs dont collide with shielding enemy knights if they're shielding away from the bomb

Entities/Common/Scripts/SetDamageToCarrier.as, Entities/Items/Explosives/Keg.as, Entities/Items/Explosives/Keg.cfg
Resolves https://github.com/transhumandesign/kag-base/issues/835
=> Lock keg ownership for 2 seconds before explosion

Entities/Common/Emotes/EmoteBubble.as, Entities/Common/Emotes/EmotesCommon.as
Resolves #873 
1. Emote
2. Hover over the emote with your cursor
=> Emote bubbles become hidden while hovering over them

Entities/Natural/Animals/Scripts/LandAnimal.as
The slight upwards force applied while walking was being applied independently for left and right keys.
This addresses one of the suggestions in #872
1. Tame a bison using a burger
2. Ride the bison
3. Hold down, left and right to superjump
=> Fixed bison superjump

Rules/CommonScripts/RegrowPlants.as
Stuff now grows on damaged dirt, grain and flowers can also grows under same conditions as bushes, bushes/flowers/grain can grow in grass now
=> Plants regrowth update

Rules/CommonScripts/RegrowPlants.as
Title. Also increased size of random_time, min_random_time and max_random_inc to u16
=> Divide by 0 fix in RegrowPlants.as

Rules/CommonScripts/RegrowPlants.as
Added checks for if tile indexes or tile array sizes are 0
=> Hopefully fixed OnSetTile error in RegrowPlants.as

GUI/guiMain.xml
=> update finish account linking button

Entities/Common/Building/BlobPlacement.as, Entities/Common/Building/BlockPlacement.as, Entities/Common/Building/PlacementCommon.as
Server will now do some checks before allowing you to place a tile down.
These include
- Range check (compensates for lag)
- Delay check (^)
- Don't allow user to place on dirt/bedrock
- Don't allow users to place tiles at tiles with no support
=> [Change] Server now checks placeBlob and placeBlock

Entities/Structures/Door/SwingDoor.as
Stops cases like this
https://cdn.discordapp.com/attachments/337266863841214465/787441804479299614/cringemiun.mp4
Old vs new
https://files.vamist.dev/Tq8df.webm
=> [Change] Doors will open if placed on top of team player, vehicle or migrant

Rules/CommonScripts/RegrowPlants.as
- flowers should now spawn
- dont check moss_stone more times than it is needed (1)
- growth checks should no longer happen immediately one after another 
- grass luck now works for all types of grass
=> Minor fixes for RegrowPlants

Rules/CommonScripts/AdminLogic.as, Rules/CommonScripts/Report.as
=> correction of a english spelling error in a function name

Scripts/Solo/AutoRebuild.as, Scripts/Solo/AutoRebuild.cfg, Scripts/localhost.as
Auto rebuild script as title says
Needs engine side PR merged for this to compile and work.
Script gets added via AddScript by localhost.as (which is called when using localhost.bat)
~~This can cause minor stutters, but we modders can disable/change how often its called, and we can work out how to improve it engine side later on.~~ read below
=> [Addition] Auto rebuild script

Entities/Industry/Saw/Saw.as
Title. Done so sawjumps cost a saw for every attempt
=> Saw breaks if it explodes too many bombs at once

Entities/Characters/Knight/KnightLogic.as
=> [Fix] Knights no longer do less damage to players when also hitting logs

Rules/TDM/gamemode.cfg
Title, not needed in a short round based gamemode
=> [Change] Removed RegrowPlants from tdm

Entities/Common/Decaying/DecayQuantity.as, Rules/CommonScripts/ChatCommands.as, Rules/Sandbox/Scripts/Sandbox_Rules.as
- ``!crate blacklisted`` item will no longer spawn said blacklisted item
- Shops will no longer spawn into the ground 
- Mats will decay extremely quickly
=> [Change] Sandbox changes 

Entities/Items/Crate/Crate.as
=> [Fix] Crates no longer slide through doors

Rules/CTF/Scripts/CTF_Trading.as
- stone blocks now give 3 coins
- stone doors now give 5 coins
- ladders now give 1 coin
=> Builder coin gain change

Entities/Characters/Archer/ArcherLogic.as, Rules/CommonScripts/Holiday/Christmas/Christmas.as
Snow now works with staging build
Archer grapple pickup bug is now fixed
=> Fixes and changed based on testing build

Entities/Common/Controls/StandardPickup.as
- **READY**
[Before](https://user-images.githubusercontent.com/26771587/102967391-1fba2780-44f2-11eb-9694-1fc39c2baeff.mp4)
[After](https://user-images.githubusercontent.com/26771587/102967402-25177200-44f2-11eb-9bda-c8efcfb7a13d.mp4)
This fix has been on captains for >6 months. It's a nice quality of life thing.
=> Fixed pressing c to deselect ladders as builder not picking up items.

Entities/Items/Sponge/Sponge.as
- **READY**
[Bug](https://user-images.githubusercontent.com/26771587/102972153-e803ad80-44fa-11eb-8ef6-20f6d2919eea.mp4)
[Fix](https://user-images.githubusercontent.com/26771587/102972160-eafe9e00-44fa-11eb-8c01-ed2af814f3ef.mp4)
=> Fixed sponges drying water tiles when they are in your inventory.

Rules/CommonScripts/Holiday/Christmas/Christmas.as
:flushed: 
(fixes issues with presents not spawning correctly)
=> [Fix] Thank you arthur for the presents

Rules/CTF/Scripts/CTF.as
150 instead of 10, everyone gets to buy a keg
=> Give more coins to winning team in CTF

Entities/Characters/Archer/ArcherCommon.as, Entities/Characters/Archer/ArcherLogic.as, Entities/Characters/Knight/KnightCommon.as, Entities/Characters/Knight/KnightLogic.as, Entities/Common/Controls/StandardControls.as
Pretty much builder binds but for archer and knight.
1. Collect different types of bombs as knight or arrows as archer
2. Press shift + num key that corresponds to the bomb/arrow you want to switch to
=> Shift + num key to switch bomb/arrow type

Rules/TDM/Scripts/TDM_Trading.as
Resolves #882 
I didn't swap the burger with the regular arrows so the regular arrows stay grouped with the other arrows.
=> Moved burger higher in the trader shop menu

Entities/Common/Help/DrawHelp.as, Entities/Special/WAR/WAR_base/WAR_base.as, Rules/CommonScripts/MapVotesCommon.as
Only tested this by launching the game to check that there are no errors.
=> Added missing translation support for some displayed text

Entities/Common/Movement/CheapFakeRolling.as, Entities/Common/Movement/FakeRolling.as, Entities/Common/Scripts/DecayStuckArrows.as, Entities/Items/Projectiles/Arrow.as
Implements everything stated in [this comment](https://github.com/transhumandesign/kag-base/issues/466#issuecomment-642981350)
Resolves #466 
1. Be archer
2. Spawn any blob
3. Change to a different team
4. Shoot the blob with an arrow
5. Wait 30 seconds for the arrow to decay (or manually reduce the decay time)
=> Arrows stay stuck in blobs

readme.txt, server_setup_info.txt
Actual information for this files here.
Fixes #95
=> [update] readme and server_setup_info files

Entities/Items/Sponge/Sponge.as
I don't actually know if this is was an issue. I was made aware of it from [this](https://github.com/transhumandesign/kag-base/pull/923#discussion_r547312406) comment.
Put a wet sponge next to a lit fireplace to dry.
=> Fixed potential issues caused by global variable in Sponge.as

Entities/Characters/Knight/KnightAnim.as
Title, there was a huge segment of code that could be sped up with a simple switch case.
Helps when there's a lot of knights on screen.
=> [Change] Moved some knight anim code to switch case

Entities/Items/Explosives/Mine/Mine.as, Entities/Items/Explosives/Mine/Mine.cfg
The highlight is identical to items being picked up (without the label). I would like feedback/suggestions on better ways to visualise this, if any. I just went with a basic and straightforward way.
Resolves #825 
1. Buy a mine
2. Drop the mine
3. Hover your mouse over the mine
=> Hover over primed mine to check if its my mine

Entities/Common/Includes/Costs.as, Entities/Industry/Building/Building.as, Entities/Industry/CTFShops/BoatShop/BoatShop.as, Entities/Industry/CTFShops/CTFCosts.cfg, Entities/Vehicles/Boats/WarBoat/WarBoat.cfg
- **HOLD**: you are aware of some serious issues with your PR. It should not be merged and you will follow up when they are fixed.
Resolves #573 
Build a boat shop
=> Removed gold cost from boat shop

Entities/Common/Includes/Costs.as, Entities/Industry/CTFShops/CTFCosts.cfg, Entities/Industry/CTFShops/VehicleShop/VehicleShop.as, Entities/Vehicles/Ballista/Ballista.as, Entities/Vehicles/Ballista/Ballista.cfg
I suggest this receives more feedback before merging since the issue this resolves only has 2 upvotes.
Resolves #840 
1. Buy ballista
2. Destroy ballista
=> Ballistae cost 50 gold and drop 50 gold upon death

Entities/Vehicles/Boats/WarBoat/WarBoat.as
=> Added missed lines from previous pull request

Entities/Characters/Builder/BuilderLogic.as, Entities/Common/Building/PlacementCommon.as
Fixes #593.
Caused by inconsistency between placing and destroying tiles as builder
=> [fixed] destroying backwall tiles at top of map

Rules/CommonScripts/Accolades.as, Rules/CommonScripts/accolade_data.cfg
=> Added -1 as a valid option for accolades

Entities/Common/Building/GoldBuilding.as, Entities/Industry/CTFShops/VehicleShop/VehicleShop.as, Entities/Items/Crate/Crate.as, Entities/Items/Crate/Crate.cfg
Ballista crates drop gold if they are destroyed before they get unpacked (for example, if they fall into a saw)
=> Ballista crates drop gold

Entities/Natural/Trees/BushyTreeLogic.as, Entities/Natural/Trees/PineTreeLogic.as
=> minimap trees no longer visible on the side of the minimap when outside of the current view

Rules/CommonScripts/PatronSupport.as, Rules/CommonScripts/SwitchFromSpec.as
Patreons can now switch teams correctly with spec slot changes
=> [fix] patreon joining

Entities/Common/Attacks/FleshHitEffects.as
(pick one)
A few sentences describing the overall goals of the pull request's commits.
title
no
=> FleshHitEffects no longer client only so that onHit doesnt bug out in RedFlash

Entities/Industry/CTFShops/BoatShop/BoatShop.cfg
=> boat shop no longer drops gold

Rules/CommonScripts/accolade_data.cfg
I am an OKSA so should have moderation accolade.
I've had 2 PRs merged so should have github accolade:
https://github.com/transhumandesign/kag-base/pulls?q=is%3Apr+author%3Abenjamingorman+is%3Aclosed
=> Update accolades for Eluded

Entities/Characters/Builder/CommonBuilderBlocks.as, Rules/CommonScripts/accolade_data.cfg
NoNamedNN github accolade - "Fix magazine requirements" pull request
=> NonamedNN accolade github contribution

Entities/Items/Containers/Present/Present.cfg, Rules/CommonScripts/Holiday/Christmas/Christmas.as
(pick one)
hoho plays 6 times cus bunnie is dum dum
=> make it play hohoho on christmas even if no trees

Entities/Characters/Archer/ArcherHUD.as, Entities/Characters/Knight/KnightHUD.as
- **READY**
Fixes null errors when knights or archer blobs die
Die as an archer or knight, this is the bug where class changing could sometimes cause the null errors
=> Null HUD fix

Rules/CTF/mapcycle.cfg
wrong mapcycle entry was crashing the server
=> [fix] mapcycle crash

Scripts/MapLoaders/BasePNGLoader.as, Scripts/MapLoaders/GenerateFromKAGGen.as
In my opinion, backgrounds are scrolling too fast, especially the one farthest from the player.
Also it is odd that they don't scroll vertically.
So I made this PR which makes backgrounds to scroll slower and to scroll vertically slightly.
Before - https://imgur.com/a/KcEeAm7
After - https://imgur.com/a/sZchnZb
=> Improved Background scrolling

Entities/Characters/Builder/BuilderLogic.as, Entities/Common/Building/BlobPlacement.as, Entities/Common/Building/BlockPlacement.as, Entities/Common/Building/PlacementCommon.as, Rules/CTF/Scripts/CTF.as
(pick one)
[added] building during build time is now almost 2 times faster (build delay: 7 > 4)
[fix] fixed bug when you could accidentally damage backwall behind a door when lagging or building fast
=> [CTF Rebuild] Faster building in build time

Locales/Russian_ru.json
(pick one)
- **HOLD**: you are aware of some serious issues with your PR. It should not be merged and you will follow up when they are fixed.
A few sentences describing the overall goals of the pull request's commits.
Outline the steps to test or reproduce the PR here.
If you added new features and want to explain how to use them, do so here.
- git branch used
- gamemode if relevant
- specific objects or behaviours affected
=> Locale fix

Rules/CommonScripts/DefaultVotes.as, Rules/CommonScripts/VoteCommon.as
Players with ~ in their username cannot start votes or contribute to existing votes. I also moved the "Voting for surrender is not available as a spectator" reason above most other reasons for not being able to vote.
Resolves #655
1. Join a server with two clients with the same username
2. Attempt to vote with the client who joined last
=> Players playing on duplicate instances of KAG cannot vote

Entities/Items/Projectiles/Arrow.as
(pick one)
[changed] fire arrows can now light team kegs
=> [CTF Rebuild] Fire arrows now light team kegs as well

Rules/CommonScripts/accolade_data.cfg
=> laws65 accolade github contribution

Entities/Common/Factory/Shop.as, Rules/CommonScripts/Holiday/Holiday.as
- Holiday.as checks against a script list
- Shop.as checks that the item requested is apart of its shop list
This is a quick fix, better solutions do exist, but we just want things to work for now.
=> [Fix] Small sanitization checks 

Entities/Industry/Building/Building.as
(pick one)
[removed] removed quarry
=> [CTF Rebuild] Quarry removed

Entities/Characters/Archer/ArcherAnim.as, Entities/Characters/Builder/BuilderAnim.as, Entities/Characters/Knight/KnightAnim.as, Entities/Characters/MovementScripts/RunnerMovementInit.as, Entities/Vehicles/Boats/Dinghy.as
(pick one)
[change] you now move faster in water
[change] dinghies move faster in water
=> [CTF Rebuild] Faster water movement

Entities/Common/Controls/StandardControls.as, Entities/Common/Controls/StandardControlsCommon.as
Resolves #1042
1. Run and join a dedicated server
2. Run [clumsy](https://jagt.github.io/clumsy/) with 200ms lag
3. Be knight/archer (to test bomb/arrow cycling)
4. Pickup an item and tap the inventory key in quick succession
5. Notice how you don't need to wait for items to visibly be in your hand to put them in your inventory
6. Tap inventory key while not holding anything to check that cycling still works
=> Improved putting held items in your inventory with bad ping

Entities/Vehicles/Boats/Dinghy.cfg
Using the standard setup for the dinghy glitch, it seems impossible to reproduce now since the shape is not as constrained.
=> Fixed(?) the dinghy yeet glitch

Entities/Characters/Archer/ArcherHUD.as, Entities/Characters/Builder/BuilderHUD.as, Entities/Characters/Knight/KnightHUD.as
Fixes #1391 
1. Set `cl_mouse_scale` to e.g. 3, 4, 5, 6
2. Aim with any of the classes
Before the PR, aiming is significantly off. With the PR, aiming is back to normal.
=> Non-default `cl_mouse_scale` cursor offset was incorrect

Rules/CTF/gamemode.cfg, Rules/CommonScripts/RebuildVote.as
- **HOLD**: need to talk to verra to setup the poll so that the poll opens at set day && put in the proper link once its done
=> rebuild poll popup at server join

Entities/Common/HoverMessage/DrawHoverMessages.as
my little sussy baka used a cplayer prop
=> fixed coin hover message spam

Entities/Vehicles/Ballista/Ballista.cfg
=> ballista no longer drops gold

Entities/Characters/Builder/BuilderLogic.as, Entities/Characters/Knight/KnightLogic.as
=> fix doors not being slashed with raycast slashes

Entities/Items/Explosives/WaterBomb.cfg
some troll pr changed it for no reason so im changing it back because it broke hadoukens
=> fix hadoukens

Entities/Structures/Door/CollapseMissingAdjacent.as
oversight related to tickfrequency
=> fix doors not getting extra damage when they should sometimes

Entities/Common/Attacks/KnockBack.as
=> [dev] fix friendly water knockback

Rules/CommonScripts/Holiday/Halloween/Halloween.as
=> [modified] halloween brightness 0.85 instead of 0.9

Entities/Industry/Saw/Saw.as
forgive me father for i have sinned and will sin again
=> [dev] water bombnado hack fix

Rules/SmallCTF/mapcycle.cfg
it was broken
- **READY**: this PR is
=> [dev] smallctf mapcycel fix

Rules/CTF/Scripts/CTF_GiveSpawnItems.as
outposts are the spawn point now so theyre the one which should give resupplies
=> [dev] fixed ballistas giving respplies

Entities/Common/Controls/StandardControls.as
=> added missing null checks

Entities/Items/Crate/Crate.as
the code for unpacking was a bit weird previously
now it just spawns the blob in the center of the white rectangle you see when unpacking
=> [fixed] outpost in ground

Entities/Characters/Knight/KnightLogic.as
=> [fixed] slashing through team doors

Entities/Common/Building/BlobPlacement.as, Entities/Common/Building/PlacementCommon.as
=> fix bad repair blob code

Entities/Common/Building/BlobPlacement.as, Entities/Common/Building/PlacementCommon.as
removed code regarding ladder repairing because it didnt even really work
=> more repairing fixes

Rules/CommonScripts/SpectatorQueue.as
=> [fixed] queue syncing

Rules/CommonScripts/RebuildVote.as
=> removed print

Rules/CommonScripts/VoteCore.as
=> show which option u selected in vote

Entities/Characters/Princess/PrincessBrain.as
Very low-effort fix for the princess not making kissing sounds on a dedicated server. However, it doesn't show the kiss animation with the heart since the princess' brain is not available on the client where animations are handled. It's not worth my time to look into this further.
Fixes #1397
1. Be on a dedicated server
2. Run past a princess
3. Hear a kiss sound
=> Fix princess not kissing on dedicated server

Entities/Characters/MovementScripts/RunnerMovement.as, Entities/Characters/Scripts/RunnerCollision.as
Resolves #1117
Crouch through crates exactly like with team platforms.
=> Add ability to crouch through crates

Entities/Industry/CTFShops/KnightShop/KnightShop.as
Fixes #1454.
Before this PR - https://imgur.com/y7Cm3It.png
After this PR - https://imgur.com/7QOnBsE.png
=> [changed] Make Keg in shop team-colored

Entities/Common/Scripts/AlertAdminOnDie.as, Entities/Natural/Seed/Seed.as, Entities/Natural/Seed/Seed.cfg, Entities/Natural/Trees/BushyTree.cfg, Entities/Natural/Trees/PineTree.cfg
- **READY**
it checked for tree blob rather than seed blobs previously
=> fix seed death message

Entities/Common/Controls/StandardPickup.as, Entities/Common/Factory/Production.as, Entities/Common/Scripts/AlertAdminOnDie.as, Entities/Industry/Factory/Factory.as, Entities/Items/Crate/Crate.as, Entities/Items/Crate/MakeCrate.as, Entities/Items/Powerups/Powerup.as, Entities/Vehicles/Common/VehicleAttachment.as, Entities/Vehicles/Common/VehicleCommon.as, Rules/WAR/Scripts/WAR_PickSpawn.as
Search for all occurrences of `.getInventoryName()` and made sure they all have translation support. If it was commented out, I just deleted the unused code.
Add translations for the text updated.
=> Add missing translation support

Entities/Common/Building/BlobPlacement.as
- **READY**
Closes #1533 and resolves #1514.
An alternative method.
1) Go on localhost or dedicated server.
2) Build blobs until you see "missing requirements".
3) Grab a seed out of your inventory.
4) Attempt to place the seed. Without the applied fix, it will be not be possible.
Credit given to Hobey
=> [fixed] Seed placement using requirements

Entities/Industry/Fireplace/Fireplace.as, Entities/Industry/Fireplace/FireplaceCommon.as, Entities/Items/Projectiles/Arrow.as
This fixes [issue #1242](https://github.com/transhumandesign/kag-base/issues/1242) and [issue #1206](https://github.com/transhumandesign/kag-base/issues/1206).
Fireplace that has been there from the start - such as the ones in Save the Princess' first map - will now be able to be extinguished by water bomb and water arrow. It was not possible before because with those two (water arrow and water bomb) the game assumed hitter was "water_stun" rather than "water" but fireplace only checked for "water" in onHit().
Fireplace can now be set on fire when shooting fire arrow through them. 
This was done by checking in onCollision() if a blob with fire source is colliding with fireplace.
It works well …
=> Fireplace that has been there from the start can be extinguished, Fireplace can be set on fire with fire arrow

Entities/Vehicles/Boats/LongBoat.as, Entities/Vehicles/Boats/LongBoat.cfg, Entities/Vehicles/Boats/WarBoat/WarBoat.as, Entities/Vehicles/Boats/WarBoat/WarBoat.cfg
- **READY**
Resolves #1573 
* It should be noted that this PR also stops longboats from decaying when left alone (bug?).
=> [boat rebuild] [fixed] Longboat & Warboat shape offset

Entities/Items/Food/MakeFood.as
Fixes #1383.
Throwing grain, egg, steak, fishy etc. at fireplace will now play a `SparkleShort.ogg` sound when playing online.
The blob can only be created server-side, so trying to play a sound based on that blob will not play the sound on the client-side when playing online.
So the sound is now played from the ingredient blob instead.
Go to online Sandbox, throw egg at a fireplace.
Notice it makes a sound now.
=> [fixed] Fireplace now properly plays SparkleShort.ogg when cooking, while playing online

Entities/Industry/CTFShops/BoatShop/BoatShop.as, Entities/Industry/CTFShops/CTFCosts.cfg, Entities/Items/Crate/Crate.as
- **READY**
The war-boat doesn't cost gold to make.
Some relevant information can be viewed at #1404
=> [boat rebuild] Warboat has no gold cost

Rules/CommonScripts/accolade_data.cfg
Updated accolades with most of the UKC tournaments.
The most recent ones might be missing; will be added in the future (need Sham to give me player lists)
Links to brackets & lists of players in individual commits.
(UKC 4, 5 and 6 did not happen/finish)
=> Accolades update - UKC tournaments

Rules/CommonScripts/accolade_data.cfg
(pick one)
added map and community contributor accolades for myself (NoahTheLegend), for updating SmallCTF mapcycle and different mods
* Note about community badge:
Revived and refreshed old Blavier's mod "Armored Warfare" (which is well known and populated for ~8 months), currently hosted by GoldenGuy
Keeping the work on Territory Control mod with spriting help of PURPLExeno (XenoTM) and TheCustomerMan (Skemonde) - currently hosting it
Created own version of Cats & Mice (old classic mod) which had 20 players on peak, although died in a few weeks
Created Knight Parkour mod (which i'm hosting periodically)
Slightly updated, was hosting Shiprekt
Added new class, spells, fixed bugs for Wizard …
=> Added accolades

Entities/Meta/CTFMusic.as, Entities/Special/CTF/CTF_Flag.as, Entities/Special/CTF/CTF_FlagCommon.as, Entities/Special/CTF/FlagBase.as, Entities/Special/CTF/FlagBase.cfg
- **READY**
This PR includes #1325 and will close it. Resolves #1319, resolves #1604
Test as instructed in mentioned issues above.
=> [dev] Simplified CTF flag scripts

Entities/Industry/Saw/Saw.as
- **READY**
Resolves #1378 & Closes #1395 
The difference between this PR and #1395 is that the saws will also synchronize the saw blade's bloody state. Sync is also done on init instead of every tick.
1) Go onto a dedicated server.
2) Create a saw, jump in it to make it bloody, then turn it off.
3) Disconnect and then rejoin the server. With the applied fix, the saw should look exactly the same as before.
=> [fixed] incorrect saw sprite on join

Rules/CTF/Scripts/CTF_PickSpawn.as
- **READY**
* Current Behavior: The menu only gives the respawn options that were available when the player died.
* Proposed Behavior: The respawn menu updates in real time while the player is waiting to respawn.
https://user-images.githubusercontent.com/68350259/218045089-6b213666-5149-4f65-b379-4c72193b20a5.mp4
=> [modified] Respawn menu options in real time

Entities/Industry/Tunnel/TunnelTravel.as
Supersedes #1348 with the same functionality (credit to mugg91) with the other saw fixes reverted for the reasons outlined in the review.
=> Teleport players to center-bottom of tunnels when traveling

Entities/Structures/MountedBow/MountedBow.as, Entities/Vehicles/Airships/Airship.as, Entities/Vehicles/Airships/Bomber.as, Entities/Vehicles/Airships/Bomber.cfg, Entities/Vehicles/Ballista/Ballista.as, Entities/Vehicles/Ballista/Ballista.cfg, Entities/Vehicles/Boats/Dinghy.as, Entities/Vehicles/Boats/Dinghy.cfg, Entities/Vehicles/Boats/LongBoat.as, Entities/Vehicles/Boats/WarBoat/WarBoat.as, Entities/Vehicles/Catapult/Catapult.as, Entities/Vehicles/Catapult/Catapult.cfg, Entities/Vehicles/Common/PopWheelsOff.as, Entities/Vehicles/Common/Seats.as, Entities/Vehicles/Common/SeatsCommon.as, Entities/Vehicles/Common/SeatsGUI.as, Entities/Vehicles/Common/Vehicle.as, Entities/Vehicles/Common/VehicleCommon.as, Entities/Vehicles/Common/VehicleGUI.as
- **READY**
Vehicle scripts are simplified. Some other improvements were added along the way.
* [fixed] desync where firing sounds wouldn't play.
* [fixed] certain vehicle sprites not showing their correct damage frame.
* [fixed] boats not colliding with platforms.
* [changed] pop off wheels button doesn't appear when the vehicle is attached.
All vehicles' functionality should be tested thoroughly.
Modders pay attention! Assuming this PR is merged, some mods may go out of date. Updating your mod may be neccessary if it modifies vehicle scripts or uses vehicle scripts. It is recommended to update because of bug fixes included.
**How to update:**
The functions ``Vehicle_onFire`` and ``Vehicle_canFire`` are deprecated. They have been moved into each vehicles class. You can view the …
=> [boat rebuild] Vehicle scripts cleanup

Entities/Vehicles/Catapult/Catapult.as
title
cook !egg, !grain, !fishy in fireplace
u can now see new icons when loading to cata
=> [added] support for cooked food icons for loading to catapult

Entities/Materials/Construction/MaterialGold.as
title
put gold on ground in sandbox
=> [modified] remove void warning from gold in sandbox

Entities/Industry/Hall/Hall.as, Rules/CommonScripts/CinematicCommon.as
Fixes the ``capture ticks`` and ``capture time`` type mismatch.
=> [fixed] Type mismatch console spam

Rules/CommonScripts/ChatCommandCommon.as, Rules/CommonScripts/ChatCommandManager.as
(pick one)
PR name explains it
Use / for commands now instead of !
=> Change chat command prefix from ! to /

Entities/Special/CTF/CTF_Flag.as
Fixes an issue where teammates could pickup their team's flag.
=> [fixed] Improper flag pickup

Entities/Common/GUI/ActorHUDStartPos.as, Rules/CTF/Scripts/CTF_Common.as, Rules/CTF/Scripts/CTF_GiveSpawnItems.as
ActorHUDStartPos.as included CTF_GiveSpawnItems.as which had hooks in it, which is very bad
moved the stuff that both files need to a new file called CTF_Common.as instead
=> [dev] move some resupply stuff to a common file - fix for mod-breaking issue

Rules/CommonScripts/accolade_data.cfg
For making tigorsun_quarry TDM map that was added this update.
=> Add mapping accolade for tigorsun.

Entities/Vehicles/Ballista/Ballista.as, Entities/Vehicles/Catapult/Catapult.as
catapult
[fixed] divide by zero error.
[fixed] players not gaining velocity when thrown.
[fixed] incorrect button icons.
ballista
[fixed] the ballista arm facing an incorrect direction after being unpacked.
Catapult should now be fully functional. Tested in dedicated host with multiple instances to make sure 100%
=> [dev] Catapult hotfixes

Rules/CommonScripts/ChatCommandCommon.as, Rules/CommonScripts/ChatCommandManager.as, Rules/CommonScripts/ChatCommands/MiscCommands.as, Rules/CommonScripts/KickAFK.as
The chat command prefix is defined in a single function that is referenced where needed. This contrasts the current approach of hardcoding the prefix throughout the codebase.
Use chat command and verify all mentions of commands are prefixed correctly.
=> Clean up chat command prefix code

Rules/CommonScripts/MapVotesCommon.as, Rules/CommonScripts/PostGameMapVotes.as
Title, essentially. The code should be easy to modify should someone want to set fewer or more maps, or to add back the random button (although this code path is now untested).
Closes #993
Test localhost mode, test multiplayer and try as many edge cases as possible.
=> Refactor map code and make it 3 options

Entities/Characters/Archer/ArcherLogic.as, Rules/CommonScripts/RedBarrier.as, Rules/CommonScripts/RedBarrierCommon.as
Resolves #1679
- Try grappling around the middle of the map in TDM
- Same in CTF while the match is going
- Try grappling the red barrier in CTF
=> Fixed grapple going through red barrier

Rules/CTF/Scripts/CTF_Interface.as
=> Fixed incorrect respawn timer in warmup

Rules/CTF/Scripts/CTF.as, Rules/CommonScripts/PostGameMapVotes.as, Rules/WAR/Scripts/WAR.as, Scripts/Solo/TutorialCTF.as, Scripts/Solo/TutorialTTH.as
=> Fixed TTH/CTF solo tutorials incorrectly showed map votes

Entities/Natural/Animals/Chicken/Egg.as
Egg.as
"hatch" - was server->server and server->client, is now server->client only
=> Cmd sanitization egg

Entities/Vehicles/Common/SinkOnLowHealth.as
SinkOnLowHealth.as
"start sinking" - was server->server and server->client. server->server is outside of command now, is now server->client, renamed to "start sinking client"
=> Cmd sanitization sinkonlowhealth

Entities/Industry/Fireplace/Fireplace.as
Fireplace.as
"extinguish" - is not used, removed
=> Cmd sanitization fireplace

Entities/Special/CTF/CTF_Flag.as, Entities/Special/CTF/FlagBase.as
CTF_Flag.as, FlagBase.as
"pickup", "capture", "return" - all were server->client. added isClient() check and changed the names of the commands (added " client"). this PR actually does nothing at all.
=> Cmd sanitization flag

Rules/CommonScripts/MapVotesCommon.as, Rules/CommonScripts/PostGameMapVotes.as
PostGameMapVotes.as
No sanitization needed (probably?), moved isClient() and isServer() around to be consistent with other commands.
=> Cmd sanitization postgamemapvotes

Rules/CommonScripts/BuilderBinderMenu.as, Rules/CommonScripts/EmoteBinderMenu.as
BuilderBinderMenu.as, EmoteBinderMenu.as
"builder binder command", "emote command" - were client->client cgridmenu commands. changed to func callbacks
needs #224 Crimson to work
=> Cmd sanitization bindings

Entities/Vehicles/Common/PopWheelsOff.as
PopWheelsOff.as
"pop_wheels" - was client->server->client. is now client->server only. added some checks server-side. uses getActiveCommandPlayer(). Added "pop_wheels_client" server->client command
=> Cmd sanitization popwheelsoff

Rules/CTF/Scripts/CTF.as, Rules/CTF/Scripts/CTF_PickSpawn.as, Rules/CTF/Scripts/CTF_PopulateSpawnList.as
CTF_PickSpawn.as
"pick default" - unused, removed
"pick spawn" - was cgridmenu client->client, is now func callback, needs #224 Crimson to work 
Also idiotic inclusion of hallcommon, removed
=> Cmd sanitization ctf spawns

Entities/Characters/Knight/KnightLogic.as
KnightLogic.as
"pick bomb" - was cgridmenu client->server->client, is now cgridmenu callback that sends client->server command
=> Cmd sanitization bomb pick

Entities/Characters/Archer/ArcherLogic.as
ArcherLogic.as
"pick arrow" - was cgridmenu client->server->client, is now cgridmenu callback that sends client->server command
=> Cmd sanitization arrow pick

Entities/Industry/Trading/TradingMenu.as
TradingMenu.as
"stock" - removed, changed to cbutton func callback
"reload menu" - unused, removed
"buy" - was client->server->client and also client->client. client->client changed to func callback, client->server still exists and uses getActiveCommandPlayer(), server->client is the "play sound" command.
=> Cmd sanitization tradingmenu

Entities/Items/Containers/Chest/Chest.as, Entities/Items/Containers/Present/Present.as
Chest.as
"activate" - was client->server->client, is now client->server, uses getActiveCommandPlayer(), added range check. added "activate client" command which runs the client code.
Present.as
"activate" - was client->server->client, is now client->server, uses getActiveCommandPlayer(), added range check. added "activate client" command which runs the client code.
=> Cmd sanitization containers

Entities/Items/Bucket/Bucket.as
Bucket.as
"splash" - was client->server->client and server->server and server->client. is now server->client only.
"fill" - was server->server and server->client, is now server->client
=> Cmd sanitization bucket

Rules/CommonScripts/Holiday/Christmas/Christmas.as, Rules/CommonScripts/Holiday/Halloween/Halloween.as, Rules/CommonScripts/Holiday/Holiday.as
- 
Christmas.as
"xmas sound" - server->client, still is server->client.
Halloween.as
"necrolaugh" - was server->client, still is server-client. changed spaces to tabs for indentation tho
Holiday.as
"sync_holiday" - was server->server + server->client, is now server->client only, server-side code runs outside of command.
=> Cmd sanitization holidays

Rules/CommonScripts/DefaultVotes.as
=> More vote fixes

Entities/Industry/Saw/Saw.as
Saw.as
"sawteammate_id" - was server->server and server->client (blending teammate). replaced with "sawteammate_id_client", which is a server->client command that just plays the sound and makes gibs. server->server code moved outside of command
"toggle_id" - was server->server and server->client (blending teammate) and client->server (turn off button). is now client->server, uses getActiveCommandPlayer(), added range and team check, server->server code moved outside of command
"toggle_id_client" - new server->client, syncs saw state
=> Cmd sanitization saw

Entities/Items/Food/EatCommon.as, Entities/Items/Food/Eatable.as
Eatable.as, EatCommon.as
"heal command" - was server->server and server->client, so moved the server-side code in it outside of the command. added "heal command client" which just plays the sound.
=> Cmd sanitization heal

Entities/Characters/Archer/ArcherCommon.as, Entities/Characters/Archer/ArcherLogic.as
ArcherLogic.as && ArcherCommon.as:
"shoot arrow" - was client->server, removed, is serverside code now. added "play fire sound" command that just plays a sound
"grapple sync" - Instead of the client telling the server what they're grappling, the code for grappling is run server-side and client-side at once now. The server then syncs the server-side grapple to the client. I think.
"pickup arrow" - was client->server->client, is now client->server. Added client-side "pickup arrow client", which just plays the sound.
=> Cmd sanitization archerlogic

Entities/Characters/Builder/BuilderLogic.as
Changed some client-side logic to not rely on sprite anymore
Only command that remains is "pickaxe", changed and sanitized it a bit
Players should feel no difference
=> Cmd sanitization builderlogic

Entities/Characters/Builder/BuilderCommon.as, Entities/Common/Factory/Shop.as, Entities/Common/Factory/ShopCommon.as, Entities/Industry/Building/Building.as, Entities/Industry/CTFShops/ArcherShop/ArcherShop.as, Entities/Industry/CTFShops/BoatShop/BoatShop.as, Entities/Industry/CTFShops/BuilderShop/BuilderShop.as, Entities/Industry/CTFShops/KnightShop/KnightShop.as, Entities/Industry/CTFShops/Quarters/Quarters.as, Entities/Industry/CTFShops/VehicleShop/VehicleShop.as, Entities/Industry/Factory/Factory.as, Entities/Industry/OldBuildings/Dorm/Dorm.as, Entities/Industry/Trading/TradingMenu.as, Entities/Industry/Workbench/Workbench.as, Rules/WAR/Scripts/WAR.as
Shop.as
"shop buy" - is client->server, sanitized a bit more.
"shop made item" - was server->client and server->server. server->server now uses callbacks. is now server->client "shop made item client".
=> Cmd sanitization shops

Entities/Items/Projectiles/BallistaBolt.as
No idea why it happens but merging it anyway
Shoot bomb ballista bolts on staging
=> [dev] fix sprite muggbug

Rules/CommonScripts/MechanismsCommon.as, Rules/CommonScripts/MechanismsReader.as
MechanismsReader.as, MechanismsCommon.as
"mechanisms_packet" - was a server->server and a server->client command. is now server->client only; server-side code now runs in MechanismsCommon.as rather than in the command (had to change some functions to shared for that, idk what are the consequences of that). renamed to "mechanisms_packet_client".
=> Cmd sanitization mechanismpacket

Rules/CommonScripts/KAG.as
Requires an unreleased test build at the moment. Will be merged when sanitization PRs are all merged. Will require testing to check for any broken behavior.
=> [dev] disable legacy net commands by default

Entities/Characters/Archer/ArcherLogic.as
=> Arrow desync

Entities/Characters/Archer/ArcherLogic.as
=> [dev] fix legolas shot

Rules/CommonScripts/TeamMenuJustSpectator.as
=> [fixed] not being able to switch to spec in tdm

Rules/CommonScripts/accolade_data.cfg
(pick one)
Suggesting accolade for pull-requests with fixes and some potentially needed changes, why not.
=> add github accolade for TerminalHash

Rules/CommonScripts/accolade_data.cfg
I contributed with a lot of bugfix PRs and sometimes with additions to the game.
=> Added mugg1991 github contributor accolade

Rules/CommonScripts/accolade_data.cfg
For making Gix_Devastated_Lake CTF map.
=> Add mapping accolade for Meepo3 (Gix).

Rules/CommonScripts/ChatCommands.as, Rules/CommonScripts/ChatCommands.cfg, Rules/CommonScripts/ChatCommands/MiscCommands.as, Rules/CommonScripts/DefaultChatCommands.as
Adds a new command /time that changes game time.
Join server/solo, type /time (day, night or number in range from 0.0 to 1.0) in chat.
=> Add day time command

Rules/CommonScripts/accolade_data.cfg
=> [dev] Basshunter -> devilide

Rules/CommonScripts/accolade_data.cfg
=> [dev] Give Gingerbeard (MrHobo) the 'github' accolade

Locales/Russian_ru.json
Russian localization in KAG it's something - missing many strings, some things translated very bad, so im tried to improve it in this pull request.
Thanks for **long wood bow** for updating japanese locale, where I got most of the missing strings.
=> [upd] russian localization

Entities/Items/Sponge/Sponge.cfg
Fixes https://github.com/transhumandesign/kag-base/issues/2171
This PR makes it so Sponge changes team when picked up. Why this is of significance is described in the issue.
=> [fixed] Sponge will change team when picked up

Entities/Characters/Princess/Princess.cfg, Entities/Characters/Princess/PrincessAnim.as, Entities/Characters/Princess/PrincessBrain.as, Entities/Characters/Princess/PrincessLogic.as
Fixes https://github.com/transhumandesign/kag-base/issues/2220
Princess Geti didn't make heart animations in online.
This PR re-arranges files and checks for "love is in the air" on server and syncs that to the client in order to fix that problem.
Works as intended in offline and online.
=> [fixed] Princess didn't make heart anim in online

GUI/guiBrowser.xml
Closes #143 
Requires engine pr
=> [new] Show players in the browser

Entities/Structures/Components/Source/Lever/Lever.as
=> [fixed] lever turning on immediately when placed

Entities/Characters/Scripts/UnSpawnImmunity.as
Fixes https://github.com/transhumandesign/kag-base/issues/2285
https://github.com/user-attachments/assets/0606834b-2df5-48a4-a620-654fc6835977
https://github.com/user-attachments/assets/f675cd46-6116-44e6-90e2-4cafed0ab9e9
=> [fixed] Immunity flashing will stop when losing invincibility

Entities/Natural/Animals/Fishy/Fishy.as
Fixes console spam while using /g_debug 2+,
This results in considerably less lag for testing purposes. There is still some console spam on staging caused by dither.png, but that has to be fixed engine side
Fixes issue in vid below
https://github.com/user-attachments/assets/31a06fef-d8af-45b9-b0fe-2c9f7e31bf67
=> [fixed] g_debug spam from fishy script
