Entities/Items/Projectiles/Arrow.as
Currently, arrows are not removed on blob hit.
As a result they're stuck at `Vec2f_zero` (for 20 seconds).
=> Make arrows disappear on blob hit

Rules/CommonScripts/KickAFK.as
Instead of leaving people with kick immunity, like admins, in-game, move them to spectator.
=> Update KickAFK to move people with kick immunity to spectator

Entities/Common/Controls/StandardPickup.as
-corpses made super low priority (used to still have decent priority when extremely close)
-added builder materials priority (gold > stone > wood)
-added saw to combat items (will ensure saw > seed for wood farms)
=> [modified] pickup priority tweaks

Entities/Common/Controls/StandardPickup.as
- material stack pickup priority based on how full the stack is (stacks which are more full have higher priority)
(hope I did the branch naming properly this time)
=> [added] material stack pick-up priority

Scripts/MapLoaders/BasePNGLoader.as
Spikes were an oversight in the loader and chests broke when changing names.
=> [fixed] chests and spikes didn't load from png maps

Rules/WAR/Scripts/WAR.as
See this [bug report](https://forum.thd.vg/threads/2311-never-ending-tth-game.27231/).
The game now checks when warmup finishes for the following cases:
- When one team caps a hall but not the other, the former wins.
- When no team caps halls, it's a tie.
=> Fix endless TTH games

Entities/Characters/MovementScripts/RunnerMovement.as
The issue was that climbing only depended on whether the blob tile was static or not.
When climbing enemy trapblocks, you could walljump with them because they were going static at some point.
However, there was no check to make sure the climber blob can collide with the tile blob in question. This adds an optional `CBlob@` parameter to `RunnerMovement.as` allowing to make sure that the blob can collide with the tile blob.
=> Fixed climbing pass-through structures (such as enemy trapblocks)

Entities/Common/Controls/StandardControlsCommon.as, Entities/Common/Controls/StandardPickup.as
This should make it hopefully more reliable to tap [C] during a battle so it doesn't pickup aimed items in an undesired way by introducing a 15 ticks (0.5 second) delay before aim is taken into account for pickup.
It might be worth merging all the tap logic for all keys in one place if the logic happens to be copied across scripts maybe?
=> [modified] ignore item aim when tapping pickup

Entities/Common/Factory/Shop.as
In your shop blob add `this.set_bool("shop offset is buy offset", true);` to change the "shop location" to wherever the shop offset is, this way you can create a shop outside of the blob's radius. For example, setting this property to true in war base you can actually buy things in the workbench. (with support for setFacingLeft)
=> Add property that allows changing buy offset

Entities/Characters/Archer/ArcherAnim.as, Entities/Characters/Archer/ArcherLogic.as
- The grapple hook is not physically affected during its movement when it's beyond the map top, but will visually look capped to the map top. It looked off when the grapple would hit a topmost block enough for me to think it's a better thing to deal with it like that.
- When the grapple hook hits a block, its position is clamped to the map top (this is the actual fix).
The other option would have been to just let the grapple go when it's over the map top.
=> Fix archer grapple beyond the map top 

Rules/CommonScripts/RedBarrier.as, Scripts/MapLoaders/BasePNGLoader.as, Scripts/MapLoaders/LoaderColors.as
Title.
Add two `A5BDC8` coloured pixels on your map's png to use custom red barrier coordinates. Example:
=>  Add support for customizable redzone

Entities/Special/CTF/FlagBase.as, Rules/CTF/Scripts/CTF.as, Rules/CTF/ctf_vars.cfg
Upon both teams capturing eachother's flags at the same time, a timer will start which will return all flags after a configurable amount of time. The timer can also be disabled in cfgs.
=> Adds Stalemates to CTF

Entities/Structures/MountedBow/MountedBow.as
Arrows (or other ammo, if that manages to happen) now start in front of the bow instead of behind.
Also, there are no inconsistencies regarding arrow spawn location and blob's facing direction anymore.
=> Fixed arrow spawn location for mounted bows.

Entities/Materials/Construction/MaterialGold.as
It's better this way because:
- Easily grabbable chunks of 50 which is how gold is always spent, so you don't have to run out of base with your team's entire gold supply if you want to set up a tunnel
- Harder (but still possible) for one team to collect all the gold and hoard it at their base
- Easier to see when a functional amount (50) is lying on the ground instead of the current small yellow pebble
- Mining 5 blocks of ore gives you an even 100 gold anyway
=> [modified] Gold material now stacks to 100 (two lumps of 50)

Entities/Characters/Builder/BuilderInventory.as
It was supposed to make a sound effect so it's more obvious what just happened and less confusing if you accidentally use the quickswap. It's the same sound effect that plays when you tap F as archer/knight.
Also, it was kind of weird that you could "quickswap" to the building, because that has the effect of immediately using 150 wood, so it should ignore building selection.
=> Builder quickswap fixes/tweaks

Entities/Items/Projectiles/Arrow.as
As requested in bounty # 3 for July 2018.
Fixes bomb arrows acting strangely by making them explode immediatly on contact with enemies. This will deal 1.5 damage to the hit enemy.
This was tested on a server for a while in a number of scenarios, however it's possible the issue may still exist. If it does I'll be happy to fix it.
=> Makes bomb arrow damage consistant

Rules/CommonScripts/VoteCommon.as
As shown in #180. Very simple fix. I'm fairly certain this was the only vote message that had this kind of error. The vote object creates a title "Kick {USER}" but that user is the one that created it and then that title was passed to the VotesCommon script. I simply circumvented it by manually getting the user_to_kick variable.
=> [fixed] the message for vote kicking

Entities/Characters/Scripts/RunnerActivateable.as, Entities/Common/Controls/StandardControls.as, Entities/Common/Emotes/EmotesCommon.as, Entities/Items/Crate/Crate.as, Entities/Items/Crate/Crate.cfg, Entities/Items/Crate/CratePickupCommon.as
There was a way to take players out of crates and hold them in your own hand / inventory...
You could even get in another crate + go into someone else's inventory for infinite crate clown car...
Yeah...
...Sorry for fixing it before you got to abuse it :P 
Other fixes/additions:
- You can now activate held crates with spacebar to dump out all non-player items that were in there, so you can put only what you want in it
- Fixed opening own inventory and taking out items while inside crate (to do things like teleport + use phantom drills)
- Fixed crashing sandbox/localhost by booby trapping crates with more than one mine
- Fixed vehicle crates / crates with stuff packed in them from picking up items (note: !crate with sv_test still counts as a packed crate because you can do !crate blob, so …
=> Crate fixes + dump out items with spacebar

Entities/Common/Scripts/RandomExitVelocity.as, Entities/Industry/CTFShops/Storage/Storage.cfg, Entities/Vehicles/Boats/Dinghy.cfg, Entities/Vehicles/Boats/LongBoat.cfg, Entities/Vehicles/Boats/WarBoat/WarBoat.cfg
Added a script for blobs to have a random (upward) velocity when leaving another blob's inventory. Can tag blobs with "blacklist random exit vel <blobname>" to blacklist this behavior when leaving <blobname> blobs.
Added this script to boats.
=> added random inventory exit velocity

Rules/CommonScripts/Report.as
Small change, prints a string to tcp, the bot reads it and if the baddie has 1 report it notifies the oksa in discord. If the baddie has 2 or more reports it pings the admins
For the future:
- It would be ideal to synchronize bans throughout all the official servers.
- Handling seclevs accordingly.
=> [added] ability to report reports to discord bot

Entities/Structures/Trampoline/TrampolineLogic.as
**READY**
Implemented a 'smarter' cooldown that can support up the cooldown of up to 8 objects. The limit is a safety feature that limits the number of cooldowns that need to be process on every collision. there is a SAFETY bool that can be set to false to disable the feature.
create a trampoline and build a tall column of background blocks.
at the top of the background blocks, build a block. 
place multiple objects on top of the block. 
destroy the block. 
observe the multiple objects bouncing on the trampoline at the same time.
=> Implemented a 'smarter' trampoline cooldown that can support the cooldown of multiple objects

Entities/Industry/CTFShops/Quarters/Quarters.as
**READY**
If you are killed at the same time you sleep in a quarters, your dead body sleeps in the bed
1. Build quarters
2. Spike yourself twice
3. Spike yourself a third time and sleep in the quarters at the same time
It seems to only occur on servers and it's somewhat difficult to reproduce
=> Fixed bug where dead blob isn't detached from quarters

Entities/Special/CTF/CTF_Flag.as
**READY**
Flags that fall into the void are instantly returned to base. This is good because it's currently annoying to wait for the flag to respawn and the flag begins to glitch out when sitting at the bottom.
Inspired by [this](https://forum.thd.vg/threads/25490/) suggestion by Makmoud
Throw a flag into the void
=> Instantly return flags that fall into the void

Rules/CommonScripts/Report.as
**READY**
Made it so that one person can only report another unique person a maximum of once per round.
=> [fixed] unique player can only report another unique player once per round

Entities/Items/Projectiles/Arrow.as
**READY**
Similarly to how fire arrows are extinguished when passing through water, normal arrows are ignited when passing through flames
1. Build a wooden structure with backwall or find grass, bushes or trees
2. Set fire to the structure or flora
3. Shoot normal arrows through the fire
=> Normal arrows are ignited when passing through flames

Entities/Vehicles/Common/SeatHop.as, Entities/Vehicles/Common/SeatsGUI.as
**READY**
To prevent players from sitting on vehicles/animals that are behind blocks, a raycast check has been added to check for solid blocks. The bobbing arrows also don't show when there is a solid block preventing you from sitting.
1. Spawn siege/shark/bison
2. Place blocks above it
3. Try sitting on it
=> Added raycast check for seats

Entities/Characters/Migrant/MigrantLogic.as, Entities/Items/Projectiles/Arrow.as
**READY**
Arrows now pass through migrants instead of sticking in them and doing no damage. This will make it easier for archers to kill enemies surrounded by migrants. If you want to kill enemy migrants, you can always slash them as knight.
Inspired by [this](https://forum.thd.vg/threads/26687/) bug report by Coroz
Shoot any migrant regardless of team
=> Arrows pass through migrants

Entities/Common/Emotes/EmoteMenu.as
**READY**
This fix ensures the emote wheel disappears when you die
Die while holding Q
=> Fix to ensure emote menu disappears when you die

Entities/Items/Projectiles/Arrow.as
**READY**
Since archers currently don't have a way to get grain from grain plants, I decided it would be useful for arrows to 'cut' grain plants if shot at the block below them. It takes into account arrow velocity which means stray arrows don't instantly destroy grain.
A fully charged shot at point-blank range instantly destroys the plant, half shot in two and quarter shot in three. The number of arrows it takes increases depending on the range since arrow velocity is reduced.
Shoot the block below a grain plant at varying strengths and distances
=> Grain plants can be 'cut' by arrows when shot at the block below

Entities/Characters/Scripts/RunnerKnock.as
**READY**
When you have multiple sponges in your inventory, the one which has absorbed the highest amount of water is used first. This reduces inventory clutter by using each sponge one at a time rather than spreading uses over all of them.
Put sponges in your inventory and stun yourself with water
=> Use highest absorbed sponge first when stunned by water

Entities/Characters/Builder/BuilderLogic.as, Entities/Characters/Knight/KnightLogic.as, Entities/Characters/Scripts/CrouchCommon.as, Entities/Characters/Scripts/RunnerCollision.as, Entities/Characters/Scripts/RunnerDefault.as
**READY**
This includes the requested changes from my previous pull request. This implementation uses the `"allow crouch"` tag to specify which states allow crouch dodging and an `isCrouching()` function to check if you’re crouching.
States which enable crouch dodging:
- Visibly crouching
- Placing blocks as builder
- Shielding as knight
I went with whitelisting instead of blacklisting because only a few states allow crouch dodging.
I included the builder's block place state because it isn't an attacking frame which doesn't allow people to attack while crouch dodging.
Test 1: Throw a boulder in the air and crouch to dodge it while in different animation states
Test 2: Place a boulder on the ground and crouch grapple through it
=> Implemented better crouch dodge code

Entities/Characters/Archer/ArcherAnim.as, Entities/Characters/Archer/ArcherCommon.as, Entities/Characters/Archer/ArcherLogic.as
**READY** (community feedback needed)
As suggested by @norill, archers shouldn't auto switch to special arrows when they are out of regular arrows. I have extended on his idea by preventing auto switch to special arrows when out of any arrow type. You still auto switch to regular arrows when out of special arrows.
Advantage:
- Reduces the likelihood of accidentally shooting special arrows
Disadvantage:
- Requires the player to manually select / quick switch to special arrows in more situations
Closes #231 
Test 1: Have normal + special arrow in inventory, shoot all of normal arrows (you shouldn't auto switch to special arrow)
Test 2: Have normal + special arrow in inventory, shoot all of special arrows (you should auto switch to normal arrows)
Test 3: Have two types of special arrows in …
=> Archers don't auto switch to special arrows

Entities/Characters/Builder/BuilderAutoPickup.as, Entities/Materials/MaterialCommon.as
**READY** (community feedback needed)
This adds what was suggested in @Frankulushus' suggestion (#288). I also changed the material anim index equation so the biggest stack sprite is only shown for a max stack. This will make it easier to visually see which stacks of gold will be auto picked up (and which stacks have enough gold to be useful).
Closes #288
Test 1: Mine 50 gold, drop it on the ground, wait a bit, then walk over it (it should auto pickup like usual)
Test 2: Mine less than 50 gold, drop it on the ground, wait a bit, then walk over it (it shouldn't auto pickup since its quantity is too small)
Test 3: Mine more than 50 gold, drop both stacks on the ground, manually pick up the larger stack, wait a bit, then walk over the smaller stack (it should auto pickup even though its …
=> Gold auto-pickup change

Entities/Vehicles/Ballista/Ballista.as, Entities/Vehicles/Catapult/Catapult.as
**READY**
Added what was suggested by @bunniewormy in #292 but also decided to enabled the flip button. This is because it would be useful to flip the siege upright as your capturing it instead of having to watch it destroy itself.
Closes #292 
Spawn a siege, flip it, swap team and try to use the buttons
=> Enabled flip and change class buttons on enemy sieges

Entities/Characters/Scripts/RunnerKnock.as
READY
This PR adds some counterplay to water stuns by allowing them to be blocked. If successfully blocked then the stun is halved (22 rather than 45 ticks).
22 ticks is still a long time - enough for water stuns to be powerful but not oppressive.
Sponges function as normal.
This affects water bombs and water arrows. I've tested both in sandbox.
References #241
Test it on my server (Eluded TDM)
- Play as knight
- Throw a water bomb upwards so it lands just to the left/right of you
- Notice that if you're shielding in the right direction then the stun is halved
=> Halve the stun from water if it was shielded

Entities/Characters/Builder/CommonBuilderBlocks.as, Entities/Industry/Factory/Factory.as
In TTH at the moment, (generic aka default) factories are called "Workshops" - the same for the default building in CTF/Sandbox. All the other specific factories do have "factory" in their name, though. When I first started playing KAG (specifically Take The Halls), I got confused by this, thinking I could build CTF shops, wanting to make a builder shop. So, I wasted my un-re-gainable mats on the factory when I should've built a Workbench. So I want to fix this, even though it'll mostly just help KAG beginners.
So, I've changed the factory's name in the Builder's menu to "Factory," and I also added a short description for the !factory and !workbench structures (in the building menu).
=> Factory Named Properly

Entities/Common/Factory/Shop.as
**READY**
This prevents purchasing items while looking at a shop's menu after it's been destroyed. Clicking on a shop item just closes the menu and does nothing.
Fixes [this](https://forum.thd.vg/threads/27069/) bug
1. Build a shop
2. Open shop menu
3. Have another player destroy the shop
4. Attempt to buy an item
=> No longer able to buy items from destroyed shops

Entities/Industry/Trading/TradingMenu.as
Before you could buy stuff far away from trading post.
This fix make player be able to buy stuff only when he is close to it.
Images:
before
after
proposed to me by Biurza (:
=> Change range of the buy button for trader post

Entities/Common/Controls/StandardPickup.as
- **READY**
Lit kegs now are even more prioritized, and unarmed enemy mines are now a priority as well.
- drop a bunch of stuff on ground
- light a keg and try to pick it up with tap
- drop a mine and pick it up as a different team
=> Adjusted some pickup priorities

Entities/Common/Building/PlacementCommon.as
**READY**
This adds the ability to place stone blocks on damaged wood blocks only if the wood isn't on fire. You shouldn't be able to repair wood blocks that are on fire because that'll make stopping fire easier.
Closes #295
Place stone blocks on damaged wood
=> Added ability to upgrade damaged wood blocks

Entities/Structures/Trampoline/TrampolineLogic.as
**READY**
Finally fixes a long-standing bug which allows knights to fly using trampolines.
Follow instructions in [this](https://forum.thd.vg/threads/25571/) bug report
=> Fixed trampoline flying glitch

Entities/Items/Projectiles/BallistaBolt.as, Entities/Vehicles/Catapult/Rock.as
READY
Allows catapulted rocks to pass through platforms from the backside and still hit from the front.
Adds a short period of time before catapulted rocks will hit back_wall. (prevents destroying own castle)
Allows ballista bolts to pass through platforms from the backside and damage the front.
Fire a catapult or a ballista at platforms facing different angles.
=> Catapult Rocks & Ballista Bolts Pass Through Platforms Fix

Entities/Vehicles/Boats/Dinghy.as, Entities/Vehicles/Boats/Dinghy.cfg, Entities/Vehicles/Common/VehicleConvert.as
- **READY**
1. Added a button to dinghy akin to storage's dump-inventory button. Dumps every item in your inventory into the dinghy.
2. Dinghies can only be picked up by same team players.
3. Dinghies take less time to capture than other vehicles (7.5 seconds compared to 15 seconds)
**0.** Spawn a dinghy with !dinghy (assuming sv_test is set to 1)
**1.** Dinghy dump inventory button
- Put items in your inventory. Button should not appear if there are no items in your inventory.
- Test with dinghy not carried / carried. Button should only appear when not carried.
- Test with dinghy same / different team. Button should only appear with same team.
**2.** Dinghy can only be picked up by same team players.
- Try to pick up a dinghy as same team and different team. 
**3.** Dinghy captures …
=> Miscellaneous dinghy improvements.

Entities/Characters/Scripts/EatFoodButton.as, Entities/Items/Food/EatCommon.as, Entities/Items/Food/Eatable.as
**READY**
Fixed issue where the item your holding is dropped if you heal using the eat key.
1. Have food in your inventory
2. Damage yourself
3. Hold a random item in your hand
4. Heal using the eat key
=> Held item is no longer dropped when using eat key

Entities/Common/Emotes/EmoteHotkeys.as, Entities/Common/Emotes/EmotesCommon.as, Rules/CTF/gamemode.cfg, Rules/Challenge/gamemode.cfg, Rules/CommonScripts/BindingsMenu.as, Rules/CommonScripts/EmoteBinderMenu.as, Rules/Sandbox/gamemode.cfg, Rules/TDM/gamemode.cfg, Rules/WAR/gamemode.cfg
**READY**
This adds an in-game menu which allows you to change the emote for each hotkey.
Closes #154
1. Join a game
2. Open main menu by clicking escape key
3. Click "Bind Emotes" button
4. Change emotes
5. Respawn to update emotes
=> In-game emote binder

Entities/Items/Explosives/Keg.as, Entities/Items/Explosives/KegVoodoo.as, Entities/Items/Projectiles/Arrow.as
**READY**
Improvements:
- Fire/fire arrows activate (arrows only collide with unlit enemy kegs and any lit keg)
- Water buckets deactivate (only water buckets to still allow launching kegs with water bombs)
- Explosion chain reaction
- Invincible to other keg explosions (to allow for chain reaction)
- Fixed weird fuse sound when relighting keg after it was frozen by admin
10-1 in favour of these changes. People were indecisive whether the fire and/or water changes were good. This will most likely still require a #democracy vote in Discord since this changes the most powerful weapon in kag.
Closes #279
!keg
=> Improved keg functionality

Rules/CTF/mapcycle.cfg
**READY**
Move 8 old maps to the returning maps pool so CTF mapcycle stays at 30.
=> [modified] Mapcycle - move 8 old maps to returning maps pool

Entities/Characters/Scripts/RunnerHead.as, Rules/CommonScripts/ScoreboardCommon.as, Rules/CommonScripts/ScoreboardRender.as
**READY**
- Adds player heads to the scoreboard
- Works with head packs, holiday, accolade and special heads
- Slightly increased padding between players on the scoreboard so heads don't overlap as much
- Includes change to ensure KDR always has two decimal places
Closes #321
Press tab
=> Added player heads to scoreboard

Entities/Vehicles/Ballista/Ballista.as
**READY**
This pull request prevents the ballista from shooting anything other than it's configured ammo type. Because f2p is being worked on, securing the game is essential. Currently, by injecting client side code, it is possible to launch all blobs on the map using a ballista.
- Start a sandbox game
- Spawn a ballista
- Shoot a bolt: it behaves like normal
- Open the console and run this code:
```
CBlob@[] all;
getBlobs(@all);
for (u32 i = 0; i < all.length; i++)
{
CBlob@ blob = all[i];
if (blob.hasCommandID("fire blob"))
{
for (u32 x = 0; i < all.length; x++)
{
CBitStream params;
params.write_netid(all[x].getNetworkID());
params.write_u8(100);
blob.SendCommand(blob.getCommandID("fire blob"), params);
}
break;
}
}
```
- One or more warnings appear in the console, the player does not …
=> Limit the ballista to shooting it's ammo type

Entities/Common/Respawning/StandardRespawnCommand.as, Entities/Special/TDM/TDM_Ruins/TDM_Ruins.as, Entities/Special/Tent/TentLogic.as, Entities/Special/WAR/WAR_base/WAR_base.as
**READY**
- Tap 'e' to quickly swap to each class at a tent or TDM ruins
- Ruins require you to tap within 7 ticks (the same as quick switching bomb/arrow types)
- Tents require you to tap within 4 ticks otherwise it would be irritating waiting for the menu to open
- Halls have been neglected for the time being since they are acting a bit spoopy :P
Closes #373
Tap the use key ('e') while in front of a tent or ruins
=> Quick swap class

Entities/Characters/Archer/ArcherLogic.as
- **READY**
A attacker can send invalid parameters in a shoot command, which will crash the archer script and break the archer class.
- Start a game
- Spawn any kind of arrow
- Switch to that arrow
- The arrow gets switched
- Run this code
```
CBlob@[] all;
getBlobs(@all);
for (u32 i = 0; i < all.length; i++)
{
CBlob@ blob = all[i];
if (blob.hasCommandID("shoot arrow"))
{
Vec2f zero = Vec2f(0,0);
CBitStream params;
params.write_Vec2f(zero);
params.write_Vec2f(zero);
params.write_u8(4);
params.write_bool(false);
blob.SendCommand(blob.getCommandID("shoot arrow"), params);
}
}
```
- Nothing happens
=> Archer command validation

Entities/Industry/Tunnel/TunnelTravel.as
- **IN DEVELOPMENT**
A attacker can abuse a command that should only be called by the server, to bypass exisiting bounds checks for traveling to a tunnel. This allows every blob on the map to be teleported to a tunnel.
This fix hasn't yet been tested with multiple clients, so I can't assure that it has no side effects.
Due to the fact that this bug is critical and requires a patched binary, I will not post instructions here. Feel free to pm me if you want instructions.
=> Tunnel bounds check bypass

Entities/Special/CTF/CTF_Flag.as, Entities/Special/CTF/FlagBase.as
- **READY**
A attacker can use ctf flag commands to write arbitrary chat messages without exposing his username.
- Start a game
- Pickup a flag normally
- The normal "picked up by username" appears
- Run this code
```
CBlob@[] all;
getBlobs(@all);
for (u32 i = 0; i < all.length; i++)
{
CBlob@ blob = all[i];
if (blob.getName() == "ctf_flag")
{
CBitStream params;
params.write_string("Hello there!");
blob.SendCommand(blob.getCommandID("pickup"), params);
return;
}
}
```
- Nothing is displayed in chat
=> CTF Flag arbitrary chat message

Entities/Characters/Scripts/UnSpawnImmunity.as
Fix for this issue: https://github.com/transhumandesign/kag-base/issues/416 When joining UnSpawnImmunity.as would only call OnInit tagging blobs with invincible. However because it was removed earlier it would never get untagged for that client causing a few bugs.
Following the steps in the issue you can reproduce the bug. Then pull this fix and test the bug again to see that it does not happen any longer.
=> [fixed] spawn immunity not being unset for joining players

Rules/CTF/gamemode.cfg, Rules/Challenge/gamemode.cfg, Rules/CommonScripts/AdminRedToggle.as, Rules/CommonScripts/AdminRedToggleCommon.as, Rules/CommonScripts/ScoreboardCommon.as, Rules/Sandbox/gamemode.cfg, Rules/TDM/gamemode.cfg, Rules/WAR/gamemode.cfg
Red names default to off.
- **READY**
Adds the ability for an admin to toggle their red name, with the red defaulting to off. The goal of this PR is to help admins punish bad players-- a lot of said players quit being bad when an admin joins.
- as admin, type `!toggle redname` in chat. no message should send to other clients, and your name should toggle red / not red
=> Added admin red name toggle.

Entities/Characters/Builder/BuilderHittable.as, Entities/Industry/Fireplace/Fireplace.as, Entities/Industry/Fireplace/Fireplace.cfg, Entities/Items/Projectiles/Arrow.as, Scripts/MapLoaders/BasePNGLoader.as
**READY**
This PR excludes the stuff to do with adding fireplaces to CTF/TTH
- Fireplaces rotate so they don't look like they are levitating when put on the edge of a block
- Modified fireplace hitbox which makes it sit properly on the ground when upside down. It also makes it slightly harder for it to roll upside down
- Builders can hit fireplaces
- Bombs / water bombs knock around fireplaces now that fireplaces no longer become static
- Fireplaces no longer become static, especially when the map loads which caused them to float
- Load maps where fireplaces used to float
- Niiiiii_Watery
- FG_SpaceInvader
- Hit fireplaces as builder
- Knock fireplaces around with explosives
=> Fireplace fixes and minor improvements

Rules/TDM/tdm_vars.cfg
**READY**
TDM warm up timer is reduced from 5 seconds to 1 second in order to stop players from re-spawning that die before the warm up timer is finished.
Attempt to kill an enemy quickly in TDM 
or 
Quickly press esc and then suicide
=> Reduced TDM warm up timer

Entities/Items/Boulder/Boulder.as, Entities/Vehicles/Catapult/Catapult.as, Entities/Vehicles/Common/Vehicle.as
**READY**
- Boulders no longer enter rock n' roll mode when swapped out of a catapult
- Players can no longer kick other players out of catapults while they're waiting to be fired
- Replacing an item with another item now drops the original item instead of 'deleting' it
Rock n' roll bug:
1. Load boulder into catapult
2. Replace the boulder with another item
3. The boulder shouldn't fall down through blocks like it used to
Kick out players:
1. Have a teamate sit in the bowl of a catapult
2. Attempt to put an item into the catapult
3. The button to add an item to the catapult shouldn't display
Replacing item with item bug:
1. Put item into catapult
2. Replace the item with another item
3. The original item should fall out
=> Catapult improvements

Entities/Common/Respawning/StandardRespawnCommand.as
**READY**
A lack of validation in the class change command allows an attacker to turn any blob in the area of a class change point into any other blob.
Due to the critical nature of this vulnerability, no steps to reproduce will be published. Pm me for instructions.
=> Validate class change

Entities/Common/Emotes/EmoteHotkeys.as, Entities/Common/Factory/Shop.as, Entities/Industry/Building/Building.as
**READY**
This adds the ability to buy items from shops by pressing a number key. The keybinds match shop buttons from left to right, top to bottom. This only works once you've clicked 'e' on a shop to prevent accidental purchases. If a shop has more than nine items (which none do at the moment), there will only be keybinds for the first nine items. This also works on the buildings which allow you to choose the shop you want.
Closes #240
Press 'e' on a shop and press a number key for the item you want
=> Shop keybinds

Rules/CommonScripts/ScoreboardRender.as
Do you have this problem
because you play on default resolution and you're a freak like me? Then this PR should fix your problem by allowing the scoreboard to scroll when it's to big for the screen.
You can reproduce this issue by playing on the default resolution. And joining a server with more than ~16 people
Also note I removed the server info shifting because there's no reason for it to make extra room now.
=> [added] scoreboard scrolling

Rules/CommonScripts/ScoreboardRender.as
**READY**
The tier displayed was one higher than what you actually pledged which caused the teir 4 icon to be invisible
=> Fixed patreon tier icon displaying wrong tier

Rules/CommonScripts/Accolades.as, Rules/CommonScripts/ScoreboardRender.as, Rules/CommonScripts/accolade_data.cfg
**READY**
- Fixed typo which prevented moderation accolades from being detected and displayed
- When admin on a server, the accolade is only shown when the player has a red name
- When on any other server, the accolade is always visible
- Found Sarius and Toblerone's missing accolades
- Added Github badge for Atheon
=> Fixed missing moderation accolades

Rules/CommonScripts/ScoreboardRender.as
**READY**
Changed `redNameEnabled`  to `coloredNameEnabled` when checking whether it should display a player's moderaction accolade.
Join sandbox without getting an error in console
=> Fixed outdated function name

Rules/CommonScripts/Report.as
**READY**
Simple change that sends the servername of the report to the connected bot.
=> [added] send servername to bot for discord message

Entities/Structures/Common/DefaultNoBuild.as
- **READY**: Working/Ready
- To fix the problem shown here: https://www.youtube.com/watch?v=CXXJQ_bPQZg
- Make the "nobuild extend" zone well aligned.
- Before the change:
- After:
- To reproduce:
1. Join a singleplayer sandbox.
2. Try building a block inside the tent/[attempt to destroy the dirt block at the left side of the tent](https://www.youtube.com/watch?v=CXXJQ_bPQZg).
=> [Fixed] Wrong position of nobuild-zone

Rules/CommonScripts/ScoreboardRender.as
**READY**
I realised that regular admins don't have rcon perms so the moderation accolade was always visible even if the player disabled their name colour.
1. Be admin on a server
2. Disable your name colour
=> Fixed issue with moderation accolade

Rules/CommonScripts/ScoreboardCommon.as, Rules/CommonScripts/ScoreboardRender.as
**READY**
- Admins always see other admins' name colour and moderation accolade
- You are still able to see whether your name colour is hidden or not
Resolves #475
1. Be admin on a server with other admins
2. Ask other admins to toggle their name colour
- You should always be able to see their name colour and moderation accolade
3. Toggle your own name colour
- Should work like usual - only see moderation accolade when name colour is visible
=> Admins always see other admins' name colour and moderation accolade

Entities/Common/Taunts/TauntMenu.as
**READY**
These settings might be needed in case taunts are spammed in f2p or if people change their opinions of taunts.
- Click to select category bool
- Show taunts in chat bool (depends on `cl_chatbubbles` setting)
=> Extra taunt settings

Entities/Common/Controls/StandardControls.as
**READY**
If you zoom out from the closest zoom while holding 'e' or 'c', the camera instantly zooms out. I'm not sure why this is a thing... please let me know if this is important for anything.
1. Zoom in fully
2. Hold 'e' or 'c' (or press it while zooming out)
3. Zoom out
=> Fixed camera jumping when zooming out while holding 'e' or 'c'

Rules/CommonScripts/accolade_data.cfg
**READY**
Ruleral's moderation accolade isn't showing in-game because he's listed twice in `accolade_data.cfg`.
I missed this when resolving merge conflicts between #468 and #472.
=> Ruleral accolade fix

Entities/Industry/Saw/Saw.as, Entities/Items/Explosives/Mine/Mine.as
- **READY**
- This PR modifies the way saws affect mines in two ways:
1. Saws no longer destroy same team's mines (avoid griefing/destroying your teammates mines by mistake).
2. Saws only destroy enemy mines if fed directly to the saw (the same way it works for killing players); to avoid abusing saws to clear the field (see: someone running with a saw throwing it into bushes to neutralize enemy mines).
- **How it used to work:**
[Having your mines destroyed by mistake.]
[Having an enemy using the saw as an anti-mine shield.]
[Clearing mines on the field in a matter of seconds.]
- **How it should be working after this PR:**
[Saws no longer waste your hard-earned mines.]
[Enemies can't use saws as shields.]
[In order to eliminate an incoming enemy mine, you should position/throw the saw …
=> [modified] the way saws affect mines

Entities/Industry/Saw/Saw.as
**READY**
- Dead bodies disable saws of the same team
- Gives knights and archers a way of 'disarming' saw traps without needing a builder to block it off / destroy it
- Mines have similar behaviour which works really well
- This gives bodies more uses other than for taunting with ;)
- If alive teammates disable saws, shouldn't their dead bodies also do the same?
- Saws no longer destroy other saws
- Why was this even a thing? Most of the time you accidentally destroy your own saws and get called out for griefing
- Throw a dead body into top of a saw of the same team
- Throw a saw into another saw
=> Dead bodies disable saws of the same team

Entities/Characters/Archer/ArcherCommon.as, Entities/Characters/Archer/ArcherLogic.as
**READY**
This adds the ability for archers to adjust the length of their grapple. This gives them a bit better control while grappling up and around walls while barely impacting the current grapple meta. The grapple extends within the rope's current limits to prevent players from extending the rope to an 'unrealistic' length. You are able to adjust the grapple as it's being thrown and while it's attached to a block. The speed of adjustment can be changed in code if it's too slow, but I found that increasing the speed causes the player to wobble about too much.
Resolves [this](https://forum.thd.vg/threads/15981/) suggestion from 2013 lol
Press W and S while your grapple is out
=> Adjust grapple length

Entities/Characters/Scripts/EatFoodButton.as, Entities/Items/Food/EatCommon.as
**READY**
This pr makes the eat button calculate your missing hearts and choose an appropriate food. It prefers to overheal than to underheal. If you miss one heart and carry a heart and a burger, it will always choose to consume the heart, no matter the order in the inventory. If more food items(different healing amounts) are added in the future, this should be compatible.
- Start a sandbox game
- Spawn a burger and a heart
- Put the burger in your inventory first, then the heart
- Take one heart of damage
- Press V
- The heart should be consumed
=> Improve eat button

Rules/CommonScripts/AssistCommon.as, Rules/CommonScripts/KillMessages.as
**READY**
- Assist hover messages are no longer shown to everyone
- Assists are not given if the victim is on the same team as the killer or the assist player
- Have an assist occur with other players on the server to see if only the assist player gets the hover message
- Have red player damage blue player and then have another blue player teamkill the damaged player
- Have blue player damage another blue player and then have a red player kill the damaged player
=> Assists fix

Entities/Common/Includes/Costs.as, Entities/Industry/Building/Building.as, Entities/Industry/CTFShops/CTFCosts.cfg, Entities/Industry/Saw/Saw.as
**READY**
- Limit one quarry per team
- Reduced the amount of wood gained by sawing crates from 100 to 50 wood
- Crates gave too much wood for its price which made it easy to keep quarries operating
Closes #328
Attempt to build more than one quarry
Throw a crate into a saw to get wood
=> Quarry balance

Entities/Items/Heart/DropHeartOnDeath.as
**READY**
Resolves #523
- New player kills new player (heart is dropped)
- New player kills old player (heart is dropped)
- Old player kills new player (heart isn't dropped)
- Old player kills old player  (heart is dropped)
I tested by overriding the `newVictim` and `newKiller` bools in code to replicate the scenarios above
=> New players drop hearts when killed by new players

Rules/CTF/Scripts/CTF_Trading.as, Rules/CommonScripts/DefaultScoreboard.as, Rules/CommonScripts/KillMessages.as
- **READY**
This PR makes the modifications suggested here #506 and closes #522 .
In other words: 
1.  in competitive gamemodes kills, deaths and assists no longer get counted if:
- It's the warm-up phase.
- One team won and the game is ended.
When it comes to sandbox, KDA should work the same way they used to be.
2. You can now suicide during the building/warm-up phase without:
- Having your name showing or spamming the kill-feed. (after the warm-up your suicides revert to being visible by everyone).
- You no longer loose a percentage of your coins. (again, only during the warm-up).
- Increasing your death count on the scoreboard.
These changes should encourage using the suicide button, to help with getting back to base and refilling without being afraid of affecting your KDR or wasting …
=> [modified] kills, deaths and assists only count when the round is on; no coin loss and no killfeed mention, if suicided during warm-up.

Entities/Characters/Scripts/RunnerFootSteps.as, Entities/Common/Scripts/DetectLadder.as
**READY**
This adds the ability for players to fall through ladders by holding S before colliding with ladders. If they let go of S while colliding with a ladder, they will climb the ladder like usual. Pressing S while climbing the ladder won’t make the player fall through it until they stop colliding with the ladder.
The only issue I see with this is that players wanting to immediately climb down ladders will most likely fall through them. They would need to not press S until they have collided with the ladder, then they can climb down without falling through.
Even with this issue, I believe the benefits this will bring to movement will outweigh the issues it may cause.
I added footstep sounds when climbing ladders to make it clearer if you are actually climbing the ladder.
I also …
=> [Improvement] Ability to fall through ladders + ladder footstep sounds

Entities/Characters/Archer/ClimbArrows.as
**READY**
Removed the ability for players to climb arrows while stunned
1. Shoot a bunch of arrows into a wall
2. Stand next to the wall
3. Jump then immediately stun yourself with water
4. Attempt to climb the arrows
=> [Bug fix] Removed ability to climb arrows while stunned

Entities/Common/Building/BlockPlacement.as, Entities/Common/Building/PlacementCommon.as
**READY**
- Fixed block placement preview showing that you can place blocks next to grass when you actually can't
- Fixed jittery tile preview when you're about to place a block while moving
- Attempt to place a block next to grass
- Move around with a block in your hand while hovering your cursor over a single tile
=> [Bug fix] Fixed minor issues with builder block placement preview

Entities/Items/Lantern/Lantern.as
**READY**
In maps like Niiiiii_GetisArena, water bombs tend to collide with the static floating lanterns. This PR only makes lanterns collide with static blobs like doors and platforms.
Throw a water bomb at a lantern.
=> Lanterns only collide with static blobs

Entities/Common/Controls/StandardPickup.as
**READY**
Resolves #636 
1. Hold 'c'
2. Click to pick up a highlighted item
3. Release 'c' (another item should not be picked up)
=> Item isnt picked up when 'c' is released if one was picked up by clicking

Entities/Items/Food/Eatable.as
**READY**
5 coins for healing a teammate with a heart and 10 coins for anything else
Picking up a teammate's food while on full health and then later healing yourself won't give the person coins
Resolves #629 
Get a teammate to heal themselves using food you once held
=> Coins for healing teammates

Entities/Vehicles/Common/WoodVehicleDamages.as, Rules/CTF/Scripts/CTF_Trading.as, Rules/CommonScripts/GameplayEvents.as
**READY**
The number of coins given when damaging vehicles is based on damage dealt instead of it being a fixed amount. This also makes kegging enemy vehicles a bit more worthwhile since it gives back a fair bit of coins.
5 coins are given per heart of damage dealt (jabs and fully charged arrows do 1 heart, and slashes do 2 hearts).
Damage enemy vehicles using various methods
=> Vehicles give coins based on damage dealt

Entities/Industry/Drill/Drill.as
**READY**
Increased from 50% to 100%
Fixed raycast issue in preparation for engine-side fix
Resolves #618 
Drill tiles/blobs for their materials and compare to the amount given when mining by hand
=> Drill yields all materials when mining tiles/blobs

Entities/Items/Food/Eatable.as
Caused by CPlayer being invalid if the blob is holding food and dies.
I've added extra null checks just in case as well
Thanks @bunniewormy for giving logs
=> Food null error fix

Entities/Industry/Drill/Drill.as
When you move when the drill ui while it's being used, it looks blurry, so we use getInterp to fix that.
Thats it, just a small problem I have with drills in game
=> Drill ui blur fix

Entities/Vehicles/Boats/Dinghy.cfg, Entities/Vehicles/Common/FakeBoatCollision.as
(pick one)
Current interaction between boats, known as collison aren't good or fluid. With this update I offer you new solution:
team boats do not collide with each other, sailing will be much more easier.
team boats collide with enemy boats, thats good thing right? of course it is
oh right needed add FakeBoatCollision.as to dinghy.cfg. dinghy is boat.
do I really need write that you should use boats in water not on land?
=> Fluid interaction between boats

Rules/CommonScripts/RedBarrier.as
Switched red barrier to cmd instead of it using sync, from my experience (and other's) using cmd to send important information like red barrier position tends to be more reliable. 
It should fix issues where the barrier is overreaching, underreaching, or just straight out gone. 
Example: https://forum.thd.vg/threads/what-is-that.28190/#post-410073
This works localhost + on a dedicated server from testing.
=> Red barrier moved to cmd from sync

Entities/Characters/Archer/ArcherLogic.as, Entities/Characters/Knight/KnightLogic.as
**READY**
If a knight/archer charges a slash/bow before entering a crate, they are able to instantly slash/shoot upon exiting the crate. This used to work by sitting in vehicles but that was fixed ages ago, so I don't see why this shouldn't be fixed too.
Please don't say this is a mechanic since most people don't know about it, and the people who do most likely never use it.
1. Hold a crate
2. Charge a slash/bow
3. Press 'E' to enter the crate
4. Before exiting the crate, hold left mouse button
5. Exit the crate
6. Release left mouse button to slash/shoot
=> [Bug fix] Removed ability for knights/archers to insta-slash/shoot when exiting crates

Entities/Structures/Ladder/Ladder.as, Entities/Structures/Platform/WoodenPlatform.as
(pick one)
It should be free from _unintended features_.
Platforms and ladders give a small amount of wood when mined. it's for this issue https://github.com/transhumandesign/kag-base/issues/630
use pickaxe on platform to recive 2 woods per hit, on ladder it's 3 per hit
=> Platforms and ladders give a small amount of wood when mined

Rules/CommonScripts/KAG.as
It isnt used anywhere engine side, easier to reset the values instead of doing this engine side so modders can see the default values.
Currently there's a problem with this when a user goes to join goldenguy's r/place mod, then join a vanilla or other modded server. This fixes it for vanilla gamemodes by resetting the base value back to normal, and also allow's modders to see what those values are.
=> Reset's SetGridMenuSize on joining any gamemode

Entities/Common/Controls/StandardControls.as
READY
Camera now have more zoom levels to switch to, making it easier to set to a mode you are more comfortable with depending on your monitor/screen resolution.
OBS: Now using Clamp instead of the manual if/else chains. Also tweaked the zoom speed and tap time to better suit the changes. The new zoom levels should not have much effect on pixel scaling quality, as perfect 16-32 multiples were used.
Simply fetch the PR's changes, launch the game and use your mouse's scroll to see the new zoom levels.
=> Add more zoom levels to the camera

Entities/Common/Scripts/GenericButtonCommon.as
Fixes a bug where the nursery will get a null error after making a seed
Found by this user:
https://forum.thd.vg/threads/nursery-bug.28389/#post-411262
=> [fix] Null fix with nursery

Rules/CTF/Scripts/CTF_Trading.as
- **READY**
This PR resolves the issue stated in #605.
You no longer lose additional coins (for TK) after killing yourself.
- Host a server or runlocalhost.
- get some coins (!coins).
- Kill yourself with a keg.
- You only lose coins for dying, no additional 50 coins for teamkilling.
=> [modified] killing yourself no longer reduces additional coins for TeamKilling.

Rules/CTF/Scripts/CTF_GiveSpawnItems.as
**READY**: this PR is (to the best of your knowledge) ready to be incorporated into the game.
Currently, when CTF is nextmapped, if the game has been going on for less than a certain amount of time, the resupply doesn't give mats until the second resupply time.
Additionally, the resupply text doesn't appear at first.
These changes address both of these issues.
1. Start CTF
2. Switch to builder
3. Get resupply
4. Nextmap
5. Assert that resupply mats are in your inventory after nextmap and resupply text appears.
=> CTF resupply works properly on nextmap

Entities/Structures/Common/FallOnNoSupport.as
No longer uses onTick. Uses a new engine hook (requires Engine PR) to move it into an Event, saving server performance.
This effects ladders, shops, doors, platforms and mechanisms
=> Optmized FallOnNoSupport

Entities/Industry/Saw/Saw.as
Fixed the bug where mat_wood appears below 1 layer of tiles when logs or crates are converted to mat_wood by the saw. I have only tested the change with logs, not crates.
=> Fixed Saw-mat_wood bug

Entities/Common/Controls/StandardPickup.as, Entities/Common/GUI/WheelMenuCommon.as
PR to implement: https://github.com/transhumandesign/kag-base/issues/613
This implements a wheel menu for picking up nearby items, that will be less ambiguous. The PR also includes fixes for all pickup that should hopefully make it less frustrating.
A few things need to be finalized:
~~* What items should be on the wheel.~~
~~* If any items on the wheel should be combined (bomb/water bomb, special arrows, etc.)~~
~~* Where on the wheel the items should be~~
Bugfixes:
~~* Doesn't quite work on dedicated servers because of not syncing shift button~~
~~* funkyness with press c then shift~~
=> Pickup menu

Entities/Characters/Builder/Builder.cfg, Entities/Characters/Builder/BuilderInventory.as, Entities/Characters/Builder/CommonBuilderBlocks.as, Entities/Common/Emotes/EmoteHotkeys.as, Rules/CTF/gamemode.cfg, Rules/Challenge/gamemode.cfg, Rules/CommonScripts/BindingsMenu.as, Rules/CommonScripts/BuilderBinderMenu.as, Rules/Sandbox/gamemode.cfg, Rules/SmallCTF/gamemode.cfg, Rules/TDM/gamemode.cfg, Rules/WAR/gamemode.cfg
Implements: https://github.com/transhumandesign/kag-base/issues/622
* Allows builders to switch blocks using `shift + (1-9)` key.
* Adds a binding menu like the emotes binding menu but for blocks.
=> Block binding UI

Entities/Common/Includes/Requirements.as, Entities/Industry/CTFShops/BuilderShop/BuilderShop.as, Entities/Industry/Drill/Drill.as
**What has changed**
- Drill UI is no longer blurry when moving apart of #757 
- Drill can no longer be used until the game has lasted more then 4 mins
- Drill now freely follow's your mouse, instead of being locked at 45 degrees near your mouse
- Drills deal half damage to shielded people
**Why did you change x**
Drills can no longer be used until game reaches 4 mins to help prevent flag rush early game, which most people agree on is not fun what so ever.
Drill follows your mouse instead of being at a 45 degree angle near your mouse because it use to lead to issues where you would dig a tile, but would do no damamge. This lets you move it freely, and just feels much better.
Drill now deals half damage to shielded people. This might change if people would rather have something different …
=> Drill changes part2

Rules/CommonScripts/accolade_data.cfg
Bump Nevrotik head timestamp to 01/03/2020 to match approximate possible release date
=> Bumped Nevrotik custom head start timestamp to 2020-03-01

Rules/CTF/gamemode.cfg, Rules/CTF/mapcycle.cfg, Rules/CommonScripts/ChatCommands.as, Rules/CommonScripts/DefaultVotes.as, Rules/CommonScripts/MapVotesCommon.as, Rules/CommonScripts/PostGameMapVotes.as, Rules/CommonScripts/Spectator.as, Rules/WAR/gamemode.cfg
Status
this PR is (to the best of your knowledge) ready to be incorporated into the game.
Description
Adds a map vote during GameOver time. Maps are randomly chosen from the current gamemodes mapcycle.cfg. Currently only added to CTF and TTH, though any mode can have a map vote by adding 'PostGameMapVotes.as' to the gamemode.cfg, replacing 'RestartAfterShortPostGame.as'.
Additionally I have added one chat command !endgame which will put the game into the gameover state (only for admins), also any nextmap votes that pass will put the game into the gameover state.
Map votes will tally up how may times a map has been voted for and be saved out to the cache each vote.
Steps to Test or Reproduce
Start either CTF or TTH and end the game using !endgame, winning the game, or passing a nextmap …
=> End Game Map Votes

Entities/Characters/Builder/BuilderInventory.as, Entities/Characters/Knight/KnightLogic.as, Entities/Meta/CTFMusic.as, Entities/Natural/Trees/TreeSync.as, Entities/Structures/Ladder/Ladder.as, Rules/CommonScripts/ChatCommands.as, Rules/CommonScripts/CinematicCommon.as
This bug happens on multiplayer only, where the hitbox would not grow what so ever for new trees that had to grow.
The current changes are as follows;
- Before we grow, we grab all hitboxes we in our sector
- Grab each one and check that we own it
- Do what we were doing before
Using get and set with sync did not fix this issue, so i decided to fix some engine side bugs and do it like this.
In rare cases where the config has not updated with the game, we force it to return false & try save the working config. The null error it self happens when you try to call an none existing "cinematic_enabled" key.
Nothing to say really, just fixing 2 errors that happened
I'll look into adding this back in the future, but because hasMenus() does not sync, and syncing it from client to server results in …
=> [Fixes/WIP] Fixes errors contained in current test build

Rules/CommonScripts/ChatCommands.as, Rules/Sandbox/Scripts/Sandbox_Rules.as
This PR changes sandbox, mostly aiming to fix issues that ive seen while playing on sandbox.
~ All chat commands are re-enabled by default
~ Command blacklist now in place
~ Command chat delay has been added (3 seconds by default)
~ Admins ignore chat delay & blacklist
~ Server will auto remove kegs/mines when 20+ are in the server
~ Added coin command that accepts coin amount
All chat commands have been re-enabled because just having access to stone and wood was pretty boring
Blacklist is in place to stop people being annoying, by spawning in 50 necromancers and so on, along with this we can disable things that can be used to crash/harm the server
Current list includes;
- Necromancer 
- Greg
- Bison
- Shark
- Hall
- CTF_flag
- flag_base
Chat commands have a delay of 3 seconds. This means …
=> [Changes] Sandbox changes

Entities/Common/Controls/StandardPickup.as, Entities/Common/GUI/WheelMenuCommon.as
This introduces a `PickupWheelOption` class that is used to represent simple priorities for picking up blobs using the pickup wheel (shift+C). If an item of higher priority can be picked over another, then it will be chosen.
e.g. lit bombs have a 1 priority whereas the bomb material has a 0 priority. If both a lit bomb and a bomb material can be picked up it will now prefer the lit bomb because it has a higher priority; regardless of how close it is.
=> shift+c pickup wheel would prioritize closer bomb materials over lit bombs

Entities/Characters/Builder/BuilderInventory.as
Title, fixes an issue with verra's block ui where if you had no resources, and tried to make a mat, all players would get that no resource sound effect.
=> [Fix] No resource sound spam fix (Test build)

Rules/TDM/Scripts/TDM_Trading.as, Rules/TDM/tdm_vars.cfg
`maxCoinsOnRestart` can be specified as negative to disable the max coin cap, and it is now the default option in vanilla TDM.
=> Remove TDM coin cap

Rules/CommonScripts/MapVotesCommon.as
No idea why it even works right now but this solves the issue. `interpolated_water_backwall{,_edge}` is not declared in the `map_colors` namespace but in the `colors` enum
=> Typo in MapVotesCommon.as that fails to compile on newer AS

Rules/CommonScripts/ScoreboardRender.as
Bug with CPlayer, on localhost, getLocalPlayer().set_int, strign etc would save, but on dedicated servers, this does not work, the value is always 0/default.
Moved to CRules to prevent this, along with adding "client_" to all set names.
=> [Fix] Scoreboard right click text not showing

Entities/Characters/Archer/ArcherLogic.as, Entities/Characters/Scripts/RunnerDrowning.as, Entities/Special/CTF/FlagBase.as
I found this while messing with sync engine side
CTF flags sync every tick * per flag in map "flag missing"
Archers always sync their bool hasarrows, when we only need to sync it when it swaps. This is also per player.
Each player also syncs air_count every few ticks, which once again is not needed unless aircount is changing. 
This PR means they don't sync until its required. This should save network resources, not like it’s very resource intensive anyway.
=> [Fix] Only sync when needed

Entities/Characters/Scripts/RunnerDrowning.as
Water sounds would only play localhost, this is because the sounds were hidden in some isServer() block.
This fixes that, we check if we are a client, and run the sounds depending on the value the server syncs and if we are in water or not.
=> [Fix] Water sounds now play client side

Entities/Common/Building/BlobPlacement.as, Entities/Common/Scripts/HasDamageOwner.as, Entities/Structures/Spikes/Spikes.cfg
Marks the spikes block with a special tag to allow the blob placement script to assign the player placing the block as it's owner. It was previously hardcoded for the spikes only.
This small script can be used to add the same functionality to custom blocks.
=> Replaced hardcoded spike kills with a special tag

Entities/Common/Controls/StandardPickup.as
Added an entry for filled buckets to the pickup wheel. I used the filled bucket sprite for this.
- Spawn bucket
- Shift-C for pickup wheel
- Select bucket to pick it up
=> Add bucket entry to pickup wheel

Entities/Common/Controls/StandardPickup.as
Increased pickup priority for buckets containing water (non-empty). 
Until now they always seem to be tricky to pick up, which can be frustrating when something is on fire and time is of the essence. This PR, together with #845 will make this easier.
The actual priority factor can be tuned.
- Spawn both empty and filled buckets, on top of each other
- Try picking them up
- Notice filled buckets are much easier to pick up
=> Bucket pickup priority increased when not empty

Entities/Meta/CTFMusic.as
Fixing behavior outlined in #690, wherein a spectator's music would stop playing. As far as I can tell, this bug does not occur in TDM, and is unique to CTF. This particular solution fixes the issue by having the spectator's camera location serve as a stand-in for a player character's location, in determining which/when music should be played. 
- Join a CTF match
- Switch to spectating
- Navigate with camera and see if music still plays
=> [Fix] Music not playing for spectators in CTF 

Entities/Items/Bucket/Bucket.as
Allow refilling of buckets using water bombs. Related to #788. This implementation is very simple. As such, it allows an "unlimited" buckets to be filled with a single water bomb. No water quantity calculations etc are done, but I do not feel they are required. Currently the buckets are also filled fully (3 splashes). 
Thoughts?
- spawn empty bucket(s)
- buy water bomb, let it explode on the buckets
- buckets are now full of water
=> Refill bucket using water bomb

Entities/Common/Controls/StandardPickup.as
A tricky PR. This way picking up items will give a slight nudge towards bigger stacks of items (depending on the maxQuantity). This should be tested, maybe only applied to resources?
- Make a small and a large stack of resources
- Quick-tap pickup or Pickup-wheel
- Notice the larger stack gets priority
=> Consider quantities for pickup priority

Entities/Characters/Archer/ArcherLogic.as
It is already possible to grapple immediately after a legolas shot. But trying to grapple immediately after a normal shot does not work. This commit fixes that inconsistency.
- Start charging an arrow as archer.
- Shoot the arrow and immediately after try grappling.
- Notice that is works!
=> [modified] allow grappling right after firing

Entities/Industry/CTFShops/Quarry/Quarry.cfg, Entities/Industry/CTFShops/Storage/Storage.cfg, Entities/Industry/Tunnel/Tunnel.cfg
Removed isFlammable from storage, tunnels and quarries. See #829.
=> [modified] make storage, tunnels and quarries non-flammable

Entities/Common/Building/PlacementCommon.as, Entities/Natural/Seed/Seed.as, Entities/Natural/Seed/Seed.cfg
Placement of seeds now only allowed on tiles where seeds can actually grow.
Seeds should have improved physics, which means they will fall down when their support is lost.
This should also fix issue #606.
Try and fail planting seeds on stone, wood, platforms, shop etc.
Plant a seed on ground tile (only place you can put them now), then dig out that tile and the seed will drop down (with a slight delay).
=> [modified] prevent placement of seeds on non-growing tiles. Seeds fall down when losing supporting tile

Entities/Common/Fabric/Wooden.as
Wooden gibs seem to spawn slightly offset to the left.
Spawn a bunch of buckets, notice that more gibs end up going to the left than right.
=> [fix] wooden gibs from self-hits (e.g. decay) should not spawn slightly towards more to the left

Entities/Vehicles/Common/BoatCommon.as
Fixes #591: boats should only show splash when in water.
=> [fixed] show boat splash only when in water

Entities/Special/CTF/CTF_Flag.as
Should have been in previous PR #859. Now yellow `<` en `<<<` indicators are vertically aligned properly.
=> Move yellow flag indicators 1 pixel up

Entities/Common/FireScripts/IsFlammable.as
This fixes fire arrows setting siege on fire only some of the time. I am unsure if my fix will cause any unintended side effects.
Resolves #875 
Shoot an enemy siege with a fire arrow
=> Fixed fire arrows setting siege on fire inconsistently

Rules/CommonScripts/ScoreboardRender.as
Usernames are now copied on click.
Resolves #871 
1. Open scoreboard
2. Drag over players on scoreboard while right clicking
=> Fix scoreboard username copying while dragging mouse

Entities/Vehicles/Common/FakeBoatCollision.as
READY: this PR is (to the best of your knowledge) ready to be incorporated into the game.
Description
Fixes collison with enemy boats, I guess no one really care about this one anyway.
Steps to Test or Reproduce
one person on server (or localhost):
1.Ram enemy dinghy with longboat without code change, to see that you are unable to brake it*
2.Ram enemy dinghy with longboat with code change, to see that you are able to brake it*
(why dinghy? because one player in longboat can't generate enough speed to "hurt" other boats. )
This change will affect following vehicles in kag: dinghy, longboat, warboat.
=> Boats collision fix

Rules/CTF/Scripts/CTF_GiveSpawnItems.as
This doubles the frequency of checks at shops and tent for whether resupplies should be given to a player. It should make resupplies feel a lot more snappy, and remove some cases where your character walks over a shop but does not receive a resupply.
Walk over a shop and notice that you get given your resupply mats faster than usual.
Affected:
- Tent
- Builder shop
- Knight shop (if it actually gave any mats)
- Archer shop
=> Double the frequency of resupply checks

Entities/Characters/Builder/BuilderAutoPickup.as
BuilderAutoPickup.as used an incorrect expression for SetDamageOwnerPlayer on line 88: blob.getPlayer() instead this.getPlayer(); "this" is the builder, and "blob" is the mat_wood/mat_stone or whatever; that means blob.getPlayer() is always null.
Changing this allows builders to immediately autopickup mats that other people drop when they switch off builder (after building time ends, if they resupply for you at tent every time they respawn, etc.) by simply walking over the mats.
The one downside of this is that because the bug that makes people drop their 300 wood + 100 stone sometimes on nextmap still exists in vanilla (it's fixed on captains), this change might make picking up your own mats …
=> BuilderAutoPickup.as bugfix

Rules/CommonScripts/ScoreboardRender.as
It's about time this was fixed!
1. Be good at tournaments
2. Open scoreboard
=> Fixed accolades overlapping username

Entities/Structures/Spikes/Spikes.as
Spikes now calculate damage dealt using velocity length rather than using only y velocity.
1. Drop a spike on a trampoline
2. Get hit by the spike in any direction
3. Notice how the damage is consistent between directions
This exact code has been used in OCE Gather and has worked perfectly.
=> Spike damage is based on velocity in any direction

Entities/Characters/Knight/KnightLogic.as
Without this, you are able to immediately slash when exiting a siege.
1. Charge a slash
2. Release the slash
3. Immediately sit in a siege
4. Get out of the siege
=> Fixed knight slash not being reset when sitting on a siege

Entities/Characters/Builder/BuilderAnim.as
The inline comment sums it up
Partially fixes #776 
<details>
<summary>Screenshots</summary>
</details>
1. Open sandbox
2. Enable smooth shader
3. Chop tree
=> Improved blob highlighting while smooth shader is enabled

Entities/Common/Scripts/TeamIconToken.as
This would cause issues on staging because of the different AS version. It looks like the vanilla version of KAG has an AS version that incorrectly allows to use a namespace prefix for a function that is not located within a namespace.
This will be worked around in staging for the time being by declaring said functions inside of the `GUI::` namespace as part of the `g_allowdeprecated` retrocompatibility set for now.
=> Fixed incorrect GUI:: namespace for AddIconToken

Entities/Characters/Knight/KnightLogic.as
This prevents the bug where a lot of wood spawns out of nowhere.
An engine side fix is also on its way to include a warning on what file is causing this to happen.
Log from test server with engine side patch
```
(ignore the broken name below)
[15:07:43] ﾰ-!_￙-!_ￚ-!_ called server_SetQuantity with value -5, please make sure its within 0 and 65535.
Value has been set to 0.
[15:07:43] 
[15:07:43] 
[15:07:43] PRINTING SCRIPT EXECUTION TRACE
[15:07:43] Tip: You can fetch callstack and scriptstack info from string[]@ getCallStack() and string[]@ getScriptStack().
[15:07:43] 
[15:07:43] Callstack for current script: knightlogic
[15:07:43] #1: void DoAttack(CBlob@ this, float damage, float aimangle, float arcdegrees, uint8 type, int deltaInt, KnightInfo@ info)
[15:07:43] #2: bool …
```
=> [Fix] Added cap on knightlogic set quantity to stop underflows

Entities/Common/Loot/LootCommon.as
Removes mat_gold dropping from chests, which is unbalanced because it can lead to one team having more gold than the other due to RNG on maps with sparse gold.
=> Remove random gold drop from chests

Entities/Characters/Knight/KnightCommon.as
This is a common error in a lot of mods that edit KnightLogic.as without also replacing KnightCommon.as
Just by adding these 2 var's, it fixes issues with a lot of older mods, without breaking anything vanilla side.
The question is, should we even consider doing stuff like this for mod compatibility.
```
---- KnightCommon.as ----
//// OLD MOD COMPATIBILITY ////
// These have no purpose in the current code base other then
// to allow old mods to still run without needing manual fixing
const u8 shieldTimer = 0;
const f32 resheath_time = 2.0f;
```
=> [Change] Added some basic mod compatibility 

Entities/Characters/MovementScripts/RunnerMovement.as
User logs:
```
[22:38:28] Loaded texture: C:/Program Files (x86)/Steam/steamapps/common/King Arthur's Gold/Base/Entities/Characters/Knight/KnightGibs.png
[22:38:30] Script: Exception occurred while executing 'Entities/Characters/MovementScripts/RunnerMovement.as'; Line 802 Column 5; in function: bool checkForSolidMapBlob(CMap@ map, Vec2f pos, CBlob@ blob = null)
Null pointer access
[22:38:30] 
[22:38:30] 
[22:38:30] PRINTING SCRIPT EXECUTION TRACE
[22:38:30] Tip: You can fetch callstack and scriptstack info from string[]@ getCallStack() and string[]@ getScriptStack().
[22:38:30] 
[22:38:30] Callstack for current script: runnermovement
[22:38:30] #1: bool checkForSolidMapBlob(CMap@ map, Vec2f pos, CBlob@ blob = null)
[22:38:30] #2: bool canVault(CBlob@ blob, CMap@ map, float movingside) …
```
=> [Fix] Null fix that occours on join

Rules/CommonScripts/ScoreboardRender.as
Title, caused by ``mouseWasPressed2 = controls.mousePressed2;`` happening at the end of drawScoreboard which is called for each team segment on the scoreboard. 
Moving to onRenderScoreboard fixes this
=> [Fix] Fixes clients being unable to copy other teams username

Entities/Structures/Door/SwingDoor.as
- Fixes a bug where doors wouldn't show destruction visuals after being open and closed after a previous bomb impact.
- Resolves #881
1. Build a door.
2. Throw a bomb to the door.
=> [fixed] Fixed doors not showing destruction visuals after bomb damage

Entities/Characters/Archer/ArcherLogic.as
- Fixes a bug where archer could bow charge even after all arrows were throw away.
- Resolves #925
1. Start bow charge.
2. Drop all arrows.
3. Bow charge is cancelled.
Before:
After:
=> [fixed] Fixed a bug where bow could charge even after all arrows were throw away

Entities/Characters/Archer/ArcherLogic.as, Entities/Industry/CTFShops/Quarters/Quarters.as, Entities/Industry/Tunnel/TunnelTravel.as
* Fixed being able to sleep in quarters while attached.
* This fixes being able to drive a siege while sleeping in a quarters by sitting on the siege right before sleeping.
* Fixed travelling through tunnels while attached.
* This fixes siege teleporting with you if you hop on it right before teleporting.
* Fixed archer grapple staying extended while attached.
* This fixes being able to grapple right after sitting on a siege, and the grapple stays extended as you drive the siege.
Resolves #599 
* Press down to sit in a siege right before attempting to sleep in a quarters.
* Press down to sit in a siege right before attempting to travel through the tunnel.
* Press down to sit in a siege right …
=> Fixed several attachment bugs

Entities/Special/CTF/FlagBase.as
This clears the flag of blocks when the flag's build sector is added.
My method:
1. Using code, set the corner tiles of the flag's build sector to any block before the code in this PR
2. Load any CTF map to see that these blocks were removed
Alternative method:
1. Make a CTF map with blocks inside the flag
2. Load the map
=> Fixed kaggen sometimes generating blocks inside flag

Entities/Characters/Archer/ArcherAnim.as, Entities/Characters/Archer/ArcherLogic.as, Entities/Items/Projectiles/Arrow.as, Entities/Items/Projectiles/Arrow.cfg
Improves archer aiming and arrow bbox. Will make it easier to shoot through gaps, and will be less confusing for (new) players.
- moved archer bow 2px up to align with arrow spawn. This was originally chosen to make it easy to shoot over level blocks, now the bow should be on the same level.
- align *arrow spawn* better when aiming up/down. The bow animation is out-of-center horizontally. This is most notabily when aiming up and down
- arrow bbox now rectangle to fit better in between blocks
Mostly try shooting in between small gaps. The arrow on the bow animation should be a better indicator if you can shoot through. Water arrows should still stun behind 2 layer walls.
=> Tweaking archer aiming and arrow bbox

Entities/Common/GUI/ActorHUDStartPos.as, Entities/Common/GUI/DefaultActorHUD.as
The staging build allows changing the resolution/window size on the fly.  
`HUD_X` and `HUD_Y` were storing the screen size on compile time in a global variable without ever refreshing it. This would cause the HUD to not update its position when resizing the window.
Resize windows on staging. This does not affect vanilla.
=> [fixed] staging build: changing resolution would not update hud

Entities/Common/Factory/Shop.as, Entities/Common/Respawning/StandardRespawnCommand.as, Entities/Industry/Hall/Hall.as, Entities/Special/Tent/TentLogic.as, Entities/Vehicles/Ballista/Ballista.as, Entities/Vehicles/Boats/WarBoat/WarBoat.as
Title, cmd would result in a delay depending on your ping. I updated the engine to include new binds for CreateGenericButton to have an option for a function callback, so if we do have any client only code we want to call, we can use that.
I tested using clumsy, your ping no longer makes a difference on how fast the gui's appear.
Requires engine pr to be merged to work
```
New funcdef: void CallbackButtonFunc(CBlob@, CBlob@)
New script binds:
CButton@ CreateGenericButton( int _frameNum, Vec2f _offset, CBlob@ attached, CallbackButtonFunc@ cb, const string &in )
CButton@ CreateGenericButton( const string &in iconName, Vec2f _offset, CBlob@ attached, CallbackButtonFunc@ cb, const string &in )
```
Fixes #612
=> [Change] Client side gui no longer use cmd

Entities/Common/Controls/StandardPickup.as
Status:
- **READY**  -- I have tested this branch local only
Partially resolves [Issue #972: Revert all recent pickup changes](https://github.com/transhumandesign/kag-base/issues/972)
---
[This commit from the halloween update](https://github.com/transhumandesign/kag-base/commit/eee806be1ebac365c10f9c6d4ea6240df6cf980f) added the feature that you can pickup items through platforms. It also added a bug where:
-  Trying to pickup an item right after throwing it would often fail.
-  Trying to pickup chickens, crates became harder, you would need to overlap the chicken/crate in order to pick it up.
The bug is caused by `if(map.getHitInfosFromRay(pos, -ray.getAngle(), ray.Length(), this, hitInfos))` (line 560) failing (and returning false and not filling the hitInfos array with anything). The …
=> Revert pickup behaviour to pre-halloween.

Entities/Industry/CTFShops/BoatShop/BoatShop.as
The boatshop currently doesn't display the right image when selecting the warboat, this change the longboat image to the warboat image
build a boatshop, notice that the warboat image is actually a warboat image
=> fixed image in boatshop where it displayed a longboat image instead of a warboat

Rules/CommonScripts/KillMessages.as
Kill message Icons are colored depending on attacker
**READY**
Ever since kill messages were added there has been kill icons. Some of these icons are sprited to be able to change team, but this was never added and those icons always look like they are from blue team no matter what team the attacker is. This PR changes that, so the attacker's team will likewise go onto the kill icon as well. 
Thanks to @Betelgeuse0
Simply kill another player from a different team.
=> Team Colored Kill Icons

Rules/CommonScripts/ScoreboardRender.as
bunnie_the is no more, long live bunnie_the-End!
We assumed CMap@ getMapName() would always finish with a file extension, however this is not the case. It can have no extension if a map in mapcycle.cfg doesnt include a .png at the end.
=> [Fix] Correctly removes file extension if mapcycle doesnt include .png

Entities/Structures/Door/SwingDoor.as
Title, slight improvement to performance with doors (more so when there's a lot of blobs)
=> [Fix] Stop looping when doors are opened

Entities/Characters/Knight/KnightLogic.as
* Fixes the issue where you need to press space twice to light a bomb in some situations
* Resolves #879
1. Have a regular bomb and a water bomb in your inventory (or any two different bomb types)
2. Select the water bomb
3. Throw the water bomb item on the ground (don't light the bomb)
4. **Old behaviour:**  The water bomb remains selected. Attempting to light a bomb switches to the regular bomb but doesn't light it. You need to press space a second time to light the regular bomb.
**New behaviour:** The regular bomb is immediately switched to. Pressing space once lights the regular bomb.
=> Fixed issues with bomb selection

Entities/Industry/CTFShops/Quarry/Quarry.as, Rules/CTF/Scripts/CTF.as, Rules/CTF/gamemode.cfg, Rules/CommonScripts/ResetQuarry.as, Rules/SmallCTF/gamemode.cfg
1. Starting output slightly increased (75 => 80)
2. Output decreases by 2 each time stone is dropped, until it reaches 30. Because stone drops are rounded to 5, it should drop same amount of stone 2-3 times before going down by 5
3. Same amount of wood is consumed for all outputs
4. Breaking the quarry doesn't reset it's output
5. Output resets on map change/restart
=> Quarry becomes less efficient each time it drops mats

Entities/Vehicles/Catapult/Catapult.as, Entities/Vehicles/Common/VehicleCommon.as
Now the charge is reset when the gunner leaves mid charge. The catapult arm correctly retracts as well.
1. Sit in gunner seat of siege
2. Hold left click to charge
3. Press up to leave mid charge
=> Siege no longer shoots if gunner leaves while charging

Entities/Characters/Archer/ArcherAnim.as
**READY**
When shooting arrows, the arrows appear behind the player's head- which looks odd if you notice. Probably unintentional so it is fixed in this request.
_Before:_
_After:_
Simply shoot some arrows and look in awe of how much better the animation looks!
=> Firing arrows is visually better

Entities/Common/Building/BlobPlacement.as
The shift key is whatever `AK_BUILD_MODIFIER` is bound to.
Resolves #983
Hold shift and press space while holding a block that can be rotated.
=> Shift + Space to rotate blocks the opposite direction

Entities/Characters/Archer/ArcherHUD.as, Entities/Characters/Archer/ArcherLogic.as, Entities/Characters/Knight/KnightHUD.as, Entities/Common/Respawning/StandardRespawnCommand.as, Entities/Special/TDM/TDM_Ruins/TDM_Ruins.as
- **READY**
Lets several icons use team colors to change their coloration. Class hud icons, class change icons, and archer arrow buttons are affected which weren't previously.
_some examples_
Play as an archer/knight on a team other than team 0 to see the new colors.
=> Team icons

Entities/Characters/Knight/KnightLogic.as
**READY**
Previously, when a knight hit dirt stone or dirt thick stone, it would not drop any of the stone mats. This PR make it so that when a knight damage a dirt stone or dirt thick stone, 4 or 6 stone mats are dropped at the feet of the knight.
Go knight, hit dirt stone, notice that 4 stone dropped at your feet.
Go knight, hit dirt thick stone, notice that 6 stone dropped at your feet.
=> damaging stone and thick stone drop stone at feet like gold does

Rules/CommonScripts/CoreHooks.as, Rules/CommonScripts/PatronSupport.as, Rules/CommonScripts/SwitchFromSpec.as, Rules/CommonScripts/TeamMenu.as
ENGINE PR IS NEEDED FOR THIS TO WORK
Add's spectator slots, the server api/browser already supports this, so there isnt much work that needs to go in there.
Autoconfig settings:
``sv_spectatorslots``, default value is 4
Binds:
``getPlayersCount_NotSpectator()``, ``getNet().joined_maxplayers``, ``getNet().joined_spectatorslots``, ``getNet().joined_reservedslots``
What does this do:
```
- Players who join will get forced to team 200 (spectator team) if game is full
- Patreons who join will be put into a team AS LONG AS there are enough patreon slots (2 by default)
- People with reserved slots will be put into a team if there's a spare slot, otherwise they will become a spectator
- People with joinfull access will be put into a team no matter what
```
=> [Addition] Spectator support

Entities/Items/Crate/Crate.as
Code is probably bad, please review uwu
- Crates are now boobytrapped if they have an enemy mine and you try to get in; the mine instakills you. Previously only opening inventory was boobytrapped (the mine goes up and instantly activates on inventory open, you can avoid it).
- Pressing space with crate in hand no longer dumps mines (previously it was only players)
=> Crate changes: pressing space with mines inside, boobytrap when trying to get in with enemy mines

Rules/CTF/gamemode.cfg, Rules/Challenge/gamemode.cfg, Rules/CommonScripts/PropagateBans.as, Rules/Sandbox/gamemode.cfg, Rules/SmallCTF/gamemode.cfg, Rules/TDM/gamemode.cfg, Rules/WAR/gamemode.cfg
Bans and unbans are sent out via TCPR to an [external program](https://github.com/eps0003/kag-propagate-bans) that propagates them to all other connected servers. The goal is for this to be used for all official servers.
Demonstration:
https://user-images.githubusercontent.com/30195802/110904625-671bbb80-835d-11eb-89bf-beaab49151a9.mp4
1. Run two or more servers
2. Compile and run the program with the info of each server
3. Ban/unban someone on one of the servers
=> Propagate bans

Rules/CommonScripts/RegrowPlants.as
(pick one)
next_check_time was being set to gametime, so in next matches it didnt work until the match time reached the gametime it was last set at
=> Fix RegrowPlants not working

Entities/Characters/Builder/BuilderHittable.as
Adding ladders to the list of "urgent" targets makes hitting them work the same for both teams: you can consistently target enemy ladders inside blocks and hit enemy ladders without overlapping them (like you already can do both with ladders of your own team).
=> Ladder targeting is consistent between teams

Entities/Vehicles/Ballista/Ballista.as
Class swap buttons were disabled in the main branch when a spawn point was near a given ballista. This seems to be too aggressive at the moment so let's remove that for now, shouldn't be a big deal.
=> [fixed] workaround for class swap button disappearing on closeby ballis

Entities/Items/Crate/Crate.as
Crates wouldn't collide with each other in the current main branch.
=> [fixed] crates should collide with each other

Entities/Common/Building/GoldBuilding.as
(pick one)
- **AMOGUS**: this PR is (to the best of your knowledge) ready to be incorporated into the game.
This fixes the issue where you could get infinite gold in TTH due to ballistas dropping gold on death even when not costing gold.
=> ballista tth infinite gold exploit fix

Entities/Industry/CTFShops/Quarry/Quarry.as
Title. Initial output would get set only if current output was -1, which was only possible if gamemode had ResetQuarry.as, otherwise current output vars would not exist. Fixed by allowing quarry to set initial output vars if they don't exist yet
=> quarry works on gamemodes that don't have ResetQuarry.as

Entities/Vehicles/Common/VehicleGUI.as
Fixes divide-by-zero error in VehicleGUI.as and therefore allows non-default vehicles to use instant-fire ammo (that is, ammo with max_charge_time = 0).
When you add a custom vehicle without charge delay it crashes when trying to fire because of progressbar percent division. The original code worked for mounted bow because it was explicitly excluded.
=> Fix divide-by-zero in VehicleGUI when max_charge_time is zero

Entities/Items/Sponge/SpongeDryInAir.as
Fixes issue #1050, sponges no longer dry underwater, only when in air
Toss one sponge underwater and one on dry ground
The sponge on dry ground will dry, the one underwater will not
=> Sponges no longer dry underwater

Entities/Characters/Builder/CommonBuilderBlocks.as
Magazine requires 20 stone but when you hover over it in build menu it shows that it needs 20 wood. This pr makes it show 20 stone as cost in build menu.
Image showing changes:
=> Fix magazine requirements

Entities/Characters/Knight/KnightLogic.as
Simple fix that just prevents the client from lighting a bomb from the player's inventory if they are holding something. However, the client now needs to wait for the round trip to the server and back before they can throw the bomb. Ideally, the client should tell the server to try to light or throw a bomb and the server decides, but that would require a bit of refactoring. At least this is an improvement from before.
Resolves #1037.
1. Run and join a dedicated server
2. Run [clumsy](https://jagt.github.io/clumsy/) with 200ms lag
3. Attempt to light two bombs in quick succession
=> Improved lighting bombs with bad ping

Entities/Natural/Trees/TreeSync.as
This happens when a tree is covered by a tile. This does not happen often in vanilla (but has done in the past), but mostly happens on modded servers. When a client joins the game, they get stuck in a while loop trying to call DoGrow, except it wont work because the tree refuses to grow due to the tile blocking it. 
Client will attempt to call do grow a finite amount of times before stopping. Ideally we add some custom logic in DoGrow for when your client is joining to ignore tiles, but for such a rare edge case I feel like this is fitting enough.
=> [fix] Game freezing while trying to join a server

Entities/Structures/Door/SwingDoor.as
Fixed door closing animation.
When a door closes, it will play the following frames: 2 -> 1 -> 0. 0 being the frame of an undamaged closed door.
When a door takes damage (frame 4 to 6, 6 being the final frame before the door is destroyed), the animation is supposed to change to: 2 -> 1 -> 4(/5/6). Currently, rather than replacing the final door frame, it will only add frames to the animation. Right now on production a fully damaged door closing will play the following animation: 2 -> 1 -> 0 -> 4 -> 5 -> 6.
After this PR, it will simply play 2 -> 1 -> 6 when the door is nearly destroyed.
Additionally, moved animation stuff to onHealthChange, as there is no reason to do this in onHit, this means …
=> [fixed] frames added to door animation unrestricted

Entities/Industry/CTFShops/BuilderShop/BuilderShop.as
This PR re-orders the builder shop, with the main goal of moving the drill from position 7 to 1. This lets you buy a drill with a much more comfortable hotkey (1 instead of 7). You can now press E → 1 → E → 1 on an empty shop to get a drill which is nice. The existing items in position 1 and 2 (lantern and empty bucket) are some of the least useful items in the game and so I think this makes sense. I've moved other items so that the layout of the shop still looks sensible - in particular filled bucket is kept on 3 to not break people's muscle memory.
Before:
After:
Enter sandbox and create a builder shop.
=> Reorder items in builder shop to put drill first

Entities/Characters/Archer/ArcherAnim.as, Entities/Characters/Knight/Knight.cfg, Entities/Common/FireScripts/FireAnim.as
- **READY**
I noticed visual bugs on each of the classes, which are:
- Knight sprite "blinks" when on fire.
- Builder plays the 'on_fire' animation even while dead.
- Archer's bow sprite "blinks" every time three arrows are charged.
- Archer's 'shiny' sprite is not properly placed or rotated around the bow.
This PR fixes these minor visual anomalies.
1) Set a knight on fire, look at the knight's body closely to see any blinks.
2) Set a builder on fire and let them die, check and see if the builder plays the on_fire animation while dead.
3) Become an archer and charge the bow till it hits three arrows, check for animation smoothness- and position of the 'shiny'.
##
Visuals for archer with fixes-
https://user-images.githubusercontent.com/68350259/143735108-3c0d868c-4aa2-4714-ac65-cdeb8b553c1 …
=> Improved classes animation

Entities/Items/Explosives/Keg.cfg
When builder hits an enemy Crate, Trampoline, Saw, etc. it's making a wooden sound per hit. However, hitting Keg didn't play any sound.
This adds Wooden.as to the scripts section in Keg.cfg, so Keg is making a wooden damage sound when it is hit by an enemy Builder or Knight, instead of getting knocked back and damaged without any noise.
=> Keg makes a sound when hit by Builder pickaxe or Knight jab

Entities/Industry/Drill/Drill.as
When the player is attached (sitting on a vehicle or animal) and is pressing Action1, drill would activate, destroying nearby blobs, scenery or walls. This happens only in online servers.
This PR will add an early return, so the drilling doesn't happen if the player is attached.
Go to online Sandbox EU.
Spawn a catapult and a drill.
Pick up the drill and sit in the catapult.
Hold Action1 while driving around.
Notice the drill will damage nearby platforms, trees, chickens, etc.
**After this change, not anymore.**
=> [fixed] Drill activating when player is attached in online server

Entities/Common/Movement/CheapFakeRolling.as, Entities/Common/Movement/FakeRolling.as
The existing way of calculating the angle to rotate the blob was completely wrong and increases rotation speed the larger the blob's radius is. The new equation corrects this by calculating the angle from the arc length of the circle defined by the blob's radius. Since the blob is rolling, the arc length is equal to the distance travelled.
Since bombs and mines relied on the existing faulty rotation calculation, I had to clamp the rotation speed to avoid blobs spinning way too fast. This can be thought of as the blob losing traction to the ground or it experiencing air resistance.
1. Spawn boulders, bombs and mines
2. Toss them around
This same equation was also used in my 3D mod and worked …
=> Fix fake rolling angle calculation

Entities/Common/Controls/StandardPickup.as
[fixed] Pick-up wheel not updating if letting go of "pickup key".
[fixed] that you could pick up Flowers.
[fixed] that you could pick up enemy items when you shouldn't be able to.
Fixed that the pick-up wheel (which appears when pressing **Pickup** and **Pickup Modifier**) didn't update buttons if you let go of **Pickup** while holding **Pickup Modifier**. The "is **Pickup** pressed" check has been removed.
Removed Flowers from list of blobs that are considered as pickable food items in the pick-up wheel.
In doing so, removed that flowers could be picked up by these methods:
a) if a food item was close while the flowers were the closest blob to the player.
b) by abusing the above mentioned bug …
=> [Fixed] Pick-Up Wheel not updating & "Picking up Flowers" bug

Rules/CommonScripts/VoteCommon.as, Rules/CommonScripts/VoteCore.as
**READY**: this PR is (to the best of your knowledge) ready to be incorporated into the game.
Resolves #837
- Stops the vote window from disappearing when you vote
- Allows admins to force votes they've already voted in
- Shows the amount of votes for and against in the vote window
- Removes "player voted for/against" chat spam (still shown for admins, devs, guards, and the server logs)
As an admin:
- Start a vote
- Vote normally for/against
- See that there's a chat message about your vote
- Force vote for/against
As a normal player:
- Start a vote
- Vote for something
- See that vote window shows your vote
- See that there's no chat message about your vote
- Try to make a second vote
- Click on the vote menu to make it disappear
=> Improve voting UI

Rules/CommonScripts/Spectator.as
Makes it so that you can move the spectator camera when voting for a new map in CTF. Resolves #1026
- Finish a CTF match
- Die or switch to spectator
- Vote for a map
- Move around as spectator
=> Allow moving spectator camera when voting for new map in CTF

Entities/Characters/Archer/ArcherLogic.as
Different (better? not hardcoded?) implementation of the same fix for PR #865 ("Abandoned").
This change should: 
* charge bow properly when out of normal arrows and picking up new ones (additional fix)
* fix cycling special arrow types after being out of other types
Fixes three issues:
1. Cycling from no-arrow to special-arrow type quickly now actually cycles, starts charging bow etc. Fixes #576.
2. While charging, cycling from no-arrow type to has-arrow type will cycle and start charging.
3. When having no arrows in inventory, while holding down the mouse, start charging the bow when picking up normal arrows.
* as archer get normal arrows and one special arrow 
* shoot a normal 
* drop the …
=> Fix arrow type cycling

Entities/Items/Projectiles/Arrow.as
This change makes fire arrows behave more like normal arrows, by first registering an arrow hit (so they will make a sound when hitting a knight's shield and allow stun when shooting fully charges) and then do the usual fire hit with, but with 0 initial damage, if not shielding.
I have also removed a redundant `damage = 0` for shield hits. This is already handled in `ShieldHit.as`, and seemed to not do much afaik.
Shoot a shielding knight with a fire arrow and notice the sound, and stun (for full charge), and no fire 
Shoot a non-shielding knight and notice the damage and fire 🔥, and possible stun
=> Make fire arrows hit like normal arrows, fix sound

Entities/Common/Emotes/EmoteBubble.as, Entities/Common/Emotes/EmotesCommon.as
Ignored players can currently still spam emotes. This commit also mutes emotes for these players. 
Should work for server-wide and client-only ignores, similar to how chat ignore works.
Intended behavior:
- client-only ignore player: no emotes will show from this ignored player for you, nobody else is affected.
- server-wide ignore player: no emotes will be shown to anybody, not even the ignored player themself
Note that a "Ignored emote" message is left in the code, but is not needed in case.
=> Also ignore emotes from ignored players

Entities/Common/HoverMessage/DrawHoverMessages.as
**Shows coin changes as part of the hover messages.**
This should be tested by more people as this could feel distracting, but in my testing hover messages are subtle enough that it is not an issue.
The fact it shows just next to materials makes it rather obvious what actions give you coins, such as building, fighting, and collecting coins - which is not necessarily obvious to a newbie since there is no other clear visual feedback, mind you. Plus it should help give some indication how much coins are actually earned.  
Since it aims towards fixing #1170, this should also help distinguishing coins and gold, because there has been various instances of newbies getting confused between the two. …
=> [added] hover message on coin count change next to materials

Entities/Common/Decaying/DecayQuantity.as, Entities/Common/Decaying/DecayUnused.as, Entities/Materials/Ammunition/MaterialArrow.as, Entities/Materials/Ammunition/MaterialBallistaBolt.as, Entities/Materials/Ammunition/MaterialBallistaBombBolt.as, Entities/Materials/Ammunition/MaterialBombArrow.as, Entities/Materials/Ammunition/MaterialFireArrow.as, Entities/Materials/Ammunition/MaterialWaterArrow.as, Entities/Materials/Construction/MaterialGold.as, Entities/Materials/Construction/MaterialStone.as, Entities/Materials/Construction/MaterialWood.as, Entities/Materials/Explosive/MaterialBomb.as, Entities/Materials/Explosive/MaterialWaterBomb.as, Rules/CTF/Scripts/CTF.as, Rules/Challenge/Scripts/Challenge.as, Rules/CommonScripts/ChatCommands.as, Rules/WAR/Scripts/WAR.as
This fixes issue #598.
Gold which is spawned into Sandbox would never despawn, since Gold doesn't have a 'decay step' set like the other materials do. Therefore, spamming !gold in Sandbox servers would be a griefing method, since nothing could be done to despawn the Gold.
This change adds a 'decay step' to Gold and DecayQuantity.as to its script section, so it will eventually decay over time.
Similar to Challenge.as, CTF.as and WAR.as will remove DecayQuantity for any gold blobs created so it won't decay in those game modes.
Although ChatCommands.as is getting refactored, I did change the existing ChatCommands.as just to be sure.  
`!gold` will spawn 50 gold instead of 200 and `!allmats` will …
=> Gold will decay over time (only in modes other than Challenge, CTF, TTH)

Entities/Characters/Knight/KnightLogic.as, Entities/Common/Throwing/ActivateHeldObject.as, Entities/Common/Throwing/ThrowCommon.as
Alternative to #1038 , which made it impossible to spam bombs if you had high ping (which caused many complaints)
Implements this comment:
"Instead of the client checking if it's holding something or needs to light a new bomb, the server should do that. Pretty much move all the checks the client is doing onto the server instead. The client just needs to blindly tell the server that they want to light/throw a bomb and the server acts on in."
Moved some code from ActivateHeldObject.as to ThrowCommon.as as well
Video - comparison between PR version and pre-Epsilon's PR bomb throwing.
https://www.youtube.com/watch?v=-4n0ouJ2m80
=> Better bomb throwing with ping

Entities/Items/Projectiles/Arrow.as
Fire Arrow had this behavior:
- If shot against friendly door or any component structure blob: Bounces off but sets it on fire after a while anyway.
- If shot against enemy door, any team bridge, platform: Sets it on fire and disappears immediately.
This PR changes the behavior to this:
- If shot against any structure blob regardless what team: Sets it on fire and sticks.
1. Build a friendly door or a wall made of Magazines. Shoot at it with a fire arrow. It will bounce off. **After this change it sticks.**
2. Build an enemy door, any team bridge or a platform. Shoot at it with a fire arrow. It will set it on fire and disappear. **After this change it keeps sticking.**
=> [Fixed] Fire Arrows ricocheting off structure blobs

Entities/Common/Attacks/Hitters.as, Entities/Common/Attacks/KnockBack.as, Entities/Common/FireScripts/FireCommon.as, Entities/Common/Includes/Costs.as, Entities/Common/Includes/SplashWater.as, Entities/Industry/CTFShops/CTFCosts.cfg, Entities/Materials/Ammunition/MaterialWaterArrow.as, Entities/Materials/Ammunition/MaterialWaterArrow.cfg
(pick one)
[changed] water arrows come in stack of 1 instead of 2
[changed] new cost of water arrow: 15 instead of 10
[added] knockback from water bombs and water arrows
[changed] splash from water buckets now does a bit of knockback
=> [CTF Rebuild] Water changes, water arrow nerf

Entities/Common/Scripts/OffscreenThrottle.as, Entities/Items/Lantern/Lantern.cfg, Entities/Items/Log/Log.cfg, Entities/Materials/MaterialStandard.as, Entities/Natural/Bushes/Bush.cfg, Entities/Structures/Door/StoneDoor.cfg, Entities/Structures/Door/SwingDoor.cfg, Entities/Structures/Platform/WoodenPlatform.cfg, Entities/Structures/Trap/TrapBlock.cfg
Staging exposes a `throttleInterval` field to `CBlob` which allows scripts to skip ticking of blobs entirely by only ticking every N ticks. It aims for maximal overhead reduction by cutting ticking much earlier than script ticking intervals would allow. The engine also attempts to spread out entity throttling in order to reduce tick time fluctuation.  
However, this remains largely experimental because skipping ticks on the client-side could have many unintended side effects. Currently, Staging uses that `throttleInterval` unconditionally but it may be disabled by default behind an `autoconfig.cfg` switch until this is largely proven to be stable.
I tested client-side throttling with a …
=> Script-side support for staging off-screen tick throttling

Entities/Items/Projectiles/Arrow.as
This fixes an issue with #1160 where the keg would often not lit up if the fire arrow was shot from a close enough distance. For some reason, the tag assignment was guarded by a `gametime % 6` condition on the arrow ticking, which was used to play some effects. Hence, the late tagging looks unintentional, and I have not found issues with this fix during my testing.
1. Go to sandbox (online or offline)
2. Switch to archer
3. Spawn a keg
4. Shoot a fire arrow at the keg. It should work even if you're basically overlapping the keg, and at short distances.
Without this workaround the arrow would miss most of the time which is largely undesirable.
=> Set the "fire source" tag as early as onInit for arrows

Entities/Common/Scripts/OffscreenThrottle.as
`isPointOnScreen(Vec2f, const float)` doesn't exist in vanilla, so scripts with offscreenthrottle.as were breaking
wrapping everything with #ifdef STAGING seems to fix it
=> [dev] fixed staging script breaking non-staging

Rules/CTF/Scripts/CTF.as, Rules/CTF/Scripts/CTF_GiveSpawnItems.as
Fixes the following issues with current base's state of resupplies (Rebuild version):
- knights and archers inbuild time receive mats in their inventories, newbies may not pay enough attention and give a shitton of mats to the enemy when they die (mats drop on ground now if you're not builder)
- archers at build time don't get arrows at all which is generally ok but it means they have to wait for the match start to get arrows at a resupply point (now you get arrows in build time too)
- if you afk as an archer at a resupply point your resupply counter gets reset and you hear the resupply sound even if you already have 30 arrows (no longer happens)
Moreover, everyone is now switched to builder …
=> Resupply improvements

Rules/CommonScripts/WaterDecaysDoors.as
Fixes #1288.
Doors and ladders that are loaded with the map wouldn't decay in water despite the gamemode having `WaterDecaysDoors.as` added to it. This PR will fix this so doors and ladders will decay in water normally.
The map loads before the scripts are loaded, so `WaterDecaysDoors.as` only accounted for newly added doors/ladders.
To account for pre-existing doors/ladders, a function `FetchExisting()` has been added to `onRestart()` which will fetch pre-existing doors/ladders.
A strings array `names_to_decay` has been added, so names "ladder" and "wooden_door" aren't hard-coded in several places.
Go to any gamemode that uses `WaterDecaysDoors.as`, e.g. the CTF Tutorial.
`/loadmap Juggernaut` …
=> [fixed] Pre-existing Doors and Ladders will now decay in water

Entities/Common/Help/DrawHelp.as, Entities/Common/Help/Help.as, Entities/Structures/Trampoline/Trampoline.cfg, Entities/Structures/Trampoline/TrampolineLogic.as
A few sentences describing the overall goals of the pull request's commits.
When held, trampoline freely rotates like drill.
Holding lmb makes it rotate in 45 degree steps, and holding rmb prevents it from rotating completely (allows players to throw tramps at any angles in different directions and place horizontal tramps more easily)
(same as https://github.com/transhumandesign/kag-base/pull/1074)
Help.as, DrawHelp.as changes:
Increased width of help pane by 33%
Now you can add things to the help system that are ALWAYS drawn (don't need f1 mode turned on for it)
Added trampoline controls explanation to it (TrampolineLogic.as onAttach, onDetach)
=>  Trampoline has 360 rotation + Help.as, DrawHelp.as minor changes

Entities/Natural/Animals/Chicken/Chicken.cfg, Rules/CommonScripts/RegrowPlants.as
(pick one)
[changed] chickens have more health 
[added] added natural chicken spawning with a limit of 10 chickens per map
=> [CTF Rebuild] Natural chicken spawning and chicken buff

Entities/Characters/Scripts/RunnerDeath.as, Entities/Structures/Platform/Bridge.as
A very simple change that allows dead enemy bodies to open team bridges. This can allow players to throw bodies onto enemy bridges in hopes of opening them underneath an enemy.
1. Place team bridges
2. Swap team
3. Spike yourself to death
4. Throw your dead corpse onto the bridges
=> Dead enemy bodies open team bridges

Entities/Industry/Drill/Drill.as
(pick one)
[change] receives slightly more heat from hitting tiles like dirt and ore
[change] receives less heat from hitting blobs like players or doors
[change] increased max heat
[change] slower cool down 
[change] water buckets now cool 50% of drill heat instead of 70%
[change] you can't pick up overheated drills anymore (previously you could and have them instantly drop to the ground]
[change] drills now ignore bushes
=> [CTF Rebuild] Drill balance changes

Entities/Items/Lantern/Lantern.as
This change makes it so that you cannot toggle the lantern on or off (= action 3) when it is in water.
Additionally, I set tickFrequency from 24 to 1, so the game checks if lantern is touching water much more reliably.
Since onTick() only checks for two bools, there should not be a drain on performance.
It is also possible to not set the tickFrequency, since the default seems to be 1.
It should be tested if the "lantern not getting extinguished" bug still happens in online servers with this change.
Hold a Lantern and stand in water. It will be extinguished by the water.
Press Action 3. Notice it will not turn light on anymore.
Throw a bunch of lanterns in water and notice they all get …
=> Cannot toggle lantern underwater, Lantern checks for water every tick

Rules/CTF/Scripts/CTF_Banners.as, Rules/CommonScripts/PostGameMapVotes.as
This PR fixes an exception that could happen when using chat command `!endgame` or when "Next map" vote passes, in a CTF server, with the newly introduced game state banners (See PR #1166 which introduced GameStateBanners.as and CTF_Banners.as).
Variable `banner_type` could become equal to the length of the `banners` array which causes an out of bounds exception.
I made it so it will return from the function if that's the case and when `banners[banner_type]` is about to be used.
Fixes #1343:
Previously, in a nutshell, `GameStateBanners.as` would set `rules.minimap = true` when a new map loads.
When the game finishes due to a team winning, the winning banner is shown and `rules.minimap = false` …
=> [fixed] Minimap on top of map voting window and exception in CTF when match ends via vote pass or chat command

Entities/Vehicles/Common/Vehicle.as
Fixes #1326.
In offline and online, you can hold an item, keep showing buttons, then throw the item away and press the "load item to catapult" button later to place the item in the catapult's mag, even from screen lengths away. This could possibly be exploited in a number of ways and have a lot of unintentional side-effects (see the linked issue for more information).
This change makes it so you can only load a blob to a catapult if it is attached to you (i.e. you are holding it).
I think this should render all of the described side-effects as fixed.
You can still load stone to catapult via button without holding the stone as usual.
Since buttons are removed when picking up an item, 
you could …
=> [fixed] Loading items you aren't holding in catapult

Entities/Materials/Construction/MaterialGold.cfg
Gold should decay in Sandbox as per PR #1276.
However, it wasn't working because it seems I didn't copy over the file `MaterialGold.cfg` by mistake.
So I'm fixing that here.
I tested in Sandbox offline, Gold is now decaying.
Then I tested with `runlocalhost.bat` (CTF offline) and Gold stays as it should.
=> [fixed] Fix that"gold will decay over time" wasn't working

Entities/Materials/Ammunition/MaterialWaterArrow.cfg
[changed] Water arrow shows up as a stack of 1 in archershop, instead of 2
[changed] "Water Arrows" inventory name to "Water Arrow"
Fixed #1435.
Go to Sandbox, spawn an Archershop.
Notice Water Arrow shows up as a stack of 2 in the purchase window.
Once bought, you can only carry 1 per slot, though.
Although Bomb Arrow shows up as `"Bomb Arrow"` in inventory, Water Arrow still show up as `"Water Arrows"` (plural).
**After this PR, Water Arrows will show up as a stack of 1 in archershop. The Water Arrow's inventory name will be "Water Arrow" to be consistent with Bomb Arrow that also comes in a stack of 1.**
=> [changed] Single water arrow in archershop, instead of double

Entities/Common/Building/PlacementCommon.as, Rules/CTF/Scripts/CTF.as
Two issues currently exist:
The first is that current code does not work properly for an unknown reason:
CTF.as (serverside only)
```
void onStateChange(CRules@ this, const u8 oldState)
{
// we have to do it like this because warmup state is broken and not synced properly clientside
if(isServer())
{
if (this.getCurrentState() == WARMUP)
{
this.Tag("faster building");
this.Sync("faster building", true);
}
else
{
this.Untag("faster building");
this.Sync("faster building", true);
}
}
}
```
PlacementCommon.as (clientside part)
```
u32 getCurrentBuildDelay(CBlob@ this)
{
return (getRules().hasTag("faster building") ? this.get_u32("warmup build delay") : this.get_u32("build delay"));
}
```
There have …
=> fix attempt for faster building

Entities/Zombies/Greg/Greg.as
Fixes #1459.
When Greg grabs a player who is already attached, then that player would be attached to that thing and Greg at the same time, causing glitchy behavior.
This PR makes it so the player detaches from catapult/bed/dinghy etc. before getting attached to Greg.
The player still holds onto their item in their hand when getting grabbed.
Tested in offline and online.
Go to Sandbox, spawn a Greg, get grabbed when sleeping in bed or sitting in a Catapult.
Notice you are still inside the bed or in the catapult but also fly away with Greg at the same time as indicated by the orange arrow pointer and camera movement. 
**After this PR, no such glitchy behavior happens, as the player properly …
=> [fixed] Greg not detaching players before attaching them

Entities/Common/Scripts/AlertAdminOnDie.as, Entities/Materials/Construction/MaterialGold.cfg, Entities/Natural/Trees/BushyTree.cfg, Entities/Natural/Trees/PineTree.cfg
Resolves #1067 
Could be improved by also detecting the player who throws a blob into the void that contains gold or seeds.
1. Throw gold or seeds into the void.
2. Jump into the void with gold or seeds.
3. Throw a blob into the void that contains gold or seeds.
=> Alert admins when gold or seeds are thrown into the void

Entities/Items/Crate/Crate.as
Resolves #1449
1. Buy a warboat crate.
2. Destroy the crate.
3. Verify 50 gold is dropped.
4. Verify no gold is dropped for other crates that don't require gold to buy.
=> Warboat crate drops gold when destroyed

Entities/Structures/Components/Load/Spiker/GenericSpike.as, Entities/Structures/Spikes/Spikes.as
Resolves #1352
Spikes still keep track of whether they are bloody but don't show that to players with `g_kidssafe` enabled. This means spikes will immediately turn bloody when the setting is disabled if someone has jumped into the spikes.
1. Enable `g_kidssafe`
2. Jump into spikes
3. Verify blood isn't visible on spikes
4. Disable `g_kidssafe`
5. Notice that blood becomes visible
=> Hide blood on spikes when kidssafe is enabled

Rules/CommonScripts/KAG.as
Fixes #156 🎉 
Seems too simple of a fix to actually be the true fix to this longstanding issue, but it seems to work fine and is the solution players have manually done to resolve the issue (`/rcon /reloadseclevs`).
1. Be admin
2. Start and join a dedicated server
3. Verify the admin menu is visible
=> Fix admin tab not showing on esc menu

Entities/Common/Controls/StandardPickup.as
Resolves #1375
1. Be knight
2. Pickup arrows surrounded by logs
3. Be archer
4. Pickup bombs surrounded by logs
=> Increase pickup priority of arrows and bombs

Entities/Common/Includes/Requirements.as, Entities/Industry/CTFShops/Quarters/Quarters.as, Scripts/Default/DefaultGUI.as
Added a "hurt" requirement that makes shop items purchasable only when the player is hurt. This requirement has been added to the beer and meal in the quarters. The requirement is shown with the other shop item requirements.
Resolves #1306
Try buying a beer or meal when at different amounts of health.
=> Prevent buying beer and meal from quarters when at full health

Entities/Industry/Building/DefaultBuilding.as, Entities/Structures/Common/AddTilesBySector.as, Entities/Structures/Common/DefaultNoBuild.as
Currently, the backwall of a building is generated and then 10 ticks later the center tile is set to air to make a window. This PR changes this so it generates the backwall with the window on the same tick, and the window doesn't remove any existing hand-placed backwall.
Resolves the first proposed change in #1314
1. Build a building in the open
2. The window is generated as normal
3. Build a wall of backwall
4. Build a building in front of that backwall
5. Notice that the window is not generated because the backwall exists
=> Buildings no longer remove center backwall when built on hand-placed backwall 

Rules/CommonScripts/Holiday/Holiday.as
Resolves #1193
1. Manually set `server_date = 2` (3rd of January)
2. Verify that Christmas is still active
=> Fix holidays not taking into account year change

Rules/CTF/Scripts/CTF_GiveSpawnItems.as
The amount of materials added to the game because of the build time changes was underestimated, so it's being modified.
REBUILD (CURRENT):
30s timer (resupply at 180/150/120/90/60/30) - 6 resupplies 
21600 wood total (12 players, 300 per player)
7200 stone total (12 players, 100 per player)
THIS PR:
40s timer (resupply at 180/140/100/60/40) - 5 resupplies 
12000 wood total (12 players, 200 per player)
3600 stone total (12 players, 60 per player)
The 50% reduction in stone may be a bit harsh, but it is still going to be more mats than pre-rebuild. Moreover, most maps also have tons of stone accessible from stone ore at the start of the game (eg. elantris - easy 3k), so it's not gonna be a 50% …
=> [modified] amount of materials in build time (balance change)

Rules/CommonScripts/KAG.as
#1478 (which was merged but not released) causes the admin tab to be shown even on servers on which you are not an admin. This is likely because reloading seclevs on the client-side overrides the seclevs obtained from the server. Attempting to actually do things from the admin menu of course fails as it fails the security checks on the server-side.
This checks whether we're the server before executing the seclev reloading. The seclevs will also be reloaded on localhost servers which should not be an issue.
=> [dev] Fixed seclev reloading showing admin menus on client

Entities/Structures/Platform/Bridge.as
Resolves #1489
1. Place bridge
2. Damage bridge
3. Change team
4. Fall through bridge
5. Verify bridge shows correct damage frame after it closes
=> Damaged bridge correctly shows damage after closing

Entities/Industry/CTFShops/KnightShop/KnightShop.as
it was showing wrong icon (damaged)
=> fixed wrong keg icon in knight shop

Entities/Common/Factory/Shop.as, Entities/Common/Includes/Requirements_Tech.as
**Requires testing on server! Only tested on localhost.** However, I believe it should work because the requirements checking code seems to be client-side in the first place.
Now, shop GUIs are refreshed every tick to update button status. Check reproduction steps.  
It might seem silly to refresh requirements `onTick` but it really shouldn't be a big deal, and should allow us to avoid thinking about every edge case if taking an event-based approach.
Examples:
Knight shop example:
1. Build a knight shop
2. Set your coins to 200
3. Buy bombs, see options gray out as you run out of coins
Builder shop example:
1. Build a builder shop
2. Buy things with wood, see options gray out as you run out of …
=> [fixed] CTF shops never refreshed as you stopped/began passing requirements while open

Entities/Common/Factory/Shop.as
This is a rather braindead way to do things (as `onTick` could be moved to a rules script there), but it is generally not a big deal. We move the refresh-related properties from shop blob properties to rule properties.
I'd rather not do this, but ATM, the only way to get an open `CGridMenu` appears to be to get it by its caption. Of course, different shops are highly likely to have the same caption.
One could hold onto a `CGridMenu` reference through a generic `get`/`set` but we have seemingly no way of figuring out whether a grid menu is still alive at that point or not.
Considering there is no situation where we can have multiple shops open, this seems to be a functional way to achieve this.
=> [dev] fix to shop refresh broken logic

Entities/Special/WAR/WAR_base/WAR_base.as
Fixes #1543.
I spent many hours finding the cause of the War Base crash and found that `getMap().getBlobs()` is the culprit.
It doesn't fetch blobs properly.
But using just `getBlobs()` will work fine.
So I made this PR which changes the code so the crash will not happen anymore.
Use this code inside `WAR_base.as`:
```
void onTick(CBlob@ this)
{
if (isServer())
{
CBlob@[] b;
this.getMap().getBlobs(@b);
for (uint s = 0; s < b.length; ++s)
{
CBlob@ blob = b[s];
if (blob is null) 
continue;
Vec2f blobpos = blob.getPosition();
print(" "+blobpos);
}
}
}
```
When you spawn a `war_base`, it will print either a lot of `(0, 0)` or `(nan, nan)` or even things like `(-2.26674e+23, -nan)`.
Sometimes it …
=> [fixed] War Base crash bug

Entities/Structures/Spikes/Spikes.as
This fixes [issue #1231](https://github.com/transhumandesign/kag-base/issues/1231).
Spikes will now do damage again when attached to dirt/wood after no longer being attached to stone.
The bug was that the spikes thought they are still in state "hidden", therefore the onCollision() function didn't execute the damage.
I added a line in onTick() so if placedOnStone is false, then set the spikes to state "normal".
I play-tested the change a bit offline and there seems to be no side-effects. The spikes are behaving as usual.
Before this gets into the next patch, please test this change online, too. (Although I don't think there are side-effects online.)
- Place spikes next on stone.
- Remove the …
=> Spikes not attached to stone anymore are doing damage

Entities/Industry/CTFShops/BoatShop/BoatShop.as, Entities/Industry/CTFShops/BuilderShop/BuilderShop.as, Entities/Industry/CTFShops/Quarters/Quarters.as, Entities/Industry/CTFShops/VehicleShop/VehicleShop.as, Entities/Items/Crate/Crate.as
As per mugg's comment on the old PR:
https://github.com/transhumandesign/kag-base/pull/1475
The gold drops for Outpost crate and Warboat crate are declared in two different places.
Gold drop for Outpost crate is added via VehicleShop.as onCommand()
whereas epsilon's PR added Gold drop for Warboat crate in Crate.as onInit().
It also caused an issue with crates not being able to auto-pickup items.
Doing `blob.get_string("packed")` means `blob.exists("packed")` will return true every time after that (which is stupid, but I suppose you're supposed to do an .exists check before getting it every time),
so `crateTake()` in CratePickupCommon.as was returning false due to that, breaking the autopickup.
=> Warboat crate drops gold when destroyed done properly && fixed crate auto-pickup

Entities/Industry/Workbench/Workbench.as
Fixes #1555.
This is a fix for the workbench bad snapshot bug that happens when you craft items at workbench in online servers.
`AddShopItemsToMenu()` in `Shop.as` applies this to command `"shop buy"`:
```
CBitStream params;
params.write_u16(caller.getNetworkID());
params.write_bool(s_item.spawnToInventory);
params.write_bool(s_item.spawnInCrate);
params.write_bool(s_item.producing);
params.write_u8(u8(i));
params.write_bool(false); //used hotkey?
```
and reads it in `onCommand()` as such:
```
if (!params.saferead_u16(callerID))
return;
bool spawnToInventory = params.read_bool();
bool spawnInCrate = params.read_bool();
bool producing = params.read_bool();
u8 s_index = params.read_u8();
bool …
```
=> [fixed] workbench bad delta bug

Entities/Structures/Door/DoorCommon.as, Entities/Vehicles/Boats/Dinghy.as, Entities/Vehicles/Boats/Dinghy.cfg, Entities/Vehicles/Common/BoatCommon.as
- **READY**
Vehicles open doors. This was already a feature in KAG some time ago but it was likely removed unintentionally.
https://user-images.githubusercontent.com/68350259/210167289-f17a1706-2b65-47f4-adb7-b14aceb86bc1.mp4
Drive a vehicle towards doors and watch as they open magically. This should work with both boats and ground vehicles. Vehicles should not open doors under them, only above or directly to the sides.
=> Vehicles open doors

Entities/Natural/Farming/GrainPlantLogic.as
- **READY**
When joining a server, fully grown grain plants will not update to the client fully and the grains will not appear. This is fixed in this PR, so that the plant will update to the client when a player joins.
Pic of a bugged grain plant with no grains
Spawn a grain plant and let it grow on a dedicated server (be aware that map-generated plants don't have the bug). Spawn a bot to keep the server ticking when there is no other players (this step may not be necessary). Leave the server and rejoin. There should be no difference in visuals if the fix is applied.
=> Fixed grain not appearing on player join

Entities/Industry/CTFShops/Quarters/Quarters.as
- **READY**
Closes duplicate pull request #1303
Here's a demonstration of the bug that is fixed in this pr.
https://user-images.githubusercontent.com/68350259/213346755-4b7a81af-467a-46de-a04a-bb316733901c.mp4
and here is the bug in a public game
https://user-images.githubusercontent.com/68350259/213349964-f4f3dda6-d5af-43e1-94ad-4ef7d16c8d76.mp4
Test on a **dedicated server**.
Reproducing this bug is a tad difficult, as you have to attach to the quarters at about the same tick the quarters is destroyed.
The timing can be done easier by spawning a quarters on top of a crate and using the collapse as a cue to attach to the quarters (as shown in the first video).
With the applied fix, the player will not attach if the quarters is dead. Print statements is a reliable way to confirm if the …
=> Fixed quarters limbo

Entities/Industry/Tunnel/TunnelTravel.as
- **READY**
Resolves #1568 by sorting tunnels according to map position (x-coordinate, then y-coordinate) instead of sorting by distance from the current tunnel.
Create a series of tunnels/halls/outposts at different elevations, and try to visit each tunnel. You should be able to visit a given tunnel by clicking the same button position (e.g. 2nd from left) consistently, no matter which tunnel you're traveling from.
Example video:
https://user-images.githubusercontent.com/22576116/213897695-50560e17-c67c-4ee8-893e-8256e6bf498e.mp4
Note: I mentioned in the issue that we may wish to flip the vertical sorting for red team (i.e. bottom-to-top instead of top-to-bottom). I did not implement that in this PR.
=> [modified] Update tunnel menu to display options in consistent order

Entities/Common/Movement/FallDamage.as
- **Fixed**
- No known issues.
Fixes #1382.
A dead player could make a grunt when fallen from a high place.
If you keep throwing the same corpse, instead of the grunt it could make a broken bone sfx.
This PR checks if the player is actually dead by checking for `hasTag("dead")` before playing 
`Sound::Play("/BreakBone", this.getPosition());` or `Sound::Play("/FallDeath.ogg", this.getPosition());`.
Tested in offline, should work in online.
Go to Sandbox.
Place one ladder on the ground, then have spikes fall on you to kill yourself.
Pick up your own corpse, climb to a high place and throw your corpse to the ground.
If done correctly, should make a grunt sound or a break bone sfx. 
--> **After this PR, it doesn't make any sound.**
=> [fixed] corpse making a grunt when falling

Entities/Industry/CTFShops/Outpost/Outpost.as, Entities/Vehicles/Airships/Airship.as, Entities/Vehicles/Boats/Dinghy.as, Entities/Vehicles/Boats/LongBoat.as, Entities/Vehicles/Boats/WarBoat/WarBoat.as, Entities/Vehicles/Common/VehicleConvert.as
- **READY**
A few minor improvements to vehicle capturing.
* Commit 1: Fixed a bug where the mounted bow on a warship would not change teams.
* Commit 3: Attached vehicles can only be converted by their parent (The vehicle that they are attached to).
* Commit 4: Introduces customizable capture zones, which fixes a problem with outposts being capped outside of walls. More in detail farther down.
A: Test to see the warboat's mounted bow change team when the warboat is captured.
B: Attach a catapult to a warboat/longboat. Now try to capture the catapult. You should only see the boat being captured.
C: Place one layer of blocks around an outpost. You shouldn't be able to capture it outside of the blocks.
devs & modders listen:
Capture zones are customizable. For example, here is the zoning …
=> [boat rebuild] Improved vehicle capturing

Rules/CommonScripts/PlayerCamera.as
Fixes #1536.
This PR makes it so you can move the camera 1 second after dying instead of 2 seconds.
Tested and verified in offline and online.
=> [changed] Reduce the wait time before you can move the camera after dying

Rules/CommonScripts/TimeToEnd.as
I put the Timer slightly higher so the "Following player" text doesn't overlap with it.
https://i.imgur.com/rcC6Grg.png - Before
https://i.imgur.com/ja6laxT.png - After
For testing, you can add TDM.as to and remove WAR-related scripts from WAR/gamemode.cfg, then go to offline TTH tutorial. Use !bot, !team 1, !bot, then switch to Spectator.
=> [fixed] that the "Following Player" text was overlapping with the Timer

Entities/Industry/Building/Building.as, Entities/Industry/CTFShops/ArcherShop/ArcherShop.as, Entities/Industry/CTFShops/BoatShop/BoatShop.as, Entities/Industry/CTFShops/BuilderShop/BuilderShop.as, Entities/Industry/CTFShops/KnightShop/KnightShop.as, Entities/Industry/CTFShops/Quarters/Quarters.as, Entities/Industry/CTFShops/VehicleShop/VehicleShop.as, Entities/Structures/Common/AddTilesBySector.as, Entities/Structures/Common/DefaultNoBuild.as
[changed] Tunnel, Storage, Quarry and Outpost don't have a window. (Fixes #1314)
[changed] Condense `AddTilesBySector()` and `AddTilesBySectorWithWindow()` into one function.
This makes it so certain buildings where the window cannot be seen are not receiving a window upon building them.
Knightshop, Archershop, Buildershop, Boatshop, Vehicleshop, Quarters and unconstructed Building will get tagged `"has window"` in their `onInit()`.
Then `AddTilesBySector.as` - which places the building's background tiles - will check for that tag. If it does have the tag, it will not place a background tile over the center tile.
Tunnel, Storage, Quarry and Outpost are not tagged with `"has window"`, therefore …
=> [changed] Tunnel, Storage, Quarry and Outpost won't get a window added to them

Entities/Characters/Knight/KnightLogic.as
Fixes #1544.
Although Wire, Inverter and other component blobs have Tag `"ignore sword"`, Knights could still destroy them via Jabbing/Slashing as long as the same attack also hit something else (a platform or a lever).
The cause of this is the line `this.server_Hit(rayb, rayInfos[j].hitpos, velocity, temp_damage, type, true);` in `DoAttack()` in `KnightLogic.as`. The function does check if `b` has Tag `"ignore sword"` (in fact, it checks for it twice) but it doesn't check if `rayb` has that Tag.
This PR fixes this by making the following changes:
- In `KnightLogic.as` in `DoAttack()`, `if (b.hasTag("ignore sword")) continue;` is only applied once instead of twice.
- Added `if …
=> [fixed] Knight can no longer destroy Wires/Components by Slashing/Jabbing

Entities/Industry/Drill/Drill.as
[fixed] Drill will now correctly cool down over time after getting hit by an enemy fire arrow. (Fixes #1400)
[dev] Only go into the huge drill logic code in `onTick()` if Drill is actually in an "PICKUP" attachment point.
Drill didn't cool down over time after getting hit by an enemy fire arrow (if it remained in standstill position).
When Drill stops moving and loses all its heat, the `tick_not_sleeping` flag would get set and Drill stops ticking.
The flag is only cleared when the Drill is picked up.
Because of this behavior, if a Drill that stopped ticking is getting heated again by an enemy fire arrow, it would not cool down since the "tick_not_sleeping" flag hadn't been cleared.
This PR …
=> [fixed] Drill not cooling down over time after getting hit by an enemy Fire Arrow

Entities/Structures/Platform/Bridge.as
Fixes #1496.
When damaging a Bridge that is currently open due to an enemy player being near, it will not assume a closed sprite.
Repairing an open Bridge will still leave the Bridge open, before and after this PR.
Tested in offline and online with no bugs observed.
Go to Sandbox.
Place some Bridges.
Have an enemy Player stand inside the Bridges.
Damage an open Bridge.
Notice it will assume a closed sprite, but still play a "closing" sound when pushing the enemy Player away. 
**→ After this PR, the Bridge will keep its open sprite.**
=> [fixed] Damaging an open Bridge doesn't give it a closed sprite

Entities/Common/Includes/MiniIconsInc.as, Entities/Industry/CTFShops/VehicleShop/VehicleShop.as, Entities/Items/Crate/Crate.as, Entities/Items/Crate/CrateCommon.as
- **READY**
Resolves #1450.
Specific crates are given their own unique 'required space' depending on the packed blob.
Here is a video showing the differences in unpacking space.
https://user-images.githubusercontent.com/68350259/211714922-5bc14112-a938-421e-ad07-37830ca3c7eb.mp4
a) Use ``!crate (name)`` or buy from vehicle/boat shops to get crates of a longboat, a warboat, and a ballista.
b) Unpack each one to assess if the required space is correct.
Note for reviewers:
Commit 1 & 2 are the necessary changes. 3 & 4 give no functional change.
=> [boat rebuild] Crate required space consistency

Entities/Industry/CTFShops/VehicleShop/VehicleShop.as, Entities/Materials/Ammunition/MaterialBallistaBombBolt.cfg, Locales/German_de.json
This fixes [issue #1235](https://github.com/transhumandesign/kag-base/issues/1235).
"Ballista Bolts" and "Ballista Shells" will be named that way in shop and inventories.
I adapted for this change in the German translation and made a few more fixes to the German translation while I was at it.
- Build a vehicle shop, notice that the Ballista ammo items will be named "Ballista Bolts" and "Ballista Shells" (Previously: "Ballista Ammo" and "Ballista Shells").
- Add those items into your inventory, notice that they will be named "Ballista Bolts" and "Ballista Shells" (Previously: "Ballista Bolts" and "Ballista Bolts").
- Play the game in the German language and notice "Ballista Shells" be translated …
=> Text changes to Ballista Ammunition and German translation

Entities/Industry/Tunnel/TunnelTravel.as
Resolves #1434 except the issue of the menu not updating immediately which affects more than just tunnels.
Outpost team changed:
1. Have three or more outposts
2. Open the travel menu
3. Have an enemy capture one of the outposts
4. Attempt to travel to the captured outpost
Tunnel destroyed:
1. Have three or more tunnels or outposts
2. Open the travel menu
3. Have someone destroy the tunnel/outpost you're travelling from
4. Attempt to travel
=> Prevent fast travel if tunnel/outpost is destroyed or team has changed

Entities/Common/GUI/HealthBar.as, Entities/Vehicles/Common/SeatsGUI.as
When putting Shark in an inventory (Storage/Crate/Dinghy/Longboat/Warboat/Bomber/Airship), the shark's seat arrow and healthbar won't be shown. 
Go to Sandbox, !shark, carry it, !crate, put shark in crate, notice there is no seat arrow and no healthbar.
=> Shark doen't show seats or healthbar when in inventory

Entities/Common/Controls/StandardControls.as
Fixes #1320:
At high ping in online, you could pick up items after sending the "get in" command but before you got put in the crate.
This PR makes it so `onCommand()` in StandardControls.as checks if the picker is in inventory. If yes, the picking up will not happen.
Fixes #1323:
At high ping in online, it is possible that a player picks up an item that has already been picked up or attached.
This PR makes it so the pickup does not happen if the picked item is attached.
Fixes that you could go to Bed or attach yourself and then pick up an item in quick succession.
Fixes #1519:
It was possible to pick up a Dinghy that someone got into just a few ticks ago.
Commit …
=> [fixed] picking up items that have already been attached / picking up items after getting in a crate

Rules/CommonScripts/RegrowPlants.as
Partly mitigates #1354
Profiling shows that object copies within the function is a significant performance hit, which the AS optimizer cannot/is not able to elide.  
This is not a complete fix but a quick improvement because the function's complexity is still `O(n)` with regards to the tile count and should be solved to close the issue.
See issue.
=> Slightly optimize `RegrowPlants`' `findTileByCoords`

Entities/Characters/Knight/KnightLogic.as, Entities/Characters/Scripts/RunnerDeath.as
- **READY**
Resolves #1578 by re-enabling the ability to slash/jab your teammates' corpses.
Also prevents held corpses from getting hit - a missed case from #1083/#1102.
1. Set up a dedicated server
2. Join with at least two players/clients
3. Kill someone to create a corpse
4. Ensure that the corpse can be damaged by slashing/jabbing from knights of any team
5. Have a player pick up the corpse
6. Ensure that the nobody can slash/jab the held corpse, regardless of the team of the holder/attacker/corpse
=> [fixed] Allow slashing/jabbing team corpses and disallow hitting held corpses

Entities/Items/Food/Food.as, Entities/Natural/Seed/Seed.as, Entities/Vehicles/Common/VehicleCommon.as
Allows seeds to be loaded into catapult and makes the correct icon show for them and food when loading.
-Spawn in a catapult
-Load different types of seeds
-Wow, it shows the correct icon
-Load different foods (Cake, Bread, Cooked Fish or Cooked Steak)
-Wow, it shows the correct icon
=> Allow seeds to be loaded into catapult and show correct icon for seeds and food

Entities/Common/GUI/HealthBar.as
- **READY**
* Fixes minor visual bug where the health bar moves far away from it's blob when the camera is zoomed out
Spawn a vehicle/outpost and zoom out your camera. With the fix the health bar won't move too far away from the vehicle.
=> [fixed] Health bar not scaling with camera zoom

Rules/CTF/Scripts/CTF.as, Rules/Sandbox/Scripts/Sandbox_Rules.as, Rules/TDM/Scripts/TDM.as
- **READY**
Currently, the respawn timer in CTF/TDM always rounds down, so the timer will say "Respawning in: 0" for an entire second before you actually spawn. This causes psychological pain when you're really eager to spawn.
This PR adds a slight offset so that the timer mostly rounds up, except for the last few ticks of a second. 
This way, the timer can still briefly show 0 before you actually spawn. I'm open to changing that if people don't like it, but I feel like it's satisfying to see the timer actually hit 0.
Only the displayed value is different. The actual time to respawn is unchanged.
1. Join a CTF or TDM game
2. Die and watch the respawn timer count down
3. The total respawn time should not change, but when the timer hits 0, the player respawns momentarily after (rather than …
=> [modified] Round up respawn timer with slight offset

Entities/Common/FireScripts/IsFlammable.as
- **READY**
Closes #1521 & resolves #1401
1) Burn a drill, log or grain.
2) Attempt to place it into your inventory. With the applied change, it will not be possible until the blob stops burning.
=> [changed] Blobs on fire aren't allowed to be put into inventories

Entities/Characters/Archer/ArcherLogic.as, Entities/Characters/Archer/ClimbArrows.as, Entities/Characters/MovementScripts/RunnerCommon.as, Entities/Characters/MovementScripts/RunnerMovement.as, Entities/Characters/MovementScripts/RunnerMovementInit.as
1. Removed non-deterministic behavior. The previous code relied on `getGameTime()`, meaning that climbing was not consistent.
2. Capped the maximum number of climbs to 2 per wall (instead of non-deterministic 2~3 in practice).
3. Increased the boost a climb gives to compensate for the above.
- What climbs are technically feasible is mostly similar to the current vanilla state - except more consistent (and slightly easier).
4. The way the code triggers climbs is vastly different:
- If you are jumping from the ground, then your first climb will be granted when your velocity stalls or becomes negative. This has the effect of granting "ideal climbs" when holding up+direction towards a wall when …
=> Wallclimb rework

Entities/Common/Movement/FaceAimPosition.as
The tickfrequency of FaceAimPosition was 3.
Since movement is dependent on the position a blob is facing (you walk faster when walking in the direction you're facing), this could mean that the same exact inputs reproduced in the same conditions could give different results.
This is the same as the deterministic wallclimb behaviour mentioned in https://github.com/transhumandesign/kag-base/pull/1603
- Spawn bots every tick and make them repeat the same actions (make them move their cursor a bit as well)
- Notice how some bots divert to different routes even with the same exact input. This is because when they change their facing direction, in some cases they will do it a tick or two later.
- Test …
=> Change setting blob facing side to be deterministic

Entities/Characters/MovementScripts/RunnerMovement.as
Climbing 1, 2-block walls was annoying with the new, improved wallclimbing due to the wait-for-optimal-time mechanic when giving speedboosts. Changed it to give speedboosts immediately if your velocity.x was higher than 0 in previous tick (jumping at a wall from an angle). Tested online on Captains, works as intended.
=> Wallclimbing improvement

Entities/Characters/Builder/CommonBuilderBlocks.as, Entities/Structures/Components/Passive/Magazine/Magazine.as
This is an addition/enhancement to [Pull Request #1215](https://github.com/transhumandesign/kag-base/pull/1215). You need to apply PR #1215 and then this to see all the changes.
Fixes [issue #1253](https://github.com/transhumandesign/kag-base/issues/1253).
- You can put in any 1x1 item instead of making it dependent on item's radius. Can put in Log, Drill, Chicken, Mine, Scroll, lit waterbomb now.
- It will show the correct icon for seeds and foods, if you applied PR 1215.
- It will say "(Un)Load -item-" instead of "(Un)Load".
- Magazine requires 20 wood.
- Optimized code to make it less repetitive.
Use `caller.getCarriedBlob()`
instead of …
=> Magazine accepts any 1x1 item and shows the correct icon

Entities/Items/Boulder/Boulder.cfg
A Boulder bought from Trader/Buildershop or spawned in Sandbox will always be of team 255. 
Therefore it will hit anyone who isn't in your team.
However, for Boulders bought at Trader, line 308 in TradingMenu.as will set the Boulder team to your team:
```
blob.server_setTeamNum(caller.getTeamNum());
if (!item.buyIntoInventory || !caller.server_PutInInventory(blob))
{
caller.server_Pickup(blob);
}
```
If the enemy picks it up, it will still be considered to be of the buyer's team. So the buyer's team cannot be hit by the boulder when the enemy picks it up. This causes strange situations in TDM: "I stole your Boulder and threw it back at you. Wtf it isn't dealing damage?"
To fix this, line 308 in …
=> [fixed] Boulder not hitting the buyer's team

Entities/Structures/Common/DummyOnStatic.as
This fixes [issue #592](https://github.com/transhumandesign/kag-base/issues/592).
Background and grass will no longer break when selecting obstructor/sensor and then something else in the build menu.
The same code in DummyOnStatic.as is executed when "selecting obstructor/sensor and then something else" and when the tile actually breaks. So I check the tile's health to make sure the code only executes in the latter case, when the health is 0.
I play-tested the change and the two components behave the same as before.
=> Obstructor and Motion Sensor no longer break background

Entities/Items/Explosives/Explosion.as
Fixes #1312 
As said in the issue, Bombs & KEGs weren't able to damage or destroy their own inventory container such as: Dinghy, Longboat, Warboat, Airship, Storage & Magazine (Players & Crates works fine though).
However, I had to do an extra step for the KEG. For some reasons, `keg_blob.isInInventory()` returned `false` and `keg_blob.getInventoryBlob()` returned a `null` value too, so I had to edit the lengthwise comparison check, I'm not sure if it will lead to unexpected behaviours. My tests seems fine though.
+ Start any game
+ Place any container (!dinghy, !longboat, !warboat, !airship, !storage)
+ Place an activated explosive (!keg, !bomb) in the container and waits it for exploding 
+ …
=> [fixed] Explosives inventories not taking damage

Entities/Industry/Saw/Saw.as
[fixed] Player will do their death cry and properly let go of a held food when getting killed by Saw, instead of eating it.
Fixes #1462.
Here is the order of executions before this PR:
1) `Saw.as`: `this.server_Hit(blob, bpos, bpos - pos, 0.0f, Hitters::saw);`
2) `RunnerDeath.as`: Checks if health is 0 or lower; if true runs things like `... PlaySound("WilhelmShort.ogg", ... )` and `StuffFallsOut(this);`
3) `Saw.as`: `onHitBlob(...)`
4) `Saw.as`: `Blend(...)` and `tobeblended.server_SetHealth(-1.0f);`
The health isn't reduced to zero until 4) happens, so at 2) all the code in `RunnerDeath.as` is skipped.
This PR adds a line `blob.server_SetHealth(-1);` right before 1), therefore the code at 2) …
=> [fixed] that RunnerDeath wasn't run when sawed

Rules/CommonScripts/ScoreboardRender.as
In staging, the window can be dynamically resized, so the screen size should never get cached into a global variable initialized once.
Resize window in staging with scoreboard open.
=> Staging: scoreboard didn't resize with window

Rules/CommonScripts/ScoreboardRender.as
- **READY**
u32 "match_time" is synchronized every ten seconds instead of every tick.
There is no functional difference. This aims to limit spam in server logs while debugging.
1) Go onto a dedicated server as a moderator.
2) Start the match with chat command ``!startgame``.
3) Use ``/rcon /g_debug 1`` in rcon to activate server sync prints. View the console.
=> [dev] Less "match_time" sync

Entities/Natural/Scripts/PlantGrowth.as, Entities/Natural/Scripts/canGrow.as
- **READY**: this PR is ready.
For plants to grow, they use a tile one block deeper than expected rather than the surface tile. This change simply changes it so the surface tile is always used instead.
Place a plant of any kind onto the ground. The plant will always grow as long as there is a dirt block underneath the plant.
=> [fixed] Plants growing off incorrect tile

Rules/CommonScripts/KickAFK.as
- **READY**
Resolves #1398 
Implementation as follows:
* AFK Players will be sent into spectator if the server is below half-capacity (threshold subject to change).
* AFK players will be kicked off servers regardless of player count on Sandbox and Challenge game modes.
1) Go onto a dedicated server.
2) Wait to be kicked. If the player count is below 50% capacity then you will be sent into spectator.
3) Use bots to simulate AFK kicking over 50% capacity.
=> [modified] Kick AFK to spectator when seeding servers

Entities/Industry/CTFShops/Storage/Storage.as, Entities/Industry/CTFShops/Storage/Storage.cfg, Entities/Items/Lantern/Lantern.as, Entities/Items/Sponge/SpongeCommon.as
- **READY**
Closes #1245, #1217, #1287, #1264
* Fixes problems with lantern desync.
* Lanterns' inventory icons change when off/on.
* Included sponge inventory frames from #1264 ,
credit to @mugg91 .
Test on a dedicated server.
A) Turn off a lantern. Rejoin the server. With the applied fixes, it should look the same as before.
B) Turn off a lantern and put it into your inventory. With the applied changes, it will appear off.
C) Put lanterns into a storage. The storage will display a lit lantern if at least one of the lanterns is on. Otherwise it will be unlit.
D) Absorb water with a sponge and put it into your inventory. It should appear the same.
=> [fixed] Lanterns sprite not updating on client join

Entities/Common/Includes/Costs.as
- **READY**
As suggested by @Vam-Jam in #1370
Optimizations
* Costs.cfg is read only once. The values are stored in a dictionary in rules.
* Other scripts will read from the dictionary. When those scripts receive the values, they do not read costs ever again.
No intended functional difference.
Though, will this even make a beneficial difference enough to be important? Let me know
=> [dev] Costs optimization

Rules/CommonScripts/RedBarrier.as, Rules/CommonScripts/RedBarrierVars.cfg
Rewrote red barrier from scratch, mainly because the old barrier code got a bit messy and to fix some issues we've been seeing with it.
Changes:
- x1 and x2 is no long f32, instead its u16 (since we didnt really need it to be f32)
- We only sync the 2 x positions instead of 2 x positions and 2 y positions 
- RedBarrierVar.cfg is now an option for servers
- Server vars will only sync if `blob_pushback` was changed in the cfg (only var client needs)
- Spikes and materials will get pushed by the barrier 
- Code might be cleaner?
=> [Change] Red Barrier Rewrite

Entities/Common/Building/BlockPlacement.as
```
A B C
D E F
G H I
```
Assume there is a Bush placed in the tile at E.
I noticed the bush only gets destroyed if a block is placed in E, F, H, I.
So it gets destroyed when placing a block to its right, but it stays alive when placing a block to its left.
I looked into it.
If a building is built, `DestroyScenary(tl, br);` in BuilderCommon.as is executed. 
tl is actually the top-left of the building.
br is actually the bottom-right of the building.
Everything is fine here.
If a block is placed, `DestroyScenary(cursorPos, cursorPos)` in BlockPlacement.as is executed.
cursorPos is equivalent to the tl of the block. 
So scenery will only be destroyed in that section.
This is not consistent with …
=> Placing a block will destroy scenery in the whole block instead of only in the top left of the block

Entities/Characters/Scripts/RunnerAnimCommon.as
Fixes #1627
1. Use any emote, your player should look like they're pointing in the direction you're aiming.
2. Open chat with enter, the speech bubble should show but your player shouldn't be pointing towards anything.
=> Do not show player pointing frames for chat bubbles

Entities/Structures/Components/Passive/Emitter/Emitter.as, Entities/Structures/Components/Passive/Receiver/Receiver.as
Emitters/receivers are background mechanisms and should not block water. Tested all other mechanisms, all other ones had correct behavior.
The added code is the same that is used for other mechanisms.
1. Use `!spawnwater` in sandbox
2. Place mechanisms
=> [fixed] emitters/receivers incorrectly blocked water

Rules/CommonScripts/Editor.as
- Closes #1629
- Makes it so that placing and breaking tiles lets you hold the keys, so you can place or break a bunch of tiles easily to debug things
1. Set `sv_test = 1` in autoconfig.
2. Start the game in localhost mode (e.g. singleplayer).
3. Hold the builder modifier key (check keybindings) and hit action1 (LMB) to place a stone block, action2 (RMB) to break blocks
=> [modified] localhost debug editor requires holding build mod + lmb/rmb

GUI/guiHeadsPack.xml, GUI/guiPatreon.xml
Closes https://github.com/AsuMagic/kag-staging/issues/157 -- cba to debug why Irrlicht decided to use a clip rect of height 90px for that text when nothing seems to use that as a value. Nothing else seems like it should be affected, anyway.
1. Use staging
2. Get the patreon & DLC boxes to open (from the customization settings)
=> Staging: work around clipped text in dlc/patreon boxes

Entities/Common/FireScripts/FireCommon.as, Entities/Common/FireScripts/IsFlammable.as
Fixes #1368.
If applying `blob.server_Hit(blob, blob.getPosition(), blob.getVelocity(), 0.0f, Hitters::fire);` in a too quick succession (such as every 10th tick), the affected player won't take any damage.
In `IsFlammable.as` in `onTick()`, after `else if (burn_time > 0)`, the value `burn_time` is used to determine if damage should be applied. If `burn_time % 7 == 0` is true, then the damage is applied. Since repeatedly applying `blob.server_Hit()` will reset `burn_time`, the condition can never become true.
I implemented a new value `burn_count`.
This value is incremented by one when entering the `else if (burn_time > 0)` section.
The previous condition `burn_time % 7 == 0` has been replaced …
=> [fixed] Player not taking damage when taking fire hits in quick succession

Entities/Common/Factory/Shop.as
When the `caller` blob occasionally had a `null` player, then the shop script would crash. We could just add a null player check, but we might as well not read the caller from the stream. Getting the player from the netcode is more robust.
This also makes it so that the command handler early returns if `!isServer`. It should not be the case that all players receive the `"shop buy"` command...
Test shops on dedicated servers for robustness. Test corner cases.
=> Use `getActiveCommandPlayer` in shop logic

Rules/CommonScripts/PlayerCamera.as
Fixes https://github.com/transhumandesign/kag-base/issues/579
All ways to get scroll input from the player do not work in onRender hooks if you are on capped framerate ever since the uncapped framerate option was added to the game.
According to GoldenGuy:
```
cuz input checking from render hooks is garbage
controls related stuff should only be used in ontick hooks
dont want to explain why
```
This PR fixes it by running the code which checks for scrolling input in onTick if you are on capped framerate rather than in onRender.
test zooming in and out while in spec/while dead both while using capped framerate and uncapped
=> [fixed] script-side hack-fix for not being able to zoom in and out in spectator/while dead on capped framerate

Entities/Natural/Farming/Grain.cfg
since grain has both ignoredamage.as and isflammable.as, setting grain on fire ended up making it produce the same sound and particles as hitting bedrock does
try to set grain on fire. u cant
=> [dev] remove isflammable from grain

Rules/CommonScripts/ScoreboardRender.as
Slightly redused the distance between numbers in 2 digit ages, also fixed "y" letter offset being too far away from number 1
Differences:
before - 
after -
=> Small change to scoreboard age number.

Rules/CommonScripts/CinematicCommon.as
map could be null and targetblob could be null
which results in null pointer errors and the camera dying
=> [dev] add missing null checks in PlayerCamera.as

Rules/CommonScripts/MapVotesCommon.as
**READY**
As it stands now, players that want to hangout and destroy building at the end of the game are met with a black screen preventing them from seeing what they are doing. To remove the black screen, players resort on clicking on the random map button as quickly as possible to be able to hangout or destroy something before the game finishes. 
By removing the black screen, players that want to hangout without caring about end game map voting won't be incentivized to speedrun click on "random map." This should make the map voting feature more useful.
This PR remove the black screen at the end of the games in the hopes to decrease the number of random map voters.
This is before this PR :
This is after this PR :
=> [modified] removed black screen during map voting

Entities/Industry/CTFShops/Outpost/Outpost.as, Entities/Vehicles/Ballista/Ballista.as, Entities/Vehicles/Boats/WarBoat/WarBoat.as
This PR addresses [issue#1498](https://github.com/transhumandesign/kag-base/issues/1498). Flag animation speeds have been made consistent and based on the `CTF_FLAG` blob.
!spawn Outpost
!spawn Ballista
!spawn Warboat
In sandbox to view their flags.
- All gamemodes relevant
- Objects affected are: Outpost, Ballista, Warboat
=> Make flag animations consistent

Entities/Industry/CTFShops/BuilderShop/BuilderShop.as
Resolves #1680
Look at the drill in the builder shop as red team
=> Fix drill icon not team-colored in builder shop

Entities/Vehicles/Boats/LongBoat.as, Entities/Vehicles/Boats/WarBoat/WarBoat.as, Entities/Vehicles/Common/WoodVehicleDamages.as
Part of #1614 & related to #1404
* Warboat can withstand 8-9 bomb arrows before sinking.
* Longboat can withstand 3-4 bomb arrows before sinking.
* Longboat is much stronger against normal arrows (previously only 22 arrows could sink one!).
=> [boat rebuild] Boat bomb arrow resistance

Entities/Common/Controls/StandardControls.as
Tapping E should select your held item's button even when you're going fast.
Addresses #1545 
I don't fully get why this works, but it seems like it does. Haven't tested on a laggy server. Also it might make it slightly harder to tap E to open a shop if you're holding a log or something and going really fast?
Get a crate, or a scroll of doom or something
Jump off a cliff
Tap E
=> [fixed?] Crate button being hard to press at high speeds

Entities/Industry/CTFShops/Quarters/Quarters.as
Quarters.as
"rest" - was client->server, still is. uses getActiveCommandPlayer() rather than id sent by client. added range check.
=> Cmd sanitization quarters

Rules/CommonScripts/ShowTipOnDeath.as, Rules/CommonScripts/SpectatorQueue.as, Rules/CommonScripts/VoteCore.as
```
[fixed] wrong font being used on tips and queue button when game state banners are shown
```
Fixes https://github.com/transhumandesign/kag-base/issues/1699
Tested online, works.
You can add
```
if (index == 1)
{
getRules().SetCurrentState(GAME);
}
else if (index == 2)
{
getRules().SetCurrentState(GAME_OVER);
}
```
in `TipCommand` in `MiscCommands.as`.
Go to CTF.
Place spikes.
Jump in the spikes so the next jump would kill you.
Still during build phase, type `/tip 2` = battle phase start, banner is shown. Then ...
... Quickly jump in the spikes again.
Notice the font on the tip is wrong.
**After this PR, it is correct.**
... Quickly go spectator.
Notice the font on the queue button is wrong. …
=> [fixed] wrong font being used on tips and queue button when game state banners are shown

Rules/CommonScripts/ColoredNameToggle.as, Rules/CommonScripts/ColoredNameToggleCommon.as
ColoredNameToggle.as, ColoredNameToggleCommon.as
"toggle colored name command" - was server->server and server->client, is now server->client only. 
"request admin prefs" - was server->client, no intervention needed (added if isClient() to make things clear)
=> Cmd sanitization colorednametoggle

Entities/Common/Taunts/TauntMenu.as, Rules/CommonScripts/EmoteBinderMenu.as
TauntMenu.as (moved "display taunt" init from EmoteBinderMenu.as)
"display taunt" - was a command that relied on client->server->all clients. now it's just client->server, added "display taunt client" which does the server->client part
also changed volume of the loud ass noammo (all other files use it with 0.5)
=> Cmd sanitization taunts

Scripts/MapLoaders/MinimapHook.as
MinimapSync.as
The script overall feels unnecessary. The client requests sync on 1st tick after joining and after restart. The server then syncs 3 bools to all clients. There is no reason why the bools would not be synced automatically by the server. Commented the script out; if its removal causes any issues in the future, it should be added back.
=> Cmd sanitization minimapsync

Entities/Vehicles/Ballista/Ballista.cfg
Since the engine searches for textures by first match, in place of the correct texture of the ballista is set the texture of the head of one of the player's head. The pull-request fixes this.
Without fix:
With fix:
=> [fixed] use correct ballista texture

Entities/Industry/Tunnel/Tunnel.as, Entities/Industry/Tunnel/TunnelTravel.as
Tunnel.as
removed unused casual mode code
TunnelTravel.as
split Travel function into server_Travel and client_Travel, added additional checks
"travel" - was client->server and client->client (cgenericbutton command). client->client is a func callback now (the yuck genericbutton callback), client->server is unnecessary, so removed
"travel to" - was client->server and client->client (cgridbutton command). client->client is a func callback now. client->server uses getActiveCommandPlayer(), added some checks
"travel none" - was client->client (cgridbutton cmd), is a func callback now
"server travel to" - was server->client, still is server->client, renamed to "travel to client"
needs #224 Crimson …
=> Cmd sanitization tunnels

Entities/Common/Emotes/EmoteBubble.as, Entities/Common/Emotes/EmotesCommon.as, Rules/CommonScripts/KAG.as
EmoteBubble.as
"emote" - Removed params. Command now relies on getActiveCommandPlayer()'s props.
=> Cmd sanitization emote

Rules/Tutorials/Tutorial01.as
```
[changed] Material bombs don't despawn in tutorial level 1
```
This PR makes it so the three bomb materials in tutorial level 1 don't despawn after 5 minutes.
Because it is possible the player goes afk or spends time in the first half of the level, the bombs could despawn in the meantime and the nearby sign explaining to light and throw a bomb doesn't make sense anymore.
Tested in offline, it works.
----
For testing, you can add `MaterialBomb.as` as a sprite script to `MaterialBomb.cfg` and add this code to `MaterialBomb.as` to render the time until despawning:
```
void onRender(CSprite@ this)
{
CBlob@ blob = this.getBlob();
if (blob is null) return;
GUI::DrawText(blob.getTimeToDie()+"", …
```
=> [changed] Pre-loaded Bombs don't despawn in Tutorial level 1

Rules/CommonScripts/DefaultVotes.as, Rules/CommonScripts/VoteCore.as
VoteCore.as
"vote: yes", "vote: no", "vote: cancel", "vote: force pass" - previously were client->server->client commands. they're now client->server commands that use getActiveCommandPlayer(). added server->client equivalents.
"vote: ended" - was a server->server and server->client command. serverside now runs outside of command, and the command is now server->client
DefaultVotes.as
"vote: kick", "vote: nextmap", "vote: surrender", "vote: scramble" - previously were client->server->client. they're now client->server commands that use getActiveCommandPlayer(). added server->client equivalents. moved votekick cooldown, vote nextmap cooldown, last username votekicked checks to server-side.
also …
=> Cmd sanitization votes

Rules/CommonScripts/TeamMenu.as, Rules/CommonScripts/TeamMenuJustSpectator.as
TeamMenu.as, TeamMenuJustSpectator.as
Replaced client->client cgridmenu commands with func callbacks, needs #224 Crimson to work 
also got rid of ReadChangeTeam() because functions with 2 lines are dumb as fuck
=> Cmd sanitization teammenu

Entities/Common/Building/BlobPlacement.as, Entities/Common/Building/BlockPlacement.as
BlobPlacement.as
"rotateBlob" - was client->server and client->client, is now client->server only. uses getActiveCommandPlayer(), added checks.
"placeBlob" - was client->server but with majority of the checks done on client. the checks are now duplicated on server to ensure player is not building out of range.
"repairBlob" - was client->server but with majority of the checks done on client. the checks are now duplicated on server to ensure player is not building out of range.
"settleLadder" - unused, removed
BlockPlacement.as
"placeBlock" - was client->server but with majority of the checks done on client. the checks are now duplicated on server to ensure player is not building out of range. …
=> Cmd sanitization building

Entities/Characters/Archer/ArcherCommon.as, Entities/Characters/Archer/ArcherLogic.as, Entities/Characters/Builder/BuilderInventory.as, Entities/Characters/Knight/KnightLogic.as, Entities/Common/Controls/StandardControls.as, Entities/Common/Controls/StandardControlsCommon.as, Entities/Common/Controls/StandardPickup.as, Entities/Items/Crate/Crate.as
StandardControls.as, StandardControlsCommon.as, StandardPickup.as
"pickup" - was and remains client->server, sanitized
"putinheld" - was and remains client->server, sanitized
"getout" - was and remains client->server, sanitized
"detach" - was and remains client->server, sanitized
"cycle" - replaced with func callback (ArcherLogic, KnightLogic)
"switch" - is now client->server command called from a func callback (ArcherLogic, KnightLogic)
"tap inventory key" - removed, unnecessary
changed minimum tap inventory key time to cycle item/putinheld to 5 from 7
and to 3 for builder (they have to switch blocks fast)
Crate.as
"getout" - sanitized version from cmd-sanitization-crate&mine …
=> Cmd sanitization controls

Entities/Items/Crate/Crate.as, Entities/Items/Explosives/Mine/Mine.as
Crate.as
"unpack" - was client->server->client, is now client->server. uses getActiveCommandPlayer(), added range check, added "unpack_client" command for the client part of it (just setting drag)
"stop unpack" - was and remains client->server. uses getActiveCommandPlayer(), added range check. syncs prop now
"getin" - was and remains client->server. uses getActiveCommandPlayer(). only getin if holding the crate on server. 
"getout" - was and remains client->server. uses getActiveCommandPlayer(). added range check.
"boobytrap" - was client->server->client, is now only a client->server command. uses getActiveCommandPlayer(), added range check.
"activate" - this was a server->server command so the …
=> Cmd sanitization crate & mine

Entities/Characters/Archer/ArcherLogic.as, Entities/Characters/Builder/BuilderLogic.as, Entities/Characters/Knight/KnightLogic.as, Entities/Common/Building/BlobPlacement.as, Entities/Common/Controls/StandardPickup.as, Entities/Common/Throwing/Activatable.as, Entities/Common/Throwing/ActivateHeldObject.as, Entities/Common/Throwing/ActivationThrowCommon.as, Entities/Items/Containers/Chest/Chest.as, Entities/Items/Containers/Chest/Chest.cfg, Entities/Items/Containers/Present/Present.as, Entities/Items/Containers/Present/Present.cfg, Entities/Items/Crate/Crate.as, Entities/Items/Crate/Crate.cfg, Entities/Items/Explosives/Bomb.cfg, Entities/Items/Explosives/Keg.as, Entities/Items/Explosives/Keg.cfg, Entities/Items/Explosives/KegVoodoo.as, Entities/Items/Explosives/Satchel.as, Entities/Items/Explosives/Satchel.cfg, Entities/Items/Explosives/WaterBomb.cfg, Entities/Items/Lantern/Lantern.as, Entities/Items/Lantern/Lantern.cfg, Entities/Items/Projectiles/Arrow.as
KegVoodoo.as, Keg.as, Arrow.as
"activate" - Was a server->server and server->client command, possibly client->server in certain cases where it shouldn't have been. (ActivateHeldObject.as/KnightLogic.as/Arrow.as/Keg.as). Is now a callback for server->server. Added "activate client", which runs the clientside code.
"deactivate" - Was a server->server and server->client command (Keg.as/KegVoodoo.as). Is now a callback for server->server. Added "deactivate client", which runs the clientside code.
Lantern.as
"activate" - Was a server->server and server->client command ("activate/throw" ActivateHeldObject.as). Is now a callback for server->server. Added "activate client", which runs the clientside …
=> Cmd sanitization activatable clusterfuck

Entities/Structures/Components/Passive/Magazine/Magazine.as, Entities/Structures/Components/Source/CoinSlot/CoinSlot.as, Entities/Structures/Components/Source/Lever/Lever.as, Entities/Structures/Components/Source/PressurePlate/PressurePlate.as, Entities/Structures/Components/Source/PushButton/PushButton.as
PushButton.as
"activate" - was client->server->client, is client->server now, uses getActiveCommandPlayer(), added range check. added "activate client" command which runs the client code.
Lever.as
"toggle" - was client->server->client, is client->server now, uses getActiveCommandPlayer(), added range check. added "toggle client" command which runs the client code.
PressurePlate.as
"activate" and "deactivate" - was server->server and server->client (i think), are now functions that are called server-side rather than commands. added "activate client" and "deactivate client" which run the client-side code.
CoinSlot.as
"activate" - was client->server->client, is client->server now, uses …
=> Cmd sanitization mechanisms

Entities/Characters/Archer/Archer.cfg, Entities/Characters/Builder/Builder.cfg, Entities/Characters/Knight/Knight.cfg, Entities/Common/Attacks/BombHit.as, Entities/Common/Includes/SplashWater.as, Entities/Items/Explosives/Explosion.as
1) bomb knockback force is now independent of distance between bomb and player. tested on captains, feels significantly better than vanilla bomb jumps, less weird ping-based timing which can make your bomb jump feel worse 
2) fixed the issue that bomb jumps from right-to-left were on average weaker than from left-to-right due to Maths::Round being dumb 
3) fixed https://github.com/transhumandesign/kag-base/issues/1822 by adding BombHit script and applying velocity from bomb explosions there instead of Explosion.as onHitBlob
=> [modified & fixed] better bombs (bomb explosion force)

Rules/CommonScripts/ScoreboardCommon.as, Rules/CommonScripts/ScoreboardRender.as
Map names, team names on ru language and match timer broken after this commit: a32a46182dfc57682b830ecab12b30dcbc3f55a3
This pull request fixing this.
Join on vanilla CTF or host local dedicated server with CTF mode, use locale RU and open scoreboard.
=> Scoreboard fixes

Scripts/MapLoaders/MinimapHook.as
```
[fixed] Obstructor has proper minimap tiles depending on its state
```
Fixes https://github.com/transhumandesign/kag-base/issues/1921
Obstructor had a minimap color `tile_castle_back` when it was non-solid, and had none, defaulting to sky color, when it was solid.
This PR changes `MinimapHook.as` to make Obstructor have a minimap tile `tile_castle_back` when it is solid and a brighter `tile_castle_back` color when it is non-solid.
I would like to make Obstructor show up as nothing when it is non-solid (i.e. sky color when it has nothing behind it, or dirt color when it has dirt backwall behind it). But there is no way to recognize such ( see: …
=> [fixed] Obstructor has proper minimap colors now

Rules/CommonScripts/ChatCommands/MiscCommands.as
```
[changed] "/bot" is now "/bot [name]" to allow setting the bot's name. "/henry" removed.
```
Fixes https://github.com/transhumandesign/kag-base/issues/1938
This PR changes `MiscCommands.as` so `/bot` can now take a string to set the bot's name.
When no argument is given, `"Henry"` will be used.
When multiple arguments are given, they will be joined together separated by one space each time.
I tested in offline.
All special characters I tried were accepted.
It didn't make a blank name at any time.
When using very long names, the string will be cut short.
The alias `/henry` was removed.
Type `/bot 123test`, the bot will be named `123test`.
Type `/bot`, the bot will be named `Henry`.
Type …
=> [added] "/bot" now allows setting the bot's name

Rules/CommonScripts/ChatCommands/BlobCommands.as
```
[fixed] "/scroll <name>" will now work in modes other than TTH
[changed] "/scroll <name>" with an invalid name will list all valid names in chat
```
Fixes https://github.com/transhumandesign/kag-base/issues/1937
This PR changes `BlobCommands.as`.
The command `/scroll <name>` didn't work outside of TTH mode.
I fixed it by executing `SetupScrolls()` if `"all scrolls"` doesn't exist in CRules@.
In testing, `SetupScrolls()` will only be executed once, the first time you try to use `/scroll <name>`.
When an invalid name is used, all valid names will be listed in chat.
When no name is used, a random scroll will be spawned.
This is the same behavior as `/seed <name>` from the seed PR here: …
=> [fixed] "/scroll <name>" chat command not working

Rules/CommonScripts/ChatCommands/PlayerCommands.as
```
[fixed] Heal chat command not working properly
```
Fixes https://github.com/transhumandesign/kag-base/issues/1933
I changed the heal amount calculation in `PlayerCommands.as`, it now works like this:
Inputted health is rounded to a multiple of 0.25 (i.e. a quarter heart).
To be valid, inputted health must be 0.25 or higher, or -0.25 or lower.
`Specify a valid amount to heal` was changed to `Specify a valid amount (at least 0.25 or -0.25)`
0.49 health will be rounded down to 0.25 health, 0.74 to 0.5 etc.
-0.49 health will be rounded up to -0.25 health, -0.74 to -0.5 etc.
The game will not say that you are at full health when trying to heal a very tiny value (see the linked issue above).
Your …
=> [fixed] Heal chat command bug

Entities/Common/Building/PlacementCommon.as
- But please look for odd cases.
```
[changed] Seed can now be placed on non-static blobs
[fixed] Seed can no longer be placed on another seed
```
Fixes https://github.com/transhumandesign/kag-base/issues/1996
Seed can now be placed on any blob unless it is static.
Therefore you can place seed on a Saw, Dinghy or other blobs that impose a no build area but not on a Building.
Also made it so you cannot place a Seed on another Seed.
Placing seed on a stuck arrow still works.
Briefly verified in offline.
=> [changed] Seed can be placed on non-static blobs

Entities/Common/Controls/StandardControls.as
- READY: this PR is (to the best of your knowledge) ready to be incorporated into the game.
Before update, the player could hold an item in his hand and switch bomb/shot type at the same time, for now it's broken.
This fix just moving command putinheld to cycle clause, no problems were noticed during testing on localhost and Gruhsha CTF.
It related to issue #2059
1. Join in Sandbox/CTF server or host it
2. Change class to knight
3. Spawn via command `/s mat_bombs` four bombs and one water bomb via command `/s mat_waterbombs`
4. Pickup three normal bombs and one water
5. Put fourth bomb in hand
6. Try to press inventory button fast for item cycling
7. ...
8. Cycle is dont work.
=> fix bomb/arrow cycle with item in hand

Rules/CommonScripts/ChatCommands.cfg, Rules/CommonScripts/ChatCommands/BlobCommands.as, Rules/CommonScripts/DefaultChatCommands.as
```
[changed] "/seed" can now be used to spawn grain_plant, bush and flowers, too. "/tree" removed.
[changed] When "/seed" is used without a type, it will spawn a random seed rather than a pine tree seed.
```
Fixes https://github.com/transhumandesign/kag-base/issues/1939
This PR makes changes to `BlobCommands.as` to allow `/seed` to be able to spawn `grain_plant`, `bush` and `flowers`.
When only `/seed` is used without an argument, it will spawn a random seed instead of always a pine seed.
Removed `/tree` since the command is now also for types of seeds that aren't trees. The user will have to type in `tree_pine` and `tree_bushy` instead of just `pine` and `bushy`, as a small side effect. …
=> [added] "/seed" chat command can now spawn grain plant, flowers and bush

Entities/Vehicles/Common/Seats.as
```
[fixed] Bison's or vehicle's damage owner did not get unset when sitting player died
```
Fixes https://github.com/transhumandesign/kag-base/issues/2037
When playing online and dying while sitting on a catapult or a bison, the game correctly runs `onDetach()` in `Seats.as`.
However, 
```
print("detached is null ? " + (detached is null));
print("detached player is null ? " + (detached.getPlayer() is null));
print("detached tag dead ? " + (detached.hasTag("dead")));
```
will yield false, false, false on client and false, true, true on server.
Because the player was already null on server, the damage player didn't get unset.
To fix the issue, this PR adds a check if the detached blob has the …
=> [fixed] Bison's or vehicle's damage owner did not get unset when sitting player died

Rules/CommonScripts/MechanismsServer.as
- **READY**:
Moves the power grid debug render to slot 6 instead of 1.
The intention is so that g_debug 1 isn't so cluttered and debuggers wont have a red screen when they just want to look at shapes and such.
Slot 6 is unoccupied by anything else so it is perfect.
=> [modified] power grid rendering moved to g_debug 6

Entities/Characters/Builder/BuilderInventory.as, Scripts/Default/DefaultGUI.as
This pull request requires engine pr 236 to be merged.
Fixes coins offset
Add another new line to builder hover text so text does not get blocked by icons
Closes #594
=> [fix] Icon offset for new engine PR

Rules/CommonScripts/DefaultVotes.as, Rules/CommonScripts/Report.as, Rules/CommonScripts/ReportCommon.as
Add's voting to kick logging that gets sent to bsion.
What the message looks like:
Known issues:
- Admin forcing to cancel does not call Pass() whatsoever, but forcing to pass does
=> [new] Start of voting to kick logging

Entities/Vehicles/Common/VehicleGUI.as
- **READY**
Fixes https://github.com/transhumandesign/kag-base/issues/2209
In offline singleplayer, when using a mounted bow or a catapult, you get to have infinite ammo.
But there is no ammo count drawn to indicate this.
This PR makes changes to `VehicleGUI.as` to show an infinite symbol.
I made some other changes to simplify the code a bit in `drawAmmoCount()` but let me know if it is good or not.
|   | Before | After |
| ----------- | -------------| -------------| 
| Bow in Save The Princess | ![BowBefore](https://github.com/user-attachments/assets/b2fbb059-4297-4fea-9777-5efbac99532b) | ![BowAfter](https://github.com/user-attachments/assets/330d7b4e-314d-41b1-89fe-7623987b01fa) |
| Catapult in other gamemodes | ![CatapultBefore](https://github.com/user-attachments/assets/dedf3a42-fb82- …
=> [changed] Infinite ammo count is shown in singleplayer

Entities/Vehicles/Catapult/Catapult.as
Fixes https://github.com/transhumandesign/kag-base/issues/2224
Catapult has a bug where it doesn't shoot blobs properly in offline.
It looks like this happens because the logic for the firing ( `v.onFire()` and `v.SetFireDelay()` ) is executed twice in offline.
This PR fixes that by adding a check for `!isServer()` in `Catapult.as`.
I tried adding the check to `Vehicle.as` at line 194
`else if (cmd == this.getCommandID("fire client") && isClient())`
--> `else if (cmd == this.getCommandID("fire client") && isClient() && !isServer())`
but it didn't fix the issue so I'm going ahead with the fix mentioned above.
After this PR, Catapult fires blobs properly and plays the firing sound in both offline …
=> [fixed] Catapult couldn't fire properly in offline

Entities/Characters/Builder/BuilderLogic.as
New logic for queued hits in BuilderLogic.as does not function, causing builders to periodically not break blocks. 
Safe reading a CBitStream after the onCommand hook fails, always reading the values in onCommand and caching them instead of the CBitStream fixes the issue.
Mentioned in issue https://github.com/transhumandesign/kag-base/issues/2065
1. Swap to builder
2. Continually break blocks until a swing does not register
=> [fixed] Builder Queued Hit Fix

Rules/CommonScripts/Spectator.as
Probably, after adding cinematic camera, while you rebinded keys **ZOOM IN** and **ZOOM OUT** in settings, in spectator team you can zoom in and out only with mouse scroll, because it using hardcoded `controls.mouseScrollUp` and `controls.mouseScrollDown` keys instead of `controls.getActionKeyKey(AK_ZOOMOUT)` and `controls.getActionKeyKey(AK_ZOOMIN)`.
This pull-request fixing it.
1. Join on server/single sandbox
2. Change team to spectator
3. Rebind keys ZOOM IN and ZOOM OUT
4. Try to use new binds
=> [fixed] camera zoom in spectator doesnt using action keys 

Entities/Characters/Archer/ArcherLogic.as
Fixes https://github.com/transhumandesign/kag-base/issues/2074
This PR fixes a bug where you could harvest your own arrows in mid air, preventing you from shooting arrows at low charge while grappling from a ceiling. Arrows can now only be harvested if they are static.
This bug only happened in online. Tested and it doesn't happen anymore on a dedicated server.
Removed a duplicate `if (arrow !is null)` check.
=> [fixed] don't pick up your own shot arrows from mid air

Entities/Vehicles/Airships/Airship.cfg, Entities/Vehicles/Airships/Bomber.cfg
```
[fixed] Team conversion bar for Airship and Bomber wasn't shown
[changed] Airship and Bomber will not decay if left with an enemy
[changed] Show healthbar for Airship and Bomber
```
Fixes https://github.com/transhumandesign/kag-base/issues/2216
Fixes https://github.com/transhumandesign/kag-base/issues/2211
Fixes https://github.com/transhumandesign/kag-base/issues/2206
Although Airship and Bomber can be converted, the graphics for it weren't shown. Now they are.
Although Airship and Bomber can be converted, they will decay if left with an enemy. Converting and decaying at the same time is stupid. So I removed the decaying when left with an enemy.
Although other vehicles and boats have a …
=> [fixed] Airship & Bomber issues

Rules/TDM/Scripts/TDM.as, Scripts/MapLoaders/BasePNGLoader.as
TDM will now spawn bombs when a map uses the bombs colour. It no longer spawns them every 2000 ticks, instead it just does it once.
=> [fix] Map loader now spawns bombs

Rules/CTF/gamemode.cfg, Rules/CommonScripts/PlayerNames.as, Rules/Sandbox/gamemode.cfg, Rules/Simple/gamemode.cfg, Rules/SmallCTF/gamemode.cfg, Rules/TDM/gamemode.cfg, Rules/WAR/gamemode.cfg
- **READY**: this PR is (to the best of your knowledge) ready to be incorporated into the game. But can still be tweaked if something interesting is suggested.
Fixes #282
Moves player names and hearts ui from engine to scripts. Also added fade-in behavior.
Along with this pr there should be an engine pr to remove names from engine.
1) join server/sinlgeplayer
2) spawn bots
3) see this:
https://github.com/transhumandesign/kag-base/assets/26719582/44094844-4805-4258-a36c-19d332a0ee23
https://github.com/transhumandesign/kag-base/assets/26719582/49160f41-c2cd-4f9b-bf39-78aa22b06200
=> Scripted playernames.

Entities/Common/Emotes/EmoteHotkeys.as
If EmoteMenu.as is not in the gamemode.cfg, when a player spawns as a blob, it errors.
The EmoteMenu.as script, calls the function `LoadEmotes(rules, cfg)`, inside of which sets `this.set("emotes", @emotesDict);`
If EmoteMenu.as is not in gamemode.cfg, then the rules "emotes" is null.
In a player's blob, the script EmoteHotkeys.as, calls readEmoteBindings in onInit()
In that function, this happens `getRules().get("emotes", @emotes);`
Then it promptly uses the variable emotes, which may be null. Hence, the error.
This edit simply halts getting emotebinds if EmoteMenu.as isn't in rules.
It halts in onTick if the size of emotebinds was 0, as well, to prevent attempting to use an empty emotebinds. …
=> [fixed] No EmoteMenu.as in gamemode.cfg error 

Entities/Vehicles/Common/Vehicle.as
```
[fixed] Couldn't swap ballista ammo in offline
```
Fixes https://github.com/transhumandesign/kag-base/issues/2173
This PR fixes that you couldn't switch from regular ballista bolts to bomb bolts in offline.
In fact, although it visually looks like nothing happens when you press the inventory key, the game actually changes the ammo twice.
**Vehicle.as**
```
void onCommand(CBlob@ this, u8 cmd, CBitStream @params)
...
/// SWAP AMMO
else if (cmd == this.getCommandID("swap_ammo") && isServer())
{
CPlayer@ p = getNet().getActiveCommandPlayer();
if (p is null) return;
CBlob@ b = p.getBlob();
if (b is null) return;
// don't swap ammo if only 1 ammo type
if (v.ammo_types.size() <= 1) return;
// …
```
=> [fixed] Couldn't swap ballista ammo in offline

Rules/CommonScripts/ChatCommandCommon.as, Rules/CommonScripts/ChatCommandManager.as, Rules/CommonScripts/ChatCommands/BlobCommands.as, Rules/CommonScripts/ChatCommands/MiscCommands.as
Quality of life improvements for the new command system. Allow syntax prior to the command rework. Tested on my balance mod since the command rework was added.
Address some common issues when using commands. Makes the following changes:
- Ignore character case when using commands
- Allow ! instead of / when using commands
- Default to the spawn command if no other command matches
1. Enable commands by setting sv_test to 1
2. Type !Keg to spawn a keg
git branch used: https://github.com/mehwaffle10/kag-base/tree/command-qol
=> Command Quality of Life

Rules/CommonScripts/ChatCommands/BlobCommands.as
cc @Vam-Jam 
It is now possible to do `/spawn keg 100`, for instance. Counts != 1 are admin-only to avoid abuse, it would mostly be useful for dev and testing.
Blobs are spawned in the same position, which would be particularly easy to abuse as it quickly gets very laggy.
```
/s keg 10
!keg 10
```
=> Optional spawn command count parameter for admins

Entities/Industry/Saw/Saw.as
Fixes https://github.com/transhumandesign/kag-base/issues/2194
This fixes that your Saw didn't deactive when you got killed by it (in offline).
When getting killed by your Saw, it would actually toggle twice. So I applied the same fix as here https://github.com/transhumandesign/kag-base/pull/2186 , checking for `!isServer()` on the client-side command.
Tested in offline and online, works correctly.
=> [fixed] Saw didn't deactivate when killing a teammate in offline

Entities/Vehicles/Common/VehicleConvert.as
This PR makes it so that converting a vehicle or outpost will also convert its inventory items (only if the item isn't neutral team, that means chickens or sharks will not change team).
Previously, drills and mines would stay in the previous team. This could lead to scenarios where a blue mine could fall out of a red outpost that was destroyed.
Tested in offline and online, works.
1. Be in blue team
2. Spawn an outpost or dinghy
3. Put in a drill and a mine
4. Have the outpost or dinghy get converted to red team (spawn a few red builders near it)
5. After conversion, spawn a few bombs to destroy the outpost or dinghy.
6. Notice blue drill and blue mine coming out. **After this PR, the items …
=> [fixed] Converting a vehicle will also convert items in inventory

Entities/Common/Taunts/TauntMenu.as
Fixes https://github.com/transhumandesign/kag-base/issues/2199
This PR makes a small adjustment to `TauntMenu.as` to make it work in offline.
It works in offline and online now, displaying the taunt in the chat.
I'm not sure what the code / command stuff is for, if `SHOW_IN_CHAT` is false.
I tried it out but nothing happens. So I'm not touching it.
Anyway, taunts as we know them are fixed in offline with this PR.
=> [fixed] Taunt Menu was not working in offline

Entities/Common/Decaying/DecayQuantity.as
```
[fixed] False admin alert when gold vanished by decaying
```
Fixes https://github.com/transhumandesign/kag-base/issues/1513
Pebble of gold could decay after 66 sec in TDM causing a false admin alert message.
Although @eps0003 suggested that blobs should be tagged by the way they are destroyed and letting `AlertAdminOnDie.as` decide which tags are getting reported, this would mean changing every script that has `server_Die()` or `server_Hit()` in it.
For now, I simply added `this.Tag("AdminAlertIgnore");` to `DecayQuantity.as` so the specific situation of gold decaying and alerting admin doesn't happen.
Admin alert message is for when players throw gold into the void, not for when materials …
=> [fixed] Gold decaying would alert admin (TDM)

Entities/Common/Controls/StandardControls.as, Entities/Common/Controls/StandardPickup.as
- **READY**
* Fixes a client side crash that can occur when players use the pickup-menu.
It also fixes "random" crashes that people have.
* Fixes an issue where players could throw blobs that weren't attached to their player.
Cause of the crash:
Line 13 StandardPickup.as
```
CBlob@[] blobs;
this.set("pickup blobs", blobs);
CBlob@[] closestblobs;
this.set("closest blobs", closestblobs);
```
**This PR also changes how pickup deals with platforms.**
Players cannot pickup through platforms that are facing against them, but can pickup through platforms if they are facing with them. (this addition to this PR means that #1864 and #1342 can be closed)
resolves #1864, resolves #1342, resolves #2087
=> [fixed] pickup crash

Entities/Materials/Explosive/MaterialWaterBomb.cfg
Fixes https://github.com/transhumandesign/kag-base/issues/2088
Items that can be stacked to more than 1 will have their inventory name in plural e.g. "fire arrows", whereas items that can not be stacked will be in singular e.g. "bomb".
However, although water bomb cannot be stacked, its inventory name was in plual, so this PR fixes the name to be in singular.
=> [fixed] Water Bomb name is singular

Rules/CommonScripts/ChatCommands/BlobCommands.as
Fixes https://github.com/transhumandesign/kag-base/issues/2178
`"/crate"` spawned a crate that was not initialized, via `server_MakeCrate("", "", 0, team, pos);`.
This means that if an enemy picks up the crate, it will change color and it does not pick materials from the ground.
For consistency reasons, I made this PR which changes the crate command logic so `"/crate"` will use `server_CreateBlob("crate", team, pos);`.
Now the crate command's default crate will behave like any other empty crate that you can buy, craft at a workbench or spawn in via `"/s crate"`. It will __not__ change color when picked by the enemy, and it __will__ pick materials from the ground.
Tested, works.
=> [fixed] "/crate" will spawn an initialized crate

Entities/Natural/Trees/BushyTreeLogic.as, Entities/Natural/Trees/LogsOnDeath.as, Entities/Natural/Trees/PineTreeLogic.as, Entities/Natural/Trees/TreeCommon.as, Entities/Natural/Trees/TreeSync.as
[dev] also made all references to TreeSegment[] into a TreeSegment@[] to avoid incorrect copy construction
Observe trees, before this PR all background leaves for the pine would be to the right.  
This is because the TreeSegment copy constructor is called but doesn't properly copy the random seed. Instead, make it so that the list is a list of handles, so the copy constructor doesn't need to get involved in the first place.
Should make sure trees are still synced between players.
There were visual tweaks to make it so that the leaves are always shown on both sides of the pine tree. The random offsets were edited for visual style reasons.
Need to test on vanilla too
Sample screenshot:
=> Fix tree segments being one-sided/having broken visual randomness

Entities/Items/Explosives/KegVoodoo.as
Closes #2305
Test online and offline:
- Kegs broken without exploding (shouldn't shake)
- Kegs exploded from contact (should shake, was working)
- Kegs exploded from the fuse (should shake, wasn't working)
=> [fixed] online, kegs exploding from fuses didn't cause screenshake

Entities/Characters/Builder/BuilderLogic.as
Unsure what is actually going in the pickaxe code. Hitdata.tilepos only contains data when actually hitting a tile, but tilepos seems to contain the correct position when hitting a blob.
Another fix could be editing line 610 and use b.getPosition() as suggested by Gingerbeard. 
Will do more testing later.
Credits to @Gingerbeard5773 
Closes #2082
=> [fix] Tilepos on blob hits being set to 0,0 instead of an actual tilepos

Entities/Industry/Trading/Trader.as
Fixes https://github.com/transhumandesign/kag-base/issues/1977#issuecomment-2571427373
When there is a dead trader and you rejoin, he will make a death scream even though he has been dead for a while.
This changes that so the death scream on rejoin won't happen. It will only happen when the trader dies.
Tested on dedicated server, it works.
=> [fixed] Dead trader won't do death scream again when rejoining

Entities/Materials/MaterialCommon.as
Should close #2315
When two (or more) materials on the floor tick at the same time with different qty's, it could result in the lower quantity being duplicated.
The reason for this is if both the lower qty and higher qty item call `merge` at the same tick, the lower qty item would be added twice & killed twice.
This patch just set's the lower qty item to 0 and checks if quantity is not 0 before merging.
=> [fix] Material duping

Entities/Common/Movement/FallDamage.as
In the standard situation, when trying to jump on a trampoline for a while, the player gets a stun:
https://github.com/transhumandesign/kag-base/assets/64691722/5728a98d-23bc-4a13-99f9-62967c078928
With the fix, the player will no longer get stun from jumping on the trampoline (including from a lower height)
https://github.com/transhumandesign/kag-base/assets/64691722/22156bef-395f-4181-9d91-003d8e8e8a47
1. Build a small pillar of blocks upwards
2. Put the trampoline underneath
3. Climb the pole and jump from it onto the trampoline
4. ...
5. STUN!
=> [fixed] fix stun, when you jumping on trampoline

Entities/Items/Bucket/Bucket.as, Entities/Items/Bucket/Bucket.cfg
- **READY**
```
[fixed] filled bucket will not splash when destroyed with 1 splash remaining
[fixed] Bucket could only splash once (offline)
[fixed] Bucket sprite did not update when used (online)
[fixed] Bucket sprite did not update when falling in water
[fixed] Bucket sprite did not update when hit by a splash hit
[fixed] Bucket sprite did not update after water count is depleted from spam decay hits
[fixed] Splashing a filled bucket applied force to the wrong team
```
Fixes https://github.com/transhumandesign/kag-base/issues/2068
Fixes https://github.com/transhumandesign/kag-base/issues/2143
Fixes https://github.com/transhumandesign/kag-base/issues/2142
Fixes https://github.com/transhumandesign/kag-base/issues/2164
This PR aims to fix bugs related to splashing a filled bucket.
|  | …
=> [fixed] 7 bugs related to filled bucket

Entities/Common/Movement/FallDamage.as
```
[fixed] You no longer can take fall damage twice on the same tick
```
Fixes https://github.com/transhumandesign/kag-base/issues/2183
When applying the fall damage hit in `FallDamage.as`, the game time is saved to the blob.
At the beginning of `onCollision()` the code drops out if it detects that it's the same tick again so it doesn't apply the hit twice.
I'm not sure why it happens in the first place. This is just a simple fix I came up with. Of course it could be worth looking for the root of the problem.
Tested in offline and online, works correctly. 
Build a construction like in the screenshot from the issue linked above.
You have to be standing on a corner with the block being on your …
=> [fixed] You no longer can take fall damage twice on the same tick

Entities/Industry/CTFShops/Quarry/Quarry.as
Fixes https://github.com/transhumandesign/kag-base/issues/2262
The command "add fuel" was only run on the server, so the spritelayer wasn't being set.
I added "add fuel client" command that is run client-side and synced `fuel_prop` in order to update the spritelayer.
In offline and online, it works correctly now. 
* Loading wood correctly set the spritelayer, the higher the amount, the more is shown visibly. 
* The wood will visibly decrease over time.
=> [fixed] Wood layer was missing when loading wood to a quarry in online

Entities/Common/Attacks/FleshHit.as
Fixes https://github.com/transhumandesign/kag-base/issues/1753
This PR changes `FleshHit.as` to not produce flesh gibs when `g_kidssafe` is on.
Originally addressed in https://github.com/transhumandesign/kag-base/pull/1854
Tested in offline, works.
=> [fixed] No flesh gibs when kidssafe is turned on

Rules/CommonScripts/PlayerCamera.as
Fixes https://github.com/transhumandesign/kag-base/issues/2307
`deathTime` didn't change between maps so toggling would not work because of the condition `getGameTime() > deathTime` at line 371 in `PlayerCamera.as`.
Now, when a new map loads and rules script `PlayerCamera.as` restarts, the `Reset()` function now sets `deathTime` back to 0.
The bug itself and the bug fix were verifed on dedicated server.
=> [fixed] Right mouse key failed to toggle cinematic camera after a new map loads

Entities/Industry/Drill/Drill.as
local can be null. this fixes it.
Put a bunch of drills on a map, load the map, you should see null reference in console.
=> [fix] drill null onrender
